<%@ Page Title="" Language="C#" MasterPageFile="~/SuperForm/SuperForm.master" AutoEventWireup="true" CodeFile="aspnet_mask_masks.aspx.cs" Inherits="SuperForm_aspnet_mask_masks" %>
<%@ Register TagPrefix="obout" Namespace="Obout.SuperForm" Assembly="obout_SuperForm" %>
<%@ Register TagPrefix="ajaxToolkit" Namespace="AjaxControlToolkit" Assembly="AjaxControlToolkit" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">

</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <br />
    
    <span class="tdText"><b>ASP.NET Super Form - Edit Masks</b></span>
    
    <br /><br />

    <ajaxToolkit:ToolkitScriptManager ID="ToolkitScriptManager1" runat="server" />
    
    <obout:SuperForm ID="SuperForm1" 
        DataSourceID="SqlDataSource1"
        AutoGenerateRows="false"
        AutoGenerateInsertButton="true"
        AutoGenerateEditButton="true"
        AutoGenerateDeleteButton="true"
        DataKeyNames="EmployeeID"
        RunAt="server"
        AllowPaging="true"
        DefaultMode="Insert"
        OnItemInserted="SuperForm1_ItemInserted"
        OnItemCommand="SuperForm1_ItemCommand">
        <Fields>
            <obout:BoundField DataField="EmployeeID" HeaderText="Employee ID" ReadOnly="true" InsertVisible="false" />
            <obout:BoundField DataField="FirstName" HeaderText="First Name" Required="true" />
            <obout:BoundField DataField="LastName" HeaderText="Last Name" Required="true" />
            <obout:DateField DataField="BirthDate" HeaderText="Birth Date" DataFormatString="{0:MM/dd/yyyy}" ApplyFormatInEditMode="true" Required="true">
                <Masks>
                    <ajaxToolkit:MaskedEditExtender ID="MaskedEditExtender1" runat="server" Mask="99/99/9999" MaskType="Date"  />
                </Masks>
            </obout:DateField>
            <obout:DateField DataField="HireDate" HeaderText="Hire Date" DataFormatString="{0:MM/dd/yyyy}" ApplyFormatInEditMode="true" Required="true">
                <Masks>
                    <ajaxToolkit:MaskedEditExtender ID="MaskedEditExtender2" runat="server" Mask="99/99/9999" MaskType="Date"  />
                </Masks>
            </obout:DateField>
            <obout:BoundField DataField="Salary" HeaderText="Salary" Required="true">
                <Masks>
                    <ajaxToolkit:MaskedEditExtender ID="MaskedEditExtender3" runat="server" Mask="9,999,9999" 
                        MaskType="Number" InputDirection="RightToLeft"  />
                </Masks>
            </obout:BoundField>
            <obout:BoundField DataField="HomePhone" HeaderText="Phone">
                <Masks>
                    <ajaxToolkit:MaskedEditExtender ID="MaskedEditExtender4" runat="server" Mask="(999)999-9999" MaskType="Number"  />
                </Masks>
            </obout:BoundField>
        </Fields>
    </obout:SuperForm>


    <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
        ConnectionString="<%$ ConnectionStrings:NorthwindConnectionString %>" 
        ProviderName="<%$ ConnectionStrings:NorthwindConnectionString.ProviderName %>" 
        SelectCommand="SELECT EmployeeID, FirstName, LastName, BirthDate, HireDate, HomePhone, Salary, HomePhone FROM [Employees] ORDER BY EmployeeID DESC"
        UpdateCommand="UPDATE Employees SET FirstName=@FirstName, LastName=@LastName, BirthDate=@BirthDate, HireDate=@HireDate, 
                        Salary=@Salary, HomePhone=@HomePhone WHERE EmployeeID=@EmployeeID"
        InsertCommand="INSERT INTO Employees (FirstName, LastName, BirthDate, HireDate, Salary, HomePhone) 
                        VALUES (@FirstName, @LastName, @BirthDate, @HireDate, @Salary, @HomePhone)"
        DeleteCommand="DELETE FROM Employees WHERE EmployeeID=@EmployeeID"
        />
    
    <br /><br />
    
    <span class="tdText">
        The Super Form provides built-in support for attaching ASP.NET AJAX ControlToolkit MaskedEditExtender controls to the fields of the form.<br />
        Using this feature, you can enhance the experience of your end users and increase the usability of the form.<br /><br />
        
        Use the <b>Masks</b> collection to add extenders to the fields of the form.<br /><br />

        This example showcases the use of various types of masks:<br />
        <ul>
            <li><b>dates</b> - for the "Birth Date" and "Hire Date" fields.</li>
            <li><b>numbers/money amounts</b> - for the "Salary" field.</li>
            <li><b>phone numbers</b> - for the "Phone" field.</li>
        </ul>
        <br />
        Click in any of these fields to see the edit masks.
    </span>
</asp:Content>

