<%@ Page Title="" Language="C#" MasterPageFile="~/SuperForm/SuperForm.master" AutoEventWireup="true" CodeFile="aspnet_live_styles_datefield.aspx.cs" Inherits="SuperForm_aspnet_live_styles_datefield" %>
<%@ Register TagPrefix="obout" Namespace="Obout.SuperForm" Assembly="obout_SuperForm" %>
<%@ Register TagPrefix="obout" Namespace="Obout.ListBox" Assembly="obout_ListBox" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">

</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <br />
    
    <span class="tdText"><b>ASP.NET Super Form - Live Styles for DateFields</b></span>
    
    <br /><br />

    <table class="tdText">
        <tr>
            <td valign="top">
                Date picker style:<br />
                <obout:ListBox runat="server" ID="ListBox1" AutoPostBack="true" Height="100" OnSelectedIndexChanged="CalendarType_Changed">
                    <obout:ListBoxItem ID="ListBoxItem1" runat="server" Text="blocky_revert" />
                    <obout:ListBoxItem ID="ListBoxItem2" runat="server" Text="blue" />
                    <obout:ListBoxItem ID="ListBoxItem3" runat="server" Text="dark" />
                    <obout:ListBoxItem ID="ListBoxItem4" runat="server" Text="default" Selected="true" />
                    <obout:ListBoxItem ID="ListBoxItem5" runat="server" Text="desert" />
                    <obout:ListBoxItem ID="ListBoxItem6" runat="server" Text="expedia" />
                    <obout:ListBoxItem ID="ListBoxItem7" runat="server" Text="graphite" />
                    <obout:ListBoxItem ID="ListBoxItem8" runat="server" Text="lite" />
                    <obout:ListBoxItem ID="ListBoxItem9" runat="server" Text="orbitz" />
                    <obout:ListBoxItem ID="ListBoxItem10" runat="server" Text="simple" />
                    <obout:ListBoxItem ID="ListBoxItem11" runat="server" Text="style10" />
                </obout:ListBox>
            </td>
            <td width="25">&#160;</td>
            <td valign="top">
                Calendar icon:
                <table cellspacing="10">
                    <tr>
                        <td align="center">
                            <img src="../Calendar/styles/date_picker1.gif" alt="" />
                        </td>
                        <td>
                            <obout:OboutRadioButton runat="server" ID="DatePicker1" OnCheckedChanged="CalendarType_Changed" Text="date_picker1.gif" Checked="true" GroupName="DatePickerIcon" AutoPostBack="true" />
                        </td>
                    </tr>
                    <tr>
                        <td align="center">
                            <img src="../Calendar/styles/date_picker2.gif" alt="" />
                        </td>
                        <td>
                            <obout:OboutRadioButton runat="server" ID="DatePicker2" OnCheckedChanged="CalendarType_Changed" Text="date_picker2.gif" GroupName="DatePickerIcon" AutoPostBack="true" />
                        </td>
                    </tr>
                    <tr>
                        <td align="center">
                            <img src="../Calendar/styles/icon2.gif" alt="" />
                        </td>
                        <td>
                            <obout:OboutRadioButton runat="server" ID="DatePicker3" OnCheckedChanged="CalendarType_Changed" Text="icon2.gif" GroupName="DatePickerIcon" AutoPostBack="true" />
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>

    <br /><br />
    
    <obout:SuperForm ID="SuperForm1" Title="Order Details"
        DataSourceID="SqlDataSource1"
        AutoGenerateRows="False"
        AutoGenerateInsertButton ="True"
        AutoGenerateEditButton="True"
        AutoGenerateDeleteButton="True"
        DataKeyNames="OrderID"
        RunAt="server"
        AllowPaging="True" AllowDataKeysInsert="False" 
        DefaultMode="Edit"
         OnDataBound="SuperForm1_DataBound">
        <Fields>
            <obout:BoundField DataField="OrderID" HeaderText="Order ID" ReadOnly="true" InsertVisible="false" />
            <obout:BoundField DataField="ShipName" HeaderText="Ship Name" />
            <obout:BoundField DataField="ShipCity" HeaderText="Ship City" />
            <obout:DropDownListField DataField="ShipCountry" DisplayField="ShipCountry" HeaderText="Country" DataSourceID="SqlDataSource2" />
            <obout:DateField DataField="OrderDate" HeaderText="Order Date" DataFormatString="{0:MM/dd/yyyy}" ApplyFormatInEditMode="true" />
            <obout:DateField DataField="ShippedDate" HeaderText=" Shipped Date" DataFormatString="{0:MM/dd/yyyy}" ApplyFormatInEditMode="true" />
            <obout:DateField DataField="RequiredDate" HeaderText="Required Date" DataFormatString="{0:MM/dd/yyyy}" ApplyFormatInEditMode="true" />
        </Fields>
    </obout:SuperForm>

    <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
        ConnectionString="<%$ ConnectionStrings:NorthwindConnectionString %>" 
        ProviderName="<%$ ConnectionStrings:NorthwindConnectionString.ProviderName %>" 
        SelectCommand="SELECT OrderID, ShipName, ShipCity, ShipCountry, OrderDate, ShippedDate, RequiredDate FROM [Orders] ORDER BY OrderID DESC"
        UpdateCommand="UPDATE Orders SET ShipName=@ShipName, ShipCity=@ShipCity, ShipCountry=@ShipCountry, 
                       OrderDate=@OrderDate, ShippedDate=@ShippedDate, RequiredDate=@RequiredDate
                       WHERE OrderID=@OrderID"
        InsertCommand="INSERT INTO Orders (ShipName, ShipCity, ShipCountry, OrderDate, ShippedDate, RequiredDate)
                        VALUES(@ShipName, @ShipCity, @ShipCountry, @OrderDate, @ShippedDate, @RequiredDate)"
        DeleteCommand="DELETE FROM Orders WHERE OrderID = @OrderID">
    </asp:SqlDataSource>

    <asp:SqlDataSource ID="SqlDataSource2" runat="server" 
        ConnectionString="<%$ ConnectionStrings:NorthwindConnectionString %>" 
        ProviderName="<%$ ConnectionStrings:NorthwindConnectionString.ProviderName %>" 
        SelectCommand="SELECT DISTINCT ShipCountry FROM [Orders] ORDER BY ShipCountry ASC" />
    
    <br /><br />
    
    <span class="tdText">
        Add <b>DateField</b> objects to the <b>Fields</b> collection to manually specify the Date / DateTime fields of a Super Form.<br />
        This type of field will render an OboutTextBox control and an Obout Calendar control in add / edit mode, which will allow end users to modify the underlying data.<br />
        The Calendar control is configured to work in date picker mode and it is linked to the OboutTextBox control.<br /><br />

        In this sample we accessed the fields of the form in the Page_Load method to gain access to the Calendar controls added to the rows.<br />
        Thus we were able to set their <b>StyleFolder</b> and <b>DatePickerImagePath</b> properties.
    </span>
</asp:Content>

