<%@ Page Title="" Language="C#" MasterPageFile="~/SuperForm/SuperForm.master" AutoEventWireup="true" CodeFile="aspnet_validation_compare.aspx.cs" Inherits="SuperForm_aspnet_validation_compare" %>
<%@ Register TagPrefix="obout" Namespace="Obout.SuperForm" Assembly="obout_SuperForm" %>
<%@ Register TagPrefix="obout" Namespace="OboutInc.Calendar2" Assembly="obout_Calendar2_NET" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
    
</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <br />
    
    <span class="tdText"><b>ASP.NET Super Form - Validate using CompareValidator</b></span>
    
    <br /><br />

    <obout:SuperForm ID="SuperForm1" 
        Title="Registration Form"
        
        AutoGenerateRows="false"
        AutoGenerateInsertButton ="false"
        AutoGenerateEditButton="false"
        AutoGenerateDeleteButton="false"
        DataKeyNames="OrderID"
        RunAt="server"
        AllowPaging="false"
        DefaultMode="Insert"
        OnItemInserting="SuperForm1_Inserting">
        <Fields>
            <obout:BoundField DataField="EmailAddress" HeaderText="E-mail Address" Required="true" />
            <obout:BoundField DataField="ConfirmEmailAddress" HeaderText="Confirm E-mail" Required="true">
                <Validators>
                    <asp:CompareValidator runat="server" ValidationGroup="Group1" ControlToCompare="SuperForm1_EmailAddress" ErrorMessage="*" /> 
                </Validators>
            </obout:BoundField>
            <obout:BoundField DataField="FirstName" HeaderText="FirstName" Required="true" />
            <obout:BoundField DataField="LastName" HeaderText="LastName" Required="true" />
            <obout:CommandField ShowInsertButton="true" ShowCancelButton="false" 
                ButtonType="Button" ItemStyle-HorizontalAlign="Center" >
                <ItemStyle HorizontalAlign="Center"></ItemStyle>
            </obout:CommandField>
        </Fields>
    </obout:SuperForm>

    <asp:Panel runat="server" ID="MessagePanel" Visible="false" CssClass="tdText">        
        Thank you for your registration.
    </asp:Panel>

    <br /><br />
    
    <span class="tdText">
        The Super Form allows developers to validate the data typed by the end users into the fields using various approaches.<br /><br />
        This sample shows how to use a <b>CompareValidator</b> control to ensure that two fields of the form contain the same data.<br />
        Use the <b>Validators</b> collection to add a <b>CompareValidator</b> to one of the fields. When setting the <b>ControlToCompare</b><br />
        property of the validator, use the DataField of the field that will be used in the comparison,<br /> preceded by the ID of the form and a underline.<br /><br />
        In this sample we added a <b>CompareValidator</b> validator in the <b>Validators</b> collection of the "ComfirmEmailAddress" field,<br />
        to compare it against the "EmailAddress" field. Thus, we set the <b>ControlToCompare</b> property of the validator to <br />
        "SuperForm1_EmailAddress" ("SuperForm1" is the ID of the form control).
    </span>
</asp:Content>

