<%@ Page Title="" Language="C#" MasterPageFile="~/SuperForm/SuperForm.master" AutoEventWireup="true" CodeFile="aspnet_autoformat.aspx.cs" Inherits="SuperForm_aspnet_style_gallery" %>
<%@ Register TagPrefix="obout" Namespace="Obout.SuperForm" Assembly="obout_SuperForm" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <br />
    
    <span class="tdText"><b>ASP.NET Super Form - Auto Format</b></span>
    
    <br /><br />

    <table class="tdText" cellspacing="30">
        <tr>
            <td valign="top">
                No formatting:<br />
                <obout:SuperForm ID="SuperForm1" 
                    DataSourceID="SqlDataSource1"
                    AutoGenerateRows="true"
                    AutoGenerateInsertButton ="true"
                    AutoGenerateEditButton="true"
                    AutoGenerateDeleteButton="true"
                    DataKeyNames="OrderID"
                    RunAt="server"
                    AllowPaging="true"
                    FolderStyle="_">
                </obout:SuperForm>
            </td>
            <td valign="top">
                Colorful:<br />
                <obout:SuperForm ID="SuperForm2"
                    DataSourceID="SqlDataSource1"
                    AutoGenerateInsertButton ="True"
                    AutoGenerateEditButton="True"
                    AutoGenerateDeleteButton="True"
                    DataKeyNames="OrderID"
                    RunAt="server"
                    AllowPaging="True" AllowDataKeysInsert="False" CellPadding="4" 
                    EnableModelValidation="True" ForeColor="#333333" GridLines="None" FolderStyle="_">
                    <AlternatingRowStyle BackColor="White" />
                    <CommandRowStyle BackColor="#FFFFC0" Font-Bold="True" />
                    <FieldHeaderStyle BackColor="#FFFF99" Font-Bold="True" />
                    <FooterStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
                    <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
                    <PagerStyle BackColor="#FFCC66" ForeColor="#333333" HorizontalAlign="Center" />
                    <RowStyle BackColor="#FFFBD6" ForeColor="#333333" />
                </obout:SuperForm>
            </td>
        </tr>
        <tr>
            <td valign="top">
                Classic:<br />
                <obout:SuperForm ID="SuperForm3"
                    DataSourceID="SqlDataSource1"
                    AutoGenerateInsertButton ="True"
                    AutoGenerateEditButton="True"
                    AutoGenerateDeleteButton="True"
                    DataKeyNames="OrderID"
                    RunAt="server"
                    AllowPaging="True" AllowDataKeysInsert="False" CellPadding="4" 
                    EnableModelValidation="True" ForeColor="#333333" GridLines="None" FolderStyle="_">
                    <AlternatingRowStyle BackColor="White" />
                    <CommandRowStyle BackColor="#D1DDF1" Font-Bold="True" />
                    <EditRowStyle BackColor="#2461BF" />
                    <FieldHeaderStyle BackColor="#DEE8F5" Font-Bold="True" />
                    <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                    <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                    <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
                    <RowStyle BackColor="#EFF3FB" />
                </obout:SuperForm>
            </td>
            <td valign="top">
                Simple:<br />
                <obout:SuperForm ID="SuperForm4"
                    DataSourceID="SqlDataSource1"
                    AutoGenerateInsertButton ="True"
                    AutoGenerateEditButton="True"
                    AutoGenerateDeleteButton="True"
                    DataKeyNames="OrderID"
                    RunAt="server"
                    AllowPaging="True" AllowDataKeysInsert="False" CellPadding="4" 
                    EnableModelValidation="True" ForeColor="#333333" GridLines="None" FolderStyle="_">
                    <AlternatingRowStyle BackColor="White" />
                    <CommandRowStyle BackColor="#C5BBAF" Font-Bold="True" />
                    <EditRowStyle BackColor="#7C6F57" />
                    <FieldHeaderStyle BackColor="#D0D0D0" Font-Bold="True" />
                    <FooterStyle BackColor="#1C5E55" Font-Bold="True" ForeColor="White" />
                    <HeaderStyle BackColor="#1C5E55" Font-Bold="True" ForeColor="White" />
                    <PagerStyle BackColor="#666666" ForeColor="White" HorizontalAlign="Center" />
                    <RowStyle BackColor="#E3EAEB" />
                </obout:SuperForm>
            </td>
        </tr>
        <tr>
            <td valign="top">
                Professional:<br />
                <obout:SuperForm ID="SuperForm5"
                    DataSourceID="SqlDataSource1"
                    AutoGenerateInsertButton ="True"
                    AutoGenerateEditButton="True"
                    AutoGenerateDeleteButton="True"
                    DataKeyNames="OrderID"
                    RunAt="server"
                    AllowPaging="True" AllowDataKeysInsert="False" CellPadding="4" 
                    EnableModelValidation="True" ForeColor="#333333" GridLines="None" FolderStyle="_">
                    <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
                    <CommandRowStyle BackColor="#E2DED6" Font-Bold="True" />
                    <EditRowStyle BackColor="#999999" />
                    <FieldHeaderStyle BackColor="#E9ECF1" Font-Bold="True" />
                    <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                    <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                    <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
                    <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
                </obout:SuperForm>
            </td>
            <td valign="top">
                Autumn:<br />
                <obout:SuperForm ID="SuperForm6"
                    DataSourceID="SqlDataSource1"
                    AutoGenerateInsertButton ="True"
                    AutoGenerateEditButton="True"
                    AutoGenerateDeleteButton="True"
                    DataKeyNames="OrderID"
                    RunAt="server"
                    AllowPaging="True" AllowDataKeysInsert="False" BackColor="White" 
                    BorderColor="#CC9966" BorderStyle="None" BorderWidth="1px" CellPadding="4" 
                    EnableModelValidation="True" FolderStyle="_">
                    <EditRowStyle BackColor="#FFCC66" Font-Bold="True" ForeColor="#663399" />
                    <FooterStyle BackColor="#FFFFCC" ForeColor="#330099" />
                    <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="#FFFFCC" />
                    <PagerStyle BackColor="#FFFFCC" ForeColor="#330099" HorizontalAlign="Center" />
                    <RowStyle BackColor="White" ForeColor="#330099" />
                </obout:SuperForm>
            </td>
        </tr>
        <tr>
            <td valign="top">
                Oceanica:<br />
                <obout:SuperForm ID="SuperForm7"
                    DataSourceID="SqlDataSource1"
                    AutoGenerateInsertButton ="True"
                    AutoGenerateEditButton="True"
                    AutoGenerateDeleteButton="True"
                    DataKeyNames="OrderID"
                    RunAt="server"
                    AllowPaging="True" AllowDataKeysInsert="False" BackColor="White" 
                    BorderColor="#3366CC" BorderStyle="None" BorderWidth="1px" CellPadding="4" 
                    EnableModelValidation="True" FolderStyle="_">
                    <EditRowStyle BackColor="#009999" Font-Bold="True" ForeColor="#CCFF99" />
                    <FooterStyle BackColor="#99CCCC" ForeColor="#003399" />
                    <HeaderStyle BackColor="#003399" Font-Bold="True" ForeColor="#CCCCFF" />
                    <PagerStyle BackColor="#99CCCC" ForeColor="#003399" HorizontalAlign="Left" />
                    <RowStyle BackColor="White" ForeColor="#003399" />
                </obout:SuperForm>
            </td>
            <td valign="top">
                Brown Sugar:<br />
                <obout:SuperForm ID="SuperForm8"
                    DataSourceID="SqlDataSource1"
                    AutoGenerateInsertButton ="True"
                    AutoGenerateEditButton="True"
                    AutoGenerateDeleteButton="True"
                    DataKeyNames="OrderID"
                    RunAt="server"
                    AllowPaging="True" AllowDataKeysInsert="False" BackColor="#DEBA84" 
                    BorderColor="#DEBA84" BorderStyle="None" BorderWidth="1px" CellPadding="3" 
                    CellSpacing="2" EnableModelValidation="True" FolderStyle="_">
                    <EditRowStyle BackColor="#738A9C" Font-Bold="True" ForeColor="White" />
                    <FooterStyle BackColor="#F7DFB5" ForeColor="#8C4510" />
                    <HeaderStyle BackColor="#A55129" Font-Bold="True" ForeColor="White" />
                    <PagerStyle ForeColor="#8C4510" HorizontalAlign="Center" />
                    <RowStyle BackColor="#FFF7E7" ForeColor="#8C4510" />
                </obout:SuperForm>
            </td>
        </tr>
        <tr>
            <td valign="top">
                Slate:<br />
                <obout:SuperForm ID="SuperForm9"
                    DataSourceID="SqlDataSource1"
                    AutoGenerateInsertButton ="True"
                    AutoGenerateEditButton="True"
                    AutoGenerateDeleteButton="True"
                    DataKeyNames="OrderID"
                    RunAt="server"
                    AllowPaging="True" AllowDataKeysInsert="False" BackColor="White" 
                    BorderColor="#E7E7FF" BorderStyle="None" BorderWidth="1px" CellPadding="3" 
                    EnableModelValidation="True" GridLines="Horizontal" FolderStyle="_">
                    <AlternatingRowStyle BackColor="#F7F7F7" />
                    <EditRowStyle BackColor="#738A9C" Font-Bold="True" ForeColor="#F7F7F7" />
                    <FooterStyle BackColor="#B5C7DE" ForeColor="#4A3C8C" />
                    <HeaderStyle BackColor="#4A3C8C" Font-Bold="True" ForeColor="#F7F7F7" />
                    <PagerStyle BackColor="#E7E7FF" ForeColor="#4A3C8C" HorizontalAlign="Right" />
                    <RowStyle BackColor="#E7E7FF" ForeColor="#4A3C8C" />
                </obout:SuperForm>
            </td>
            <td valign="top">
                Sand &amp; Sky:<br />
                <obout:SuperForm ID="SuperForm10"
                    DataSourceID="SqlDataSource1"
                    AutoGenerateInsertButton ="True"
                    AutoGenerateEditButton="True"
                    AutoGenerateDeleteButton="True"
                    DataKeyNames="OrderID"
                    RunAt="server"
                    AllowPaging="True" AllowDataKeysInsert="False" 
                    BackColor="LightGoldenrodYellow" BorderColor="Tan" BorderWidth="1px" 
                    CellPadding="2" EnableModelValidation="True" ForeColor="Black" GridLines="None" FolderStyle="_">
                    <AlternatingRowStyle BackColor="PaleGoldenrod" />
                    <EditRowStyle BackColor="DarkSlateBlue" ForeColor="GhostWhite" />
                    <FooterStyle BackColor="Tan" />
                    <HeaderStyle BackColor="Tan" Font-Bold="True" />
                    <PagerStyle BackColor="PaleGoldenrod" ForeColor="DarkSlateBlue" 
                        HorizontalAlign="Center" />
                </obout:SuperForm>
            </td>
        </tr>
        <tr>
            <td valign="top">
                Rainy Day:<br />
                <obout:SuperForm ID="SuperForm11"
                    DataSourceID="SqlDataSource1"
                    AutoGenerateInsertButton ="True"
                    AutoGenerateEditButton="True"
                    AutoGenerateDeleteButton="True"
                    DataKeyNames="OrderID"
                    RunAt="server"
                    AllowPaging="True" AllowDataKeysInsert="False" BackColor="White" 
                    BorderColor="#999999" BorderStyle="None" BorderWidth="1px" CellPadding="3" 
                    EnableModelValidation="True" GridLines="Vertical" FolderStyle="_">
                    <AlternatingRowStyle BackColor="#DCDCDC" />
                    <EditRowStyle BackColor="#008A8C" Font-Bold="True" ForeColor="White" />
                    <FooterStyle BackColor="#CCCCCC" ForeColor="Black" />
                    <HeaderStyle BackColor="#000084" Font-Bold="True" ForeColor="White" />
                    <PagerStyle BackColor="#999999" ForeColor="Black" HorizontalAlign="Center" />
                    <RowStyle BackColor="#EEEEEE" ForeColor="Black" />
                </obout:SuperForm>
            </td>
            <td valign="top">
                Snowy Pine:<br />
                <obout:SuperForm ID="SuperForm12"
                    DataSourceID="SqlDataSource1"
                    AutoGenerateInsertButton ="True"
                    AutoGenerateEditButton="True"
                    AutoGenerateDeleteButton="True"
                    DataKeyNames="OrderID"
                    RunAt="server"
                    AllowPaging="True" AllowDataKeysInsert="False" BackColor="White" 
                    BorderColor="#CCCCCC" BorderStyle="None" BorderWidth="1px" CellPadding="3" 
                    EnableModelValidation="True" FolderStyle="_">
                    <EditRowStyle BackColor="#669999" Font-Bold="True" ForeColor="White" />
                    <FooterStyle BackColor="White" ForeColor="#000066" />
                    <HeaderStyle BackColor="#006699" Font-Bold="True" ForeColor="White" />
                    <PagerStyle BackColor="White" ForeColor="#000066" HorizontalAlign="Left" />
                    <RowStyle ForeColor="#000066" />
                </obout:SuperForm>
            </td>
        </tr>
        <tr>
            <td valign="top">
                Lilacs in Mist:<br />
                <obout:SuperForm ID="SuperForm13"
                    DataSourceID="SqlDataSource1"
                    AutoGenerateInsertButton ="True"
                    AutoGenerateEditButton="True"
                    AutoGenerateDeleteButton="True"
                    DataKeyNames="OrderID"
                    RunAt="server"
                    AllowPaging="True" AllowDataKeysInsert="False" BackColor="White" 
                    BorderColor="White" BorderStyle="Ridge" BorderWidth="2px" CellPadding="3" 
                    CellSpacing="1" EnableModelValidation="True" GridLines="None" FolderStyle="_">
                    <EditRowStyle BackColor="#9471DE" Font-Bold="True" ForeColor="White" />
                    <FooterStyle BackColor="#C6C3C6" ForeColor="Black" />
                    <HeaderStyle BackColor="#4A3C8C" Font-Bold="True" ForeColor="#E7E7FF" />
                    <PagerStyle BackColor="#C6C3C6" ForeColor="Black" HorizontalAlign="Right" />
                    <RowStyle BackColor="#DEDFDE" ForeColor="Black" />
                </obout:SuperForm>
            </td>
            <td valign="top">
                Black &amp; Blue 1:<br />
                <obout:SuperForm ID="SuperForm14"
                    DataSourceID="SqlDataSource1"
                    AutoGenerateInsertButton ="True"
                    AutoGenerateEditButton="True"
                    AutoGenerateDeleteButton="True"
                    DataKeyNames="OrderID"
                    RunAt="server"
                    AllowPaging="True" AllowDataKeysInsert="False" BackColor="White" 
                    BorderColor="#999999" BorderStyle="Solid" BorderWidth="1px" CellPadding="3" 
                    EnableModelValidation="True" ForeColor="Black" GridLines="Vertical" FolderStyle="_">
                    <AlternatingRowStyle BackColor="#CCCCCC" />
                    <EditRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
                    <FooterStyle BackColor="#CCCCCC" />
                    <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
                    <PagerStyle BackColor="#999999" ForeColor="Black" HorizontalAlign="Center" />
                </obout:SuperForm>
            </td>
        </tr>
        <tr>
            <td valign="top">
                Black &amp; Blue 2:<br />
                <obout:SuperForm ID="SuperForm15"
                    DataSourceID="SqlDataSource1"
                    AutoGenerateInsertButton ="True"
                    AutoGenerateEditButton="True"
                    AutoGenerateDeleteButton="True"
                    DataKeyNames="OrderID"
                    RunAt="server"
                    AllowPaging="True" AllowDataKeysInsert="False" BackColor="#CCCCCC" 
                    BorderColor="#999999" BorderStyle="Solid" BorderWidth="3px" CellPadding="4" 
                    CellSpacing="2" EnableModelValidation="True" ForeColor="Black" FolderStyle="_">
                    <EditRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
                    <FooterStyle BackColor="#CCCCCC" />
                    <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
                    <PagerStyle BackColor="#CCCCCC" ForeColor="Black" HorizontalAlign="Left" />
                    <RowStyle BackColor="White" />
                </obout:SuperForm>
            </td>
            <td valign="top">
                Clover Field:<br />
                <obout:SuperForm ID="SuperForm16"
                    DataSourceID="SqlDataSource1"
                    AutoGenerateInsertButton ="True"
                    AutoGenerateEditButton="True"
                    AutoGenerateDeleteButton="True"
                    DataKeyNames="OrderID"
                    RunAt="server"
                    AllowPaging="True" AllowDataKeysInsert="False" BackColor="White" 
                    BorderColor="#336666" BorderStyle="Double" BorderWidth="3px" CellPadding="4" 
                    EnableModelValidation="True" GridLines="Horizontal" FolderStyle="_">
                    <EditRowStyle BackColor="#339966" Font-Bold="True" ForeColor="White" />
                    <FooterStyle BackColor="White" ForeColor="#333333" />
                    <HeaderStyle BackColor="#336666" Font-Bold="True" ForeColor="White" />
                    <PagerStyle BackColor="#336666" ForeColor="White" HorizontalAlign="Center" />
                    <RowStyle BackColor="White" ForeColor="#333333" />
                </obout:SuperForm>
            </td>
        </tr>
        <tr>
            <td valign="top">
                Apple Orchard:<br />
                <obout:SuperForm ID="SuperForm17"
                    DataSourceID="SqlDataSource1"
                    AutoGenerateInsertButton ="True"
                    AutoGenerateEditButton="True"
                    AutoGenerateDeleteButton="True"
                    DataKeyNames="OrderID"
                    RunAt="server"
                    AllowPaging="True" AllowDataKeysInsert="False" BackColor="White" 
                    BorderColor="#CCCCCC" BorderStyle="None" BorderWidth="1px" CellPadding="4" 
                    EnableModelValidation="True" ForeColor="Black" GridLines="Horizontal" FolderStyle="_">
                    <EditRowStyle BackColor="#CC3333" Font-Bold="True" ForeColor="White" />
                    <FooterStyle BackColor="#CCCC99" ForeColor="Black" />
                    <HeaderStyle BackColor="#333333" Font-Bold="True" ForeColor="White" />
                    <PagerStyle BackColor="White" ForeColor="Black" HorizontalAlign="Right" />
                </obout:SuperForm>
            </td>
            <td valign="top">
                Mocha:<br />
                <obout:SuperForm ID="SuperForm18"
                    DataSourceID="SqlDataSource1"
                    AutoGenerateInsertButton ="True"
                    AutoGenerateEditButton="True"
                    AutoGenerateDeleteButton="True"
                    DataKeyNames="OrderID"
                    RunAt="server"
                    AllowPaging="True" AllowDataKeysInsert="False" BackColor="White" 
                    BorderColor="#DEDFDE" BorderStyle="None" BorderWidth="1px" CellPadding="4" 
                    EnableModelValidation="True" ForeColor="Black" GridLines="Vertical" FolderStyle="_">
                    <AlternatingRowStyle BackColor="White" />
                    <EditRowStyle BackColor="#CE5D5A" Font-Bold="True" ForeColor="White" />
                    <FooterStyle BackColor="#CCCC99" />
                    <HeaderStyle BackColor="#6B696B" Font-Bold="True" ForeColor="White" />
                    <PagerStyle BackColor="#F7F7DE" ForeColor="Black" HorizontalAlign="Right" />
                    <RowStyle BackColor="#F7F7DE" />
                </obout:SuperForm>
            </td>
        </tr>
    </table>
    
    

    <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
        ConnectionString="<%$ ConnectionStrings:NorthwindConnectionString %>" 
        ProviderName="<%$ ConnectionStrings:NorthwindConnectionString.ProviderName %>" 
        SelectCommand="SELECT OrderID, ShipName, ShipCity, ShipCountry, Sent FROM [Orders]"
        InsertCommand="INSERT INTO Orders(ShipName, ShipCity, ShipCountry, Sent) VALUES(@ShipName, @ShipCity, @ShipCountry, @Sent)"
        UpdateCommand="UPDATE Orders SET ShipName=@ShipName, ShipCity=@ShipCity, ShipCountry=@ShipCountry, Sent=@Sent
                         WHERE OrderID=@OrderID"
        DeleteCommand="DELETE FROM Orders WHERE OrderID=@OrderID">
    </asp:SqlDataSource>
    
    <br /><br />
    
    <span class="tdText">
        All the elements of the Super Form can be customized using the properties exposed by the control.<br />
        The simplest and fastest way to change the appearance of the Super Form is to use the Auto Format feature<br />
        available in design mode. You can use one of the default formats as a template that you can further customize.
    </span>
</asp:Content>

