<%@ Page Title="" Language="C#" MasterPageFile="~/SuperForm/SuperForm.master" AutoEventWireup="true" CodeFile="aspnet_api_client_events.aspx.cs" Inherits="SuperForm_aspnet_api_client_events" %>
<%@ Register TagPrefix="obout" Namespace="Obout.SuperForm" Assembly="obout_SuperForm" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
    <script type="text/javascript">
        function SuperForm1_Adding() {
            return confirm('Are you sure you want to add this record?');
        }

        function SuperForm1_Inserting() {
            return confirm('Are you sure you want to insert this record?');
        }

        function SuperForm1_Editing() {
            return confirm('Are you sure you want to edit this record?');
        }

        function SuperForm1_Updating() {
            return confirm('Are you sure you want to update this record?');
        }

        function SuperForm1_Deleting() {
            return confirm('Are you sure you want to remove this record?');
        }

        function SuperForm1_Deleted() {
            alert('The record was deleted');
        }
    </script>
</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <br />
    
    <span class="tdText"><b>ASP.NET Super Form - Auto Generate Fields</b></span>
    
    <br /><br />
    
    <obout:SuperForm ID="SuperForm1" 
        DataSourceID="SqlDataSource1"
        AutoGenerateInsertButton ="True"
        AutoGenerateEditButton="True"
        AutoGenerateDeleteButton="True"
        DataKeyNames="OrderID"
        RunAt="server"
        AllowPaging="True" AllowDataKeysInsert="False" 
        EnableModelValidation="True">
        <ClientSideEvents 
            OnAdding="SuperForm1_Adding" OnInserting="SuperForm1_Inserting"
            OnEditing="SuperForm1_Editing" OnUpdating="SuperForm1_Updating" 
            OnDeleting="SuperForm1_Deleting" />
    </obout:SuperForm>

    <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
        ConnectionString="<%$ ConnectionStrings:NorthwindConnectionString %>" 
        ProviderName="<%$ ConnectionStrings:NorthwindConnectionString.ProviderName %>" 
        SelectCommand="SELECT * FROM [Orders]"
        UpdateCommand="UPDATE Orders SET ShipName=@ShipName, ShipCity=@ShipCity, ShipCountry=@ShipCountry, Sent=@Sent
                         WHERE OrderID=@OrderID">
        <UpdateParameters>
            <asp:Parameter Name="ShipName" Type="String" />
            <asp:Parameter Name="ShipCity" Type="String" />
            <asp:Parameter Name="ShipCountry" Type="String" />
            <asp:Parameter Name="Sent" Type="Boolean" />
            <asp:Parameter Name="OrderID" Type="Int32" />
        </UpdateParameters>
    </asp:SqlDataSource>
    
    <br /><br />
    
    <span class="tdText">
        The Super Form comes with predefined styles which are suited for most page layouts.<br /><br />
        The styles can be switched easily using the <b>FolderStyle</b> property, which needs to contain<br />
        the relative path to the folder containing the style to be used.
    </span>
</asp:Content>

