using System;
using System.Collections.Generic;

using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;

public partial class SuperForm_aspnet_commands_autogenerate : System.Web.UI.Page
{
    protected void Page_Load(object sender, EventArgs e)
    {
        SuperForm1.AutoGenerateEditButton = GenerateEditButton.Checked;
        SuperForm1.AutoGenerateDeleteButton = GenerateDeleteButton.Checked;
        SuperForm1.AutoGenerateInsertButton = GenerateInsertButton.Checked;
    }
}
