<%@ Page Title="" Language="C#" MasterPageFile="~/SuperForm/SuperForm.master" AutoEventWireup="true" CodeFile="aspnet_linked_enable.aspx.cs" Inherits="SuperForm_aspnet_linked_enable" %>
<%@ Register TagPrefix="obout" Namespace="Obout.SuperForm" Assembly="obout_SuperForm" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
    
</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <br />
    
    <span class="tdText"><b>ASP.NET Super Form - Enable / Disable Linked Fields</b></span>
    
    <br /><br />

    <obout:SuperForm ID="SuperForm1" 
        DataSourceID="SqlDataSource1"
        AutoGenerateRows="false"
        AutoGenerateInsertButton ="true"
        AutoGenerateEditButton="true"
        AutoGenerateDeleteButton="true"
        DataKeyNames="ProductID"
        RunAt="server"
        AllowPaging="true"
        DefaultMode="Edit">
        <Fields>
            <obout:BoundField DataField="ProductID" HeaderText="Product ID" ReadOnly="true" InsertVisible="false" />
            <obout:BoundField DataField="ProductName" HeaderText="Product Name" Required="true" />
            <obout:CheckBoxField DataField="Discontinued" HeaderText="Discontinued" FieldsToDisable="UnitPrice,UnitsInStock,UnitsOnOrder" />
            <obout:BoundField DataField="UnitPrice" HeaderText="Unit Price" />
            <obout:BoundField DataField="UnitsInStock" HeaderText="Units In Stock" />
            <obout:BoundField DataField="UnitsOnOrder" HeaderText="Units On Order" />
        </Fields>
    </obout:SuperForm>

    <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
        ConnectionString="<%$ ConnectionStrings:NorthwindConnectionString %>" 
        ProviderName="<%$ ConnectionStrings:NorthwindConnectionString.ProviderName %>" 
        SelectCommand="SELECT ProductID, ProductName, Discontinued, UnitPrice, UnitsInStock, UnitsOnOrder FROM [Products] ORDER BY ProductID DESC"
        UpdateCommand="UPDATE Products SET ProductName=@ProductName, Discontinued=@Discontinued, UnitPrice=@UnitPrice, 
                        UnitsInStock=@UnitsInStock, UnitsOnOrder=@UnitsOnOrder WHERE ProductID=@ProductID"
        InsertCommand="INSERT INTO Products (ProductName, Discontinued, UnitPrice, UnitsInStock, UnitsOnOrder) 
                        VALUES (@ProductName, @Discontinued, @UnitPrice, @UnitsInStock, @UnitsOnOrder)"
        DeleteCommand="DELETE FROM Products WHERE ProductID=@ProductID"
        />    
    
    <br /><br />
    
    <span class="tdText">
        The Super Form supports the ability of linking fields. Using this feature you can set up some of the fields<br />
        to depend on other fields. Thus these dependent fields will be enabled / disabled based on the state of the field they depend on.<br />
        For example some fields can be enabled (editable) only when a check box is checked, otherwise they will be disabled (non-editable).<br /><br />

        This example showcases the use of a <b>CheckBoxField</b> ("Discontinued") that controls three other fields. <br />
        When "Discontinued" is checked, "UnitPrice", "UnitsInStock" and "UnitsOnOrder" are disabled (non-editable). <br />
        These fields will become enabled (editable) when "Discontinued" is unchecked. <br /><br />

        Use the <b>FieldsToEnable</b> property of all the field classes to specify the fields that will be enabled when the state of the field is changed.<br /><br />

        Use the <b>FieldsToEnable</b> property of the <b>CheckBoxField</b> class to specify the fields that will be enabled when the CheckBox is checked.<br />
        Use the <b>FieldsToDisable</b> property of the <b>CheckBoxField</b> class to specify the fields that will be disabled when the CheckBox will be checked.<br />
    </span>
</asp:Content>

