<%@ Page Title="" Language="C#" MasterPageFile="~/SuperForm/SuperForm.master" AutoEventWireup="true" CodeFile="aspnet_validation_custom.aspx.cs" Inherits="SuperForm_aspnet_validation_custom" %>
<%@ Register TagPrefix="obout" Namespace="Obout.SuperForm" Assembly="obout_SuperForm" %>
<%@ Register TagPrefix="obout" Namespace="OboutInc.Calendar2" Assembly="obout_Calendar2_NET" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
    <style type="text/css">
        #ctl00_ContentPlaceHolder1_SuperForm1_RegularExpressionValidator1, #ctl00_ContentPlaceHolder1_SuperForm1_CustomValidator1
        {
            position: relative !important;
        }
    </style>
</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <br />
    
    <span class="tdText"><b>ASP.NET Super Form - Custom Validation</b></span>
    
    <br /><br />

    <obout:SuperForm ID="SuperForm1" 
        Title="Employee Form"
        DataSourceID="SqlDataSource1"
        AutoGenerateRows="false"
        AutoGenerateInsertButton ="true"
        AutoGenerateEditButton="true"
        AutoGenerateDeleteButton="true"
        DataKeyNames="EmployeeID"
        RunAt="server"
        AllowPaging="true"
        DefaultMode="Edit">
        <Fields>
            <obout:BoundField DataField="EmployeeID" HeaderText="Employee ID" ReadOnly="true" InsertVisible="false" />
            <obout:BoundField DataField="FirstName" HeaderText="First Name" Required="true" />
            <obout:BoundField DataField="LastName" HeaderText="Last Name" Required="true" />
            <obout:BoundField DataField="TitleOfCourtesy" HeaderText="Courtesy Title" Required="true">
                <Validators>
                    <asp:CustomValidator runat="server" OnServerValidate="ValidateTitle" Display="Dynamic" 
                        ErrorMessage="Title needs to be 'Mr.', 'Ms.', 'Mrs.' or 'Dr.'" ID="CustomValidator1" />
                </Validators>
            </obout:BoundField>
            <obout:DateField DataField="BirthDate" HeaderText="Birth Date" Required="true" DataFormatString="{0:MM/dd/yyyy}" ApplyFormatInEditMode="true">
                <Validators>
                    <asp:RangeValidator runat="server" MinimumValue="1900/1/1" MaximumValue = "2039/12/31" Type="Date" ErrorMessage="*" />
                </Validators>
            </obout:DateField>
            <obout:BoundField DataField="HomePhone" HeaderText="Home Phone" Required="true">
                <Validators>
                    <asp:RegularExpressionValidator runat="server" Display="Dynamic" ValidationExpression="^(\(?\s*\d{3}\s*[\)\-\.]?\s*)?[1-9]\d{2}\s*[\-\.]\s*\d{4}$" 
                        ErrorMessage="Phone numbers must have this format (###) ###-####" ID="RegularExpressionValidator1" />
                </Validators>
            </obout:BoundField>            
        </Fields>
    </obout:SuperForm>

    <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
        ConnectionString="<%$ ConnectionStrings:NorthwindConnectionString %>" 
        ProviderName="<%$ ConnectionStrings:NorthwindConnectionString.ProviderName %>" 
        SelectCommand="SELECT EmployeeID, FirstName, LastName, TitleOfCourtesy, BirthDate, HomePhone FROM [Employees] ORDER BY EmployeeID DESC"
        UpdateCommand="UPDATE Employees SET FirstName=@FirstName, LastName=@LastName, TitleOfCourtesy=@TitleOfCourtesy, BirthDate=@BirthDate, 
                        HomePhone=@HomePhone WHERE EmployeeID=@EmployeeID"
        InsertCommand="INSERT INTO Employees (FirstName, LastName, TitleOfCourtesy, BirthDate, HomePhone) 
                        VALUES (@FirstName, @LastName, @TitleOfCourtesy, @BirthDate, @HomePhone)"
        DeleteCommand="DELETE FROM Employees WHERE EmployeeID=@EmployeeID"
        />
    
    <br /><br />
    
    <span class="tdText">
        The Super Form allows developers to validate the data typed by the end users into the fields using various approaches.<br />
        You can add any number of validators to a field, by means of the <b>Validators</b> collection.<br /><br />

        This sample showcases the use of the <b>RegularExpressionValidator</b> control for validating phone numbers and <br />
        the use of the <b>CustomValidator</b> control for performing custom validation at run time - the 'Courtesy Title' field <br />
        is validated against a set of predetermined possible values.
    </span>
</asp:Content>

