<%@ Page Title="" Language="C#" MasterPageFile="~/SuperForm/SuperForm.master" AutoEventWireup="true" CodeFile="aspnet_layout_tabs.aspx.cs" Inherits="SuperForm_aspnet_layout_tabs" %>
<%@ Register TagPrefix="obout" Namespace="Obout.SuperForm" Assembly="obout_SuperForm" %>
<%@ Register Assembly="Obout.Ajax.UI" Namespace="Obout.Ajax.UI.HTMLEditor" TagPrefix="obout" %>
<%@ Register Assembly="Obout.Ajax.UI" Namespace="Obout.Ajax.UI.HTMLEditor.Popups" TagPrefix="obout" %>
<%@ Register TagPrefix="oem" Namespace="OboutInc.EasyMenu_Pro" Assembly="obout_EasyMenu_Pro" %>

<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <br />
    
    <span class="tdText"><b>ASP.NET Super Form - Field Sets with Tabs</b></span>
    
    <br /><br />
    
    <asp:ScriptManager runat="Server" EnablePartialRendering="true" ID="ScriptManager1" />
    
    <obout:SuperForm ID="SuperForm1" 
        Title="Employee Form"
        DataSourceID="SqlDataSource1"
        Width="480px"
        AutoGenerateRows="false"
        AutoGenerateInsertButton ="true"
        AutoGenerateEditButton="true"
        AutoGenerateDeletebutton="true"
        DataKeyNames="EmployeeID"
        RunAt="server"
        AllowPaging="true"
        DefaultMode="Edit"
        OnItemUpdating="SuperForm1_ItemUpdating"
        OnItemInserting="SuperForm1_ItemInserting">
        <Fields>
            <obout:BoundField DataField="EmployeeID" HeaderText="Employee ID" ReadOnly="true" InsertVisible="false" FieldSetID="FieldSet1" Visible="false" />
            <obout:BoundField DataField="FirstName" HeaderText="First Name:" FieldSetID="FieldSet1" />
            <obout:BoundField DataField="LastName" HeaderText="Last Name:" FieldSetID="FieldSet1" />
            <obout:TemplateField FieldSetID="FieldSet2">
                <ItemTemplate>
                    <div style="position: relative;">
                        <oem:EasyMenu SelectedItemId="Item_3_1" id="EasymenuTabStrip1" runat="server" ShowEvent="Always" StyleFolder="../EasyMenu/styles/TabStrip2"
						    Position="Horizontal" Width="430">
						    <Components>
							    <oem:MenuItem InnerHtml="<span style='cursor:default'>Personal Information</span>" OnClientClick="SelectTab(3, 1)" ID="Item_3_1"></oem:MenuItem>
                                <oem:MenuItem InnerHtml="<span style='cursor:default'>Contact Information</span>" OnClientClick="SelectTab(4, 1)" ID="Item_4_1"></oem:MenuItem>
							    <oem:MenuItem InnerHtml="<span style='cursor:default'>Notes</span>" OnClientClick="SelectTab(5, 1)" ID="Item_5_1"></oem:MenuItem>
						    </Components>
					    </oem:EasyMenu>
                        <div class="tabs-border">&#160;</div>
                    </div>
                </ItemTemplate>
                <EditItemTemplate>
                    <div style="position: relative;">
                        <oem:EasyMenu SelectedItemId="Item_3_2" id="EasymenuTabStrip2" runat="server" ShowEvent="Always" StyleFolder="../EasyMenu/styles/TabStrip2"
						    Position="Horizontal" Width="430">
						    <Components>
							    <oem:MenuItem InnerHtml="<span style='cursor:default'>Personal Information</span>" OnClientClick="SelectTab(3, 2)" ID="Item_3_2"></oem:MenuItem>
                                <oem:MenuItem InnerHtml="<span style='cursor:default'>Contact Information</span>" OnClientClick="SelectTab(4, 2)" ID="Item_4_2"></oem:MenuItem>
							    <oem:MenuItem InnerHtml="<span style='cursor:default'>Notes</span>" OnClientClick="SelectTab(5, 2)" ID="Item_5_2"></oem:MenuItem>
						    </Components>
					    </oem:EasyMenu>
                        <div class="tabs-border">&#160;</div>
                    </div>
                </EditItemTemplate>
            </obout:TemplateField>

            <obout:BoundField DataField="City" HeaderText="City:" FieldSetID="FieldSet3" />
            <obout:DateField DataField="BirthDate" HeaderText="Birth Date:" FieldSetID="FieldSet3" DataFormatString="{0:MM/dd/yyyy}" ApplyFormatInEditMode="true" />
            <obout:BoundField DataField="Address" HeaderText="Address:" FieldSetID="FieldSet3" />
            <obout:DateField DataField="HireDate" HeaderText="Hire Date:" FieldSetID="FieldSet3" DataFormatString="{0:MM/dd/yyyy}" ApplyFormatInEditMode="true" />
            <obout:BoundField DataField="Country" HeaderText="Country:" FieldSetID="FieldSet3" />
            <obout:BoundField DataField="Salary" HeaderText="Salary:" FieldSetID="FieldSet3" />

            <obout:BoundField DataField="HomePhone" HeaderText="Home Phone:" FieldSetID="FieldSet4" />
            <obout:DateField DataField="Extension" HeaderText="Extension:" FieldSetID="FieldSet4" />
            <obout:BoundField DataField="PostalCode" HeaderText="Postal Code:" FieldSetID="FieldSet4" />
            <obout:BoundField DataField="Region" HeaderText="Region:" FieldSetID="FieldSet4" />
            
            <obout:TemplateField HeaderText="Notes:" FieldSetID="FieldSet5">
                <ItemTemplate>
                    <%# Eval("Notes")%>
                </ItemTemplate>
                <EditItemTemplate>
                    <div id="EditorContainer">
                        <obout:Editor id="Editor1" runat="server" Width="450" Height="270" 
                            Content='<%# Eval("Notes") %>' >
                            <TopToolbar Appearance="lite" />
                        </obout:Editor>
                    </div>
                </EditItemTemplate>
            </obout:TemplateField>
        </Fields>
        <FieldSets>
            <obout:FieldSetRow>
                <obout:FieldSet ID="FieldSet1" Direction="Horizontal" CssClass="field-set" />                
            </obout:FieldSetRow>
            <obout:FieldSetRow>
                <obout:FieldSet ID="FieldSet2" Direction="Horizontal" CssClass="field-set" />
            </obout:FieldSetRow>            
            <obout:FieldSetRow>
                <obout:FieldSet ID="FieldSet3" Direction="Horizontal" CssClass="field-set field-set-visible" />
            </obout:FieldSetRow>
            <obout:FieldSetRow>
                <obout:FieldSet ID="FieldSet4" Direction="Horizontal" CssClass="field-set field-set-hidden" />
            </obout:FieldSetRow>
            <obout:FieldSetRow>
                <obout:FieldSet ID="FieldSet5" Direction="Horizontal" CssClass="field-set field-set-hidden-editor" />
            </obout:FieldSetRow>
        </FieldSets>
        <FieldHeaderStyle Width="200" />
    </obout:SuperForm>

    <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
        ConnectionString="<%$ ConnectionStrings:NorthwindConnectionString %>" 
        ProviderName="<%$ ConnectionStrings:NorthwindConnectionString.ProviderName %>" 
        SelectCommand="SELECT EmployeeID, LastName, FirstName, Title, TitleOfCourtesy, BirthDate, HireDate, 
                        Address, City, Region, PostalCode, Country, Notes,
                        HomePhone, Extension, Salary FROM [Employees] ORDER BY EmployeeID DESC"
        UpdateCommand="UPDATE Employees SET LastName=@LastName, FirstName=@FirstName, Title=@Title, TitleOfCourtesy=@TitleOfCourtesy, 
                        BirthDate=@BirthDate, HireDate=@HireDate, Address=@Address, City=@City, Region=@Region,
                        PostalCode=@PostalCode, Country=@Country, Notes=@Notes, HomePhone=@HomePhone, Extension=@Extension, Salary=@Salary
                         WHERE EmployeeID=@EmployeeID"
        InsertCommand="INSERT INTO Employees (LastName, FirstName, Title, TitleOfCourtesy, BirthDate, HireDate, Address, City, Region, PostalCode, Country, Notes, HomePhone, Extension, Salary) 
                        VALUES (@LastName, @FirstName, @Title, @TitleOfCourtesy, @BirthDate, @HireDate, @Address, @City, @Region, @PostalCode, @Country, @Notes, @HomePhone, @Extension, @Salary)"
        DeleteCommand="DELETE FROM Employees WHERE EmployeeID=@EmployeeID">
        <UpdateParameters>
            <asp:Parameter Name="LastName" DbType="String" />
            <asp:Parameter Name="FirstName" DbType="String" />
            <asp:Parameter Name="Title" DbType="String" />            
            <asp:Parameter Name="TitleOfCourtesy" DbType="String" />
            <asp:Parameter Name="BirthDate" DbType="DateTime" />
            <asp:Parameter Name="HireDate" DbType="DateTime" />
            <asp:Parameter Name="Address" DbType="String" />
            <asp:Parameter Name="City" DbType="String" />
            <asp:Parameter Name="Region" DbType="String" />
            <asp:Parameter Name="PostalCode" DbType="String" />
            <asp:Parameter Name="Country" DbType="String" />
            <asp:Parameter Name="Notes" DbType="String" />
            <asp:Parameter Name="HomePhone" DbType="String" />
            <asp:Parameter Name="Extension" DbType="String" />
            <asp:Parameter Name="Salary" DbType="Double" />
            <asp:Parameter Name="EmployeeID" DbType="Int32" />
        </UpdateParameters>
        <InsertParameters>
            <asp:Parameter Name="LastName" DbType="String" />
            <asp:Parameter Name="FirstName" DbType="String" />
            <asp:Parameter Name="Title" DbType="String" />            
            <asp:Parameter Name="TitleOfCourtesy" DbType="String" />
            <asp:Parameter Name="BirthDate" DbType="DateTime" />
            <asp:Parameter Name="HireDate" DbType="DateTime" />
            <asp:Parameter Name="Address" DbType="String" />
            <asp:Parameter Name="City" DbType="String" />
            <asp:Parameter Name="Region" DbType="String" />
            <asp:Parameter Name="PostalCode" DbType="String" />
            <asp:Parameter Name="Country" DbType="String" />
            <asp:Parameter Name="Notes" DbType="String" />
            <asp:Parameter Name="HomePhone" DbType="String" />
            <asp:Parameter Name="Extension" DbType="String" />
            <asp:Parameter Name="Salary" DbType="Double" />
        </InsertParameters>
    </asp:SqlDataSource>

    <asp:SqlDataSource ID="SqlDataSource2" runat="server" 
        ConnectionString="<%$ ConnectionStrings:NorthwindConnectionString %>" 
        ProviderName="<%$ ConnectionStrings:NorthwindConnectionString.ProviderName %>" 
        SelectCommand="SELECT DISTINCT ShipCountry FROM [Orders] ORDER BY ShipCountry ASC" />
    
    <br /><br />
    
    <span class="tdText">
        The fields of the Super Form can be grouped in field sets. Use the <b>FieldSets</b> collection to define field sets for the form.<br />
        The field sets are grouped in field set rows, which allow developers to organize the field sets in a tabular structure.<br />
        To designate a field as member of a field set, use the <b>FieldSetID</b> property of the field.<br /><br />
        By combining template fields with field sets you can achieve highly complex form layouts.<br />
        This example showcases the use of tabs inside the form, that allow users to switch between tab panels that contain different field sets.<br />
        Using this approach you can fit a large form structure in less space on your web page.
    </span>
</asp:Content>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
    <style type="text/css">
        .ob_fRwF span
        {
            position: static !important;            
        }
        
        td.field-set
        {
            padding-left: 0px !important;
            padding-right:0px !important;
            padding-bottom: 0px !important;
            padding-top: 0px !important;
        }
        
        td.field-set .ob_fRwH, td.field-set .ob_fRwF
        {
            padding-bottom: 0px !important;
            padding-top: 0px !important;
        }
        
        .field-set-visible
        {
            display: block;
        }
        
        .field-set-hidden
        {
            display: none;
        }
        
        .field-set-hidden-editor
        {
            visibility: hidden;
        }
        
        .field-set-hidden-editor #EditorContainer
        {
            position: absolute;
            width: 1px;
            height: 1px;
            overflow: hidden;
        }
        
        .tabs-border
        {
            height: 2px;
            width: 100%;
            background-image: url(styles/black_glass/images/separator.png);
            top: 38px;
            position: absolute;
        }
    </style>

    <script type="text/javascript">
        var lastVisibleFieldSetIndex = 3;

        function SelectTab(fieldSetIndex, typeIndex) {
            ob_em_SelectItem('Item_' + fieldSetIndex + '_' + typeIndex);
            var container = document.getElementById('__dvctl00_ContentPlaceHolder1_SuperForm1__div').firstChild;
            while (container.className != 'ob_fC') {
                container = container.nextSibling;
            }

            container = container.firstChild;
            while (container.nodeName != 'TABLE') {
                container = container.nextSibling;
            }

            container = container.firstChild;
            while (container.nodeName != 'TBODY') {
                container = container.nextSibling;
            }

            var increment = 1;

            if (container.firstChild.nodeName != 'TR') {
                increment++;
            }

            var previousFieldSet = container.childNodes[lastVisibleFieldSetIndex - increment].firstChild
            while (previousFieldSet.nodeName != 'TD') {
                previousFieldSet = previousFieldSet.nextSibling;
            }
            previousFieldSet.className = previousFieldSet.className.replace('field-set-visible', 'field-set-hidden');

            var fieldSet = container.childNodes[fieldSetIndex - increment].firstChild;
            while (fieldSet.nodeName != 'TD') {
                fieldSet = fieldSet.nextSibling;
            }
            fieldSet.className = fieldSet.className.replace('field-set-hidden', 'field-set-visible');

            lastVisibleFieldSetIndex = fieldSetIndex;
        }
	</script>
</asp:Content>

