<%@ Page Title="" Language="C#" MasterPageFile="~/SuperForm/SuperForm.master" AutoEventWireup="true" CodeFile="aspnet_templates_combobox_cascading.aspx.cs" Inherits="SuperForm_aspnet_templates_combobox_cascading" %>
<%@ Register TagPrefix="obout" Namespace="Obout.SuperForm" Assembly="obout_SuperForm" %>
<%@ Register TagPrefix="obout" Namespace="Obout.ComboBox" Assembly="obout_ComboBox" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">

</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <br />
    
    <span class="tdText"><b>ASP.NET Super Form - Cascading ComboBox Field</b></span>
    
    <br /><br />
    
    <obout:SuperForm ID="SuperForm1" 
        DataSourceID="SqlDataSource1"
        AutoGenerateRows="false"
        AutoGenerateInsertButton ="true"
        AutoGenerateEditButton="true"
        AutoGenerateDeleteButton="true"
        AutoGenerateDateFields="true"
        DataKeyNames="OrderID"
        RunAt="server"
        AllowPaging="true"
        OnItemUpdating="SuperForm1_ItemUpdating"
        OnItemInserting="SuperForm1_ItemInserting"
        OnDataBound="SuperForm1_DataBound"
        DefaultMode="Edit">
        <Fields>
            <obout:BoundField DataField="OrderID" HeaderText="Order ID" ReadOnly="true" InsertVisible="false" />
            <obout:BoundField DataField="ShipName" HeaderText="Ship Name" />
            <obout:TemplateField HeaderText="Ship Country">
                <ItemTemplate>
                    <%# Eval("ShipCountry") %>
                </ItemTemplate>
                <EditItemTemplate>
                    <obout:ComboBox runat="server" ID="ShipCountry" DataSourceID="SqlDataSource2" Height="150" Width="100%"
                        OnSelectedIndexChanged="ShipCountry_SelectedIndexChanged" AutoPostBack="true"
                        DataValueField="ShipCountry" DataTextField="ShipCountry" SelectedValue='<%# Eval("ShipCountry") %>' />
                </EditItemTemplate>
            </obout:TemplateField>
            <obout:TemplateField HeaderText="Ship City">
                <ItemTemplate>
                    <%# Eval("ShipCity") %>
                </ItemTemplate>
                <EditItemTemplate>
                    <obout:ComboBox runat="server" ID="ShipCity" DataSourceID="SqlDataSource3" Height="150" Width="100%"
                        DataValueField="ShipCity" DataTextField="ShipCity" AppendDataBoundItems="false" />
                </EditItemTemplate>
            </obout:TemplateField>
        </Fields>
    </obout:SuperForm>


    <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
        ConnectionString="<%$ ConnectionStrings:NorthwindConnectionString %>" 
        ProviderName="<%$ ConnectionStrings:NorthwindConnectionString.ProviderName %>" 
        SelectCommand="SELECT OrderID, ShipName, ShipCity, ShipCountry
                       FROM [Orders] ORDER BY OrderID DESC"
        UpdateCommand="UPDATE Orders SET ShipName=@ShipName, ShipCity=@ShipCity, ShipCountry=@ShipCountry
                       WHERE OrderID=@OrderID"
        InsertCommand="INSERT INTO Orders (ShipName, ShipCity, ShipCountry)
                        VALUES(@ShipName, @ShipCity, @ShipCountry)"
        DeleteCommand="DELETE FROM Orders WHERE OrderID = @OrderID">
        <UpdateParameters>
            <asp:Parameter Name="ShipName" DbType="String" />
            <asp:Parameter Name="ShipCity" DbType="String" />
            <asp:Parameter Name="ShipCountry" DbType="String" />
            <asp:Parameter Name="OrderID" DbType="Int32" />
        </UpdateParameters>
        <InsertParameters>
            <asp:Parameter Name="ShipName" DbType="String" />
            <asp:Parameter Name="ShipCity" DbType="String" />
            <asp:Parameter Name="ShipCountry" DbType="String" />
        </InsertParameters>
    </asp:SqlDataSource>

    <asp:SqlDataSource ID="SqlDataSource2" runat="server" 
        ConnectionString="<%$ ConnectionStrings:NorthwindConnectionString %>" 
        ProviderName="<%$ ConnectionStrings:NorthwindConnectionString.ProviderName %>"
        SelectCommand="SELECT DISTINCT ShipCountry FROM Orders ORDER BY ShipCountry ASC" />

    <asp:SqlDataSource ID="SqlDataSource3" runat="server" 
        ConnectionString="<%$ ConnectionStrings:NorthwindConnectionString %>" 
        ProviderName="<%$ ConnectionStrings:NorthwindConnectionString.ProviderName %>"
        SelectCommand="SELECT DISTINCT ShipCity FROM Orders WHERE ShipCountry LIKE @ShipCountry ORDER BY ShipCity ASC">
        <SelectParameters>
            <asp:Parameter Name="ShipCountry" DbType="String" DefaultValue="" />
        </SelectParameters>    
    </asp:SqlDataSource>
    
    <br /><br />
    
    <span class="tdText">
        Use the <b>TemplateField</b> class to gain full control over the layout of the field.<br /> 
        A TemplateField allows developers to specify different templates for view / add / edit modes.<br /><br />

        This example showcases the use of two TemplateField objects - one for the "Ship Country" field and one for the "Ship City" field.<br />
        Using the TemplateField class we can use ComboBox controls to edit the data from these fields.<br />
        The two ComboBoxes are linked in cascade - when the selection changes in the "Ship Country" ComboBox, <br />
        the "Ship City" ComboBox is populated with the cities located in the selected country.
    </span>
</asp:Content>

