using System;
using System.Collections.Generic;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using Obout.SuperForm;

public partial class SuperForm_cs_commands_autogenerate : System.Web.UI.Page
{
    private SuperForm SuperForm1;
    protected void Page_Load(object sender, EventArgs e)
    {
        SuperForm1 = new SuperForm();
        SuperForm1.ID = "SuperForm1"; 
        SuperForm1.DataSourceID = "SqlDataSource1";
        SuperForm1.AutoGenerateRows = true;        
        SuperForm1.AutoGenerateDateFields = true;
        SuperForm1.DataKeyNames = new string[] { "OrderID" };
        SuperForm1.AllowPaging = true;

        if (!IsPostBack)
        {
            SuperForm1.AutoGenerateInsertButton = true;
            SuperForm1.AutoGenerateEditButton = true;
            SuperForm1.AutoGenerateDeleteButton = true;
        }

        SuperForm1Container.Controls.Add(SuperForm1);        
    }

    protected void CheckBox_CheckedChanged(object sender, EventArgs e)
    {
        SuperForm1.AutoGenerateEditButton = GenerateEditButton.Checked;
        SuperForm1.AutoGenerateDeleteButton = GenerateDeleteButton.Checked;
        SuperForm1.AutoGenerateInsertButton = GenerateInsertButton.Checked;

        SuperForm1Container.DataBind();
    }
}
