using System;
using System.Collections.Generic;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using Obout.SuperForm;

public partial class SuperForm_cs_commands_editonly : System.Web.UI.Page
{
    private SuperForm SuperForm1;
    protected void Page_Load(object sender, EventArgs e)
    {
        SuperForm1 = new SuperForm();
        SuperForm1.ID = "SuperForm1"; 
        SuperForm1.DataSourceID = "SqlDataSource1";
        SuperForm1.Title = "Order Details";
        SuperForm1.AutoGenerateInsertButton = true;
        SuperForm1.AutoGenerateEditButton = true;
        SuperForm1.AutoGenerateDeleteButton = true;
        SuperForm1.DataKeyNames = new string[] { "Order ID" };
        SuperForm1.AllowPaging = true;
        SuperForm1.AllowDataKeysInsert = false;
        SuperForm1.DefaultMode = DetailsViewMode.Edit;
        SuperForm1.ModeChanging += SuperForm1_ModeChaning;


        SuperForm1Container.Controls.Add(SuperForm1);

    }
    protected void SuperForm1_ModeChaning(object sender, DetailsViewModeEventArgs e)
    {
        if (e.NewMode == DetailsViewMode.ReadOnly)
        {
            SuperForm1.DataBind();
        }
        e.Cancel = true;
    }

}
