using System;
using System.Collections.Generic;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using Obout.SuperForm;

public partial class SuperForm_cs_commands_customize : System.Web.UI.Page
{
    private SuperForm SuperForm1;
    protected void Page_Load(object sender, EventArgs e)
    {
        SuperForm1 = new SuperForm();
        SuperForm1.ID = "SuperForm1"; 
        SuperForm1.DataSourceID = "SqlDataSource1";
        SuperForm1.AutoGenerateRows = true;
        SuperForm1.AutoGenerateDateFields = true;
        SuperForm1.DataKeyNames = new string[] { "OrderID" };
        SuperForm1.AllowPaging = true;
        SuperForm1.DefaultMode = DetailsViewMode.Edit;
        
        Obout.SuperForm.CommandField field1 = new Obout.SuperForm.CommandField();
       

        if (ButtonType1.Checked)
        {
            field1.ButtonType = ButtonType.Button;
        }
        else if (ButtonType2.Checked)
        {
            field1.ButtonType = ButtonType.Image;
            field1.EditImageUrl = "resources/icons/Edit.png";
            field1.DeleteImageUrl = "resources/icons/Delete.png";
            field1.NewImageUrl = "resources/icons/Add.png";
            field1.InsertImageUrl = "resources/icons/Save.png";
            field1.UpdateImageUrl = "resources/icons/Save.png";
            field1.CancelImageUrl = "resources/icons/Delete.png";
        }
        else
        {
            field1.ButtonType = ButtonType.Link;
        }

        field1.ShowCancelButton = ShowCancelButton.Checked;
        field1.ShowDeleteButton = ShowDeleteButton.Checked;
        field1.ShowEditButton = ShowEditButton.Checked;
        field1.ShowInsertButton = ShowInsertButton.Checked;
        SuperForm1.Fields.Add(field1);
        SuperForm1Container.Controls.Add(SuperForm1);
    }
}
