using System;
using System.Collections.Generic;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using Obout.SuperForm;

public partial class SuperForm_cs_commands_sp : System.Web.UI.Page
{
    private SuperForm SuperForm1;
    protected void Page_Load(object sender, EventArgs e)
    {
        SuperForm1 = new SuperForm();
        SuperForm1.ID = "SuperForm1";
        SuperForm1.Title = "Customer Details";
        SuperForm1.DataSourceID = "sds1";
        SuperForm1.AutoGenerateRows = false;
        SuperForm1.DataKeyNames = new string[] { "CustomerID" };
        SuperForm1.AllowPaging = true;
        SuperForm1.DefaultMode = DetailsViewMode.Edit;
        SuperForm1.AutoGenerateInsertButton = true;
        SuperForm1.AutoGenerateEditButton = true;
        SuperForm1.AutoGenerateDeleteButton = true;
        SuperForm1.AllowDataKeysInsert = true;

        Obout.SuperForm.BoundField field11 = new Obout.SuperForm.BoundField();
        field11.DataField = "CustomerID";
        field11.HeaderText = "Customer ID";
        field11.ReadOnly = true;

        Obout.SuperForm.BoundField field12 = new Obout.SuperForm.BoundField();
        field12.DataField = "CompanyName";
        field12.HeaderText = "Company Name";

        Obout.SuperForm.BoundField field13 = new Obout.SuperForm.BoundField();
        field13.DataField = "ContactName";
        field13.HeaderText = "Contact Name";

        Obout.SuperForm.BoundField field14 = new Obout.SuperForm.BoundField();
        field14.DataField = "Country";
        field14.HeaderText = "Country";
       
        SuperForm1.Fields.Add(field11);
        SuperForm1.Fields.Add(field12);
        SuperForm1.Fields.Add(field13);
        SuperForm1.Fields.Add(field14);

        SuperForm1Container.Controls.Add(SuperForm1);

    }
}
