<%@ Page Title="" Language="C#" MasterPageFile="~/SuperForm/SuperForm.master" AutoEventWireup="true" CodeFile="cs_commands_autogenerate.aspx.cs" Inherits="SuperForm_cs_commands_autogenerate" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
<br />
    
    <span class="tdText"><b>ASP.NET Super Form - Auto Generate Command Buttons</b></span>
    
    <br /><br />
    
    <obout:OboutCheckBox runat="server" ID="GenerateEditButton" Text="Auto Generate Edit Button" AutoPostBack="true" Checked="true" OnCheckedChanged="CheckBox_CheckedChanged" /> <br />
    <obout:OboutCheckBox runat="server" ID="GenerateDeleteButton" Text="Auto Generate Delete Button" AutoPostBack="true" Checked="true" OnCheckedChanged="CheckBox_CheckedChanged" /> <br />
    <obout:OboutCheckBox runat="server" ID="GenerateInsertButton" Text="Auto Generate Insert Button" AutoPostBack="true" Checked="true" OnCheckedChanged="CheckBox_CheckedChanged" />

    <br /><br />
    <asp:PlaceHolder runat="server" ID="SuperForm1Container" />

    <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
        ConnectionString="<%$ ConnectionStrings:NorthwindConnectionString %>" 
        ProviderName="<%$ ConnectionStrings:NorthwindConnectionString.ProviderName %>" 
        SelectCommand="SELECT OrderID, ShipName, ShipCity, ShipRegion, ShipCountry, ShipPostalCode, 
                        OrderDate, ShippedDate, RequiredDate, Sent FROM [Orders] ORDER BY OrderID DESC"
        UpdateCommand="UPDATE Orders SET ShipName=@ShipName, ShipCity=@ShipCity, ShipRegion=@ShipRegion, ShipCountry=@ShipCountry, 
                       ShipPostalCode=@ShipPostalCode, OrderDate=@OrderDate, ShippedDate=@ShippedDate, RequiredDate=@RequiredDate, Sent=@Sent
                       WHERE OrderID=@OrderID"
        InsertCommand="INSERT INTO Orders (ShipName, ShipCity, ShipRegion, ShipCountry, ShipPostalCode, OrderDate, ShippedDate, RequiredDate, Sent)
                        VALUES(@ShipName, @ShipCity, @ShipRegion, @ShipCountry, @ShipPostalCode, @OrderDate, @ShippedDate, @RequiredDate, @Sent)"
        DeleteCommand="DELETE FROM Orders WHERE OrderID = @OrderID">
    </asp:SqlDataSource>
    
    <br /><br />
    
    <span class="tdText">
        The Super Form can generate its command buttons automatically. To make the form auto generate the command buttons, <br />
        use a combination of the following properties:<br />

        <ul>
            <li><b>AutoGenerateEditButton</b> - gets or sets a value indicating whether the built-in controls to edit the current record are displayed in the form.</li>
            <li><b>AutoGenerateDeleteButton</b> - gets or sets a value indicating whether the built-in controls to delete the current record are displayed in the form.</li>
            <li><b>AutoGenerateInsertButton</b> - gets or sets a value indicating whether the built-in controls to insert a new record are displayed in the form.</li>
        </ul>
    </span>
</asp:Content>


