using System;
using System.Collections.Generic;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using Obout.SuperForm;

public partial class SuperForm_cs_fields_dropdownlistfield : System.Web.UI.Page
{
    private SuperForm SuperForm1;
    protected void Page_Load(object sender, EventArgs e)
    {
        SuperForm1 = new SuperForm();
        SuperForm1.ID = "SuperForm1";
        SuperForm1.Title = "Order Details";
        SuperForm1.DataSourceID = "SqlDataSource1";
        SuperForm1.AutoGenerateRows = false;
        SuperForm1.AutoGenerateInsertButton = true;
        SuperForm1.AutoGenerateEditButton = true;
        SuperForm1.AutoGenerateDeleteButton = true;
        SuperForm1.DataKeyNames = new string[] { "OrderID" };
        SuperForm1.AllowPaging = true;
        SuperForm1.DefaultMode = DetailsViewMode.Edit;

        Obout.SuperForm.BoundField field11 = new Obout.SuperForm.BoundField();
        field11.DataField = "OrderID";
        field11.HeaderText = "Order ID";
        field11.ReadOnly = true;
        field11.InsertVisible = false;

        Obout.SuperForm.DropDownListField field12 = new Obout.SuperForm.DropDownListField();
        field12.DataField = "CustomerID";
        field12.DisplayField = "CompanyName";
        field12.HeaderText = "Customer";
        field12.DataSourceID = "SqlDataSource3";

        Obout.SuperForm.DropDownListField field13 = new Obout.SuperForm.DropDownListField();
        field13.DataField = "ShipCountry";
        field13.DisplayField = "ShipCountry";
        field13.HeaderText = "Country";
        field13.DataSourceID = "SqlDataSource2";

        SuperForm1.Fields.Add(field11);
        SuperForm1.Fields.Add(field12);
        SuperForm1.Fields.Add(field13);

        SuperForm1Container.Controls.Add(SuperForm1);
 
    }
}
