using System;
using System.Collections.Generic;
using Obout.SuperForm;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using OboutInc.EasyMenu_Pro;

public partial class SuperForm_cs_layout_tabs : System.Web.UI.Page
{
    private SuperForm SuperForm1;
    protected void Page_Load(object sender, EventArgs e)
    {
        SuperForm1 = new SuperForm();
        SuperForm1.ID = "SuperForm1";
        SuperForm1.Title = "Employee Form";
        SuperForm1.DataSourceID = "SqlDataSource1";
        SuperForm1.AutoGenerateRows = false;
        SuperForm1.AutoGenerateInsertButton = true;
        SuperForm1.AutoGenerateEditButton = true;
        SuperForm1.AutoGenerateDeleteButton = true;
        SuperForm1.Width = Unit.Pixel(480);
        SuperForm1.DataKeyNames = new string[] { "EmployeeID" };
        SuperForm1.AllowPaging = true;
        SuperForm1.DefaultMode = DetailsViewMode.Edit;

        SuperForm1.ItemUpdating += SuperForm1_ItemUpdating;
        SuperForm1.ItemInserting += SuperForm1_ItemInserting;

        Obout.SuperForm.BoundField field1 = new Obout.SuperForm.BoundField();
        field1.DataField = "EmployeeID";
        field1.HeaderText = "Employee ID:";
        field1.ReadOnly = true;
        field1.InsertVisible = false;
        field1.Visible= false;
        field1.FieldSetID = "FieldSet1";

        Obout.SuperForm.BoundField field2 = new Obout.SuperForm.BoundField();
        field2.DataField = "FirstName";
        field2.HeaderText = "First Name:";
        field2.FieldSetID = "FieldSet1";

        Obout.SuperForm.BoundField field3 = new Obout.SuperForm.BoundField();
        field3.DataField = "LastName";
        field3.HeaderText = "Last Name:";
        field3.FieldSetID = "FieldSet1";

        Obout.SuperForm.TemplateField field4 = new Obout.SuperForm.TemplateField();
        field4.FieldSetID = "FieldSet2";
        field4.ItemTemplate = new TabStripItemTemplate();
        field4.EditItemTemplate = new TabStripEditItemTemplate();

        Obout.SuperForm.BoundField field5 = new Obout.SuperForm.BoundField();
        field5.DataField = "City";
        field5.HeaderText = "City:";
        field5.FieldSetID = "FieldSet3";

        Obout.SuperForm.DateField field6 = new Obout.SuperForm.DateField();
        field6.DataField = "BirthDate";
        field6.HeaderText = "Birth Date:";
        field6.FieldSetID = "FieldSet3";
        field6.DataFormatString = "{0:MM/dd/yyyy}";
        field6.ApplyFormatInEditMode = true;

        Obout.SuperForm.BoundField field7 = new Obout.SuperForm.BoundField();
        field7.DataField = "Address";
        field7.HeaderText = "Address:";
        field7.FieldSetID = "FieldSet3";

        Obout.SuperForm.DateField field8 = new Obout.SuperForm.DateField();
        field8.DataField = "HireDate";
        field8.HeaderText = "Hire Date:";
        field8.FieldSetID = "FieldSet3";
        field8.DataFormatString = "{0:MM/dd/yyyy}";
        field8.ApplyFormatInEditMode = true;

        Obout.SuperForm.BoundField field9 = new Obout.SuperForm.BoundField();
        field9.DataField = "Country";
        field9.HeaderText = "Country:";
        field9.FieldSetID = "FieldSet3";

        Obout.SuperForm.BoundField field10 = new Obout.SuperForm.BoundField();
        field10.DataField = "Salary";
        field10.HeaderText = "Salary:";
        field10.FieldSetID = "FieldSet3";

        Obout.SuperForm.BoundField field11 = new Obout.SuperForm.BoundField();
        field11.DataField = "HomePhone";
        field11.HeaderText = "HomePhone:";
        field11.FieldSetID = "FieldSet4";

        Obout.SuperForm.BoundField field12 = new Obout.SuperForm.BoundField();
        field12.DataField = "Extension";
        field12.HeaderText = "Extension:";
        field12.FieldSetID = "FieldSet4";

        Obout.SuperForm.BoundField field13 = new Obout.SuperForm.BoundField();
        field13.DataField = "PostalCode";
        field13.HeaderText = "PostalCode:";
        field13.FieldSetID = "FieldSet4";

        Obout.SuperForm.BoundField field14 = new Obout.SuperForm.BoundField();
        field14.DataField = "Region";
        field14.HeaderText = "Region:";
        field14.FieldSetID = "FieldSet4";

        Obout.SuperForm.TemplateField field15 = new Obout.SuperForm.TemplateField();
        field15.FieldSetID = "FieldSet5";
        field15.HeaderText = "Notes:";
        field15.ItemTemplate = new EditorItemTemplate();
        field15.EditItemTemplate = new EditorEditItemTemplate();

        Obout.SuperForm.FieldSetRow fieldSetRow1 = new Obout.SuperForm.FieldSetRow();
        Obout.SuperForm.FieldSet fieldSet1 = new Obout.SuperForm.FieldSet();
        fieldSet1.ID = "FieldSet1";
        fieldSet1.Direction = Direction.Horizontal;
        fieldSet1.CssClass = "field-set";
        fieldSetRow1.Items.Add(fieldSet1);

        Obout.SuperForm.FieldSetRow fieldSetRow2 = new Obout.SuperForm.FieldSetRow();
        Obout.SuperForm.FieldSet fieldSet2 = new Obout.SuperForm.FieldSet();
        fieldSet2.ID = "FieldSet2";
        fieldSet2.Direction = Direction.Horizontal;
        fieldSet2.CssClass = "field-set";
        fieldSetRow2.Items.Add(fieldSet2);

        Obout.SuperForm.FieldSetRow fieldSetRow3 = new Obout.SuperForm.FieldSetRow();
        Obout.SuperForm.FieldSet fieldSet3 = new Obout.SuperForm.FieldSet();
        fieldSet3.ID = "FieldSet3";
        fieldSet3.Direction = Direction.Horizontal;
        fieldSet3.CssClass = "field-set field-set-visible";
        fieldSetRow3.Items.Add(fieldSet3);

        Obout.SuperForm.FieldSetRow fieldSetRow4 = new Obout.SuperForm.FieldSetRow();
        Obout.SuperForm.FieldSet fieldSet4 = new Obout.SuperForm.FieldSet();
        fieldSet4.ID = "FieldSet4";
        fieldSet4.Direction = Direction.Horizontal;
        fieldSet4.CssClass = "field-set field-set-hidden";
        fieldSetRow4.Items.Add(fieldSet4);

        Obout.SuperForm.FieldSetRow fieldSetRow5 = new Obout.SuperForm.FieldSetRow();
        Obout.SuperForm.FieldSet fieldSet5 = new Obout.SuperForm.FieldSet();
        fieldSet5.ID = "FieldSet5";
        fieldSet5.Direction = Direction.Horizontal;
        fieldSet5.CssClass = "field-set field-set-hidden-editor";
        fieldSetRow5.Items.Add(fieldSet5);

        SuperForm1.FieldSets.Add(fieldSetRow1);
        SuperForm1.FieldSets.Add(fieldSetRow2);
        SuperForm1.FieldSets.Add(fieldSetRow3);
        SuperForm1.FieldSets.Add(fieldSetRow4);
        SuperForm1.FieldSets.Add(fieldSetRow5);

        SuperForm1.Fields.Add(field1);
        SuperForm1.Fields.Add(field2);
        SuperForm1.Fields.Add(field3);
        SuperForm1.Fields.Add(field4);
        SuperForm1.Fields.Add(field5);
        SuperForm1.Fields.Add(field6);
        SuperForm1.Fields.Add(field7);
        SuperForm1.Fields.Add(field8);
        SuperForm1.Fields.Add(field9);
        SuperForm1.Fields.Add(field10);
        SuperForm1.Fields.Add(field11);
        SuperForm1.Fields.Add(field12);
        SuperForm1.Fields.Add(field13);
        SuperForm1.Fields.Add(field14);
        SuperForm1.Fields.Add(field15);
        SuperForm1.FieldHeaderStyle.Width = Unit.Pixel(200);
        SuperForm1Container.Controls.Add(SuperForm1);
    }

    protected void SuperForm1_ItemUpdating(object sender, DetailsViewUpdateEventArgs e)
    {
        e.NewValues["Notes"] = ((Obout.Ajax.UI.HTMLEditor.Editor)((DetailsViewRow)SuperForm1.Rows[14]).FindControl("Editor1")).Content;
    }

    protected void SuperForm1_ItemInserting(object sender, DetailsViewInsertEventArgs e)
    {
        e.Values["Notes"] = ((Obout.Ajax.UI.HTMLEditor.Editor)((DetailsViewRow)SuperForm1.Rows[14]).FindControl("Editor1")).Content;
    }

    public class TabStripItemTemplate : ITemplate
    {
        public void InstantiateIn(Control container)
        {
            PlaceHolder templatePlaceHolder = new PlaceHolder();
            container.Controls.Add(templatePlaceHolder);

            Literal div1 = new Literal();
            div1.Text = "<div style=\"position: relative;\">";

            EasyMenu tabStrip = new EasyMenu();
            tabStrip.SelectedItemId = "Item_3_1";
            tabStrip.ID = "EasymenuTabStrip1"; 
            tabStrip.ShowEvent = MenuShowEvent.Always;
            tabStrip.StyleFolder = "../EasyMenu/styles/TabStrip2";
			tabStrip.Position = MenuPosition.Horizontal;
            tabStrip.Width = "430";

            OboutInc.EasyMenu_Pro.MenuItem item1 = new OboutInc.EasyMenu_Pro.MenuItem();
            item1.InnerHtml = "<span style='cursor:default'>Personal Information</span>";
            item1.OnClientClick = "SelectTab(3, 1)";
            item1.ID = "Item_3_1";

            OboutInc.EasyMenu_Pro.MenuItem item2 = new OboutInc.EasyMenu_Pro.MenuItem();
            item2.InnerHtml = "<span style='cursor:default'>Contact Information</span>";
            item2.OnClientClick = "SelectTab(4, 1)";
            item2.ID = "Item_4_1";

            OboutInc.EasyMenu_Pro.MenuItem item3 = new OboutInc.EasyMenu_Pro.MenuItem();
            item3.InnerHtml = "<span style='cursor:default'>Notes</span>";
            item3.OnClientClick = "SelectTab(5, 1)";
            item3.ID = "Item_5_1";

            tabStrip.Components.Add(item1);
            tabStrip.Components.Add(item2);
            tabStrip.Components.Add(item3);
            
            Literal div2 = new Literal();
            div2.Text = "<div class=\"tabs-border\">&#160;</div>";

            Literal enddiv1 = new Literal();
            enddiv1.Text = "</div>";

            templatePlaceHolder.Controls.Add(div1);
            templatePlaceHolder.Controls.Add(tabStrip);
            templatePlaceHolder.Controls.Add(div2);
            templatePlaceHolder.Controls.Add(enddiv1);    
        }  
    }


    public class TabStripEditItemTemplate : ITemplate
    {

        public void InstantiateIn(Control container)
        {
            PlaceHolder templatePlaceHolder = new PlaceHolder();
            container.Controls.Add(templatePlaceHolder);

            Literal div1 = new Literal();
            div1.Text = "<div style=\"position: relative;\">";

            EasyMenu tabStrip = new EasyMenu();
            tabStrip.SelectedItemId = "Item_3_2";
            tabStrip.ID = "EasymenuTabStrip2";
            tabStrip.ShowEvent = MenuShowEvent.Always;
            tabStrip.StyleFolder = "../EasyMenu/styles/TabStrip2";
            tabStrip.Position = MenuPosition.Horizontal;
            tabStrip.Width = "430";

            OboutInc.EasyMenu_Pro.MenuItem item1 = new OboutInc.EasyMenu_Pro.MenuItem();
            item1.InnerHtml = "<span style='cursor:default'>Personal Information</span>";
            item1.OnClientClick = "SelectTab(3, 2)";
            item1.ID = "Item_3_2";

            OboutInc.EasyMenu_Pro.MenuItem item2 = new OboutInc.EasyMenu_Pro.MenuItem();
            item2.InnerHtml = "<span style='cursor:default'>Contact Information</span>";
            item2.OnClientClick = "SelectTab(4, 2)";
            item2.ID = "Item_4_2";

            OboutInc.EasyMenu_Pro.MenuItem item3 = new OboutInc.EasyMenu_Pro.MenuItem();
            item3.InnerHtml = "<span style='cursor:default'>Notes</span>";
            item3.OnClientClick = "SelectTab(5, 3)";
            item3.ID = "Item_5_3";

            tabStrip.Components.Add(item1);
            tabStrip.Components.Add(item2);
            tabStrip.Components.Add(item3);

            Literal div2 = new Literal();
            div2.Text = "<div class=\"tabs-border\">&#160;</div>";

            Literal enddiv1 = new Literal();
            enddiv1.Text = "</div>";

            templatePlaceHolder.Controls.Add(div1);
            templatePlaceHolder.Controls.Add(tabStrip);
            templatePlaceHolder.Controls.Add(div2);
            templatePlaceHolder.Controls.Add(enddiv1);    
        } 
    }
    public class EditorItemTemplate : ITemplate
    {

        public void InstantiateIn(Control container)
        {
            Literal templatePlaceHolder = new Literal();
            container.Controls.Add(templatePlaceHolder);

            templatePlaceHolder.DataBinding += new EventHandler(DataBindTemplate);
        }

        public void DataBindTemplate(object sender, EventArgs e)
        {
            Literal templatePlaceHolder = sender as Literal;
            DetailsViewRow row = templatePlaceHolder.Parent.Parent as DetailsViewRow;
            SuperForm form = row.Parent.Parent as SuperForm;

            templatePlaceHolder.Text = DataBinder.Eval(form.DataItem, "Notes").ToString();
        }
    }
    public class EditorEditItemTemplate : ITemplate
    {

        public void InstantiateIn(Control container)
        {
            PlaceHolder templatePlaceHolder = new PlaceHolder();
            container.Controls.Add(templatePlaceHolder);

            Literal div = new Literal();
            div.Text = "<div id=\"EditorContainer\">";

            Obout.Ajax.UI.HTMLEditor.Editor editor1 = new Obout.Ajax.UI.HTMLEditor.Editor();

            templatePlaceHolder.Controls.Add(div);
            templatePlaceHolder.Controls.Add(editor1);

            editor1.ID = "Editor1";
            editor1.TopToolbar.Appearance = Obout.Ajax.UI.HTMLEditor.EditorTopToolbar.AppearanceType.Lite;
            editor1.Width = 450;
            editor1.Height = 270;

            Literal enddiv = new Literal();
            enddiv.Text = "</div>";

            templatePlaceHolder.Controls.Add(enddiv);
        }
    }
}
