using System;
using System.Collections.Generic;
using OboutInc.Calendar2;
using Obout.SuperForm;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;

public partial class SuperForm_cs_localization_date_field : System.Web.UI.Page
{
    private SuperForm SuperForm1;
     protected void Page_Load(object sender, EventArgs e)
    {
        SuperForm1 = new SuperForm();
        SuperForm1.ID = "SuperForm1";
        SuperForm1.Title = "Order Details";
        SuperForm1.DataSourceID = "SqlDataSource1";
        SuperForm1.AutoGenerateRows = false;
        SuperForm1.AutoGenerateInsertButton = true;
        SuperForm1.AutoGenerateEditButton = true;
        SuperForm1.AutoGenerateDeleteButton = true;
        SuperForm1.AllowDataKeysInsert = false;
        SuperForm1.DataKeyNames = new string[] { "OrderID" };
        SuperForm1.AllowPaging = true;
        SuperForm1.DefaultMode = DetailsViewMode.Insert;
        SuperForm1.EnableModelValidation = true;

        Obout.SuperForm.BoundField field1 = new Obout.SuperForm.BoundField();
        field1.DataField = "OrderID";
        field1.HeaderText = "Order ID";
        field1.ReadOnly = true;
        field1.InsertVisible = true;

        Obout.SuperForm.BoundField field2 = new Obout.SuperForm.BoundField();
        field2.DataField = "ShipName";
        field2.HeaderText = "Ship Name";

        Obout.SuperForm.DateField field3 = new Obout.SuperForm.DateField();
        field3.DataField = "OrderDate";
        field3.HeaderText = "Order Date";
        field3.DataFormatString = "{0:MM/dd/yyyy}";
        field3.ApplyFormatInEditMode = true;

        Obout.SuperForm.DateField field4 = new Obout.SuperForm.DateField();
        field4.DataField = "ShippedDate";
        field4.HeaderText = "Shipped Date";
        field4.DataFormatString = "{0:MM/dd/yyyy}";
        field4.ApplyFormatInEditMode = true;

        Obout.SuperForm.DateField field5 = new Obout.SuperForm.DateField();
        field5.DataField = "RequiredDate";
        field5.HeaderText = "Required Date";
        field5.DataFormatString = "{0:MM/dd/yyyy}";
        field5.ApplyFormatInEditMode = true;

        SuperForm1.Fields.Add(field1);
        SuperForm1.Fields.Add(field2);
        SuperForm1.Fields.Add(field3);
        SuperForm1.Fields.Add(field4);
        SuperForm1.Fields.Add(field5);

        SuperForm1Container.Controls.Add(SuperForm1);
        SuperForm1.DataBind();

        if (SuperForm1.CurrentMode == DetailsViewMode.Edit || SuperForm1.CurrentMode == DetailsViewMode.Insert)
        {
            OboutInc.Calendar2.Calendar orderDateCalendar = (OboutInc.Calendar2.Calendar)(SuperForm1.Rows[2].Cells[1].Controls[0].Controls[1].Controls[0]);
            orderDateCalendar.CultureName = ListBox1.SelectedValue;

            OboutInc.Calendar2.Calendar shippedDateCalendar = (OboutInc.Calendar2.Calendar)(SuperForm1.Rows[3].Cells[1].Controls[0].Controls[1].Controls[0]);
            shippedDateCalendar.CultureName = ListBox1.SelectedValue;

            OboutInc.Calendar2.Calendar requiredDateCalendar = (OboutInc.Calendar2.Calendar)(SuperForm1.Rows[4].Cells[1].Controls[0].Controls[1].Controls[0]);
            requiredDateCalendar.CultureName = ListBox1.SelectedValue;
        }
    }
}
