using System;
using System.Collections.Generic;

using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using Obout.SuperForm;
using Obout.Interface;
using Obout.ComboBox;

public partial class SuperForm_cs_templates_combobox_cascading : System.Web.UI.Page
{
    private SuperForm SuperForm1;
    protected void Page_Load(object sender, EventArgs e)
    {
        SuperForm1 = new SuperForm();
        SuperForm1.ID = "SuperForm1";
        SuperForm1.DataSourceID = "SqlDataSource1";
        SuperForm1.AutoGenerateRows = false;
        SuperForm1.AutoGenerateInsertButton = true;
        SuperForm1.AutoGenerateEditButton = true;
        SuperForm1.AutoGenerateDeleteButton = true;
        SuperForm1.AutoGenerateDateFields = true;
        SuperForm1.DataKeyNames = new string[] { "OrderID" };
        SuperForm1.AllowPaging = true;
        SuperForm1.DefaultMode = DetailsViewMode.Edit;
       
        SuperForm1.ItemUpdating += SuperForm1_ItemUpdating;
        SuperForm1.ItemInserting += SuperForm1_ItemInserting;
        SuperForm1.DataBound += SuperForm1_DataBound;

        Obout.SuperForm.BoundField field1 = new Obout.SuperForm.BoundField();
        field1.DataField = "OrderID";
        field1.HeaderText = "Order ID";
        field1.ReadOnly = true;
        field1.InsertVisible = false;

        Obout.SuperForm.BoundField field2 = new Obout.SuperForm.BoundField();
        field2.DataField = "ShipName";
        field2.HeaderText = "Ship Name";

        Obout.SuperForm.TemplateField field3 = new Obout.SuperForm.TemplateField();
        field3.HeaderText = "Ship Country";
        field3.ItemTemplate = new ShipCountryItemTemplate();
        field3.EditItemTemplate = new ShipCountryEditItemTemplate(SqlDataSource3);

        Obout.SuperForm.TemplateField field4 = new Obout.SuperForm.TemplateField();
        field4.HeaderText = "Ship City";
        field4.ItemTemplate = new ShipCityItemTemplate();
        field4.EditItemTemplate = new ShipCityEditItemTemplate();

        SuperForm1.Fields.Add(field1);
        SuperForm1.Fields.Add(field2);
        SuperForm1.Fields.Add(field3);
        SuperForm1.Fields.Add(field4);

        SuperForm1Container.Controls.Add(SuperForm1);

    }

    public class ShipCountryItemTemplate : ITemplate
    {
        public void InstantiateIn(Control container)
        {
            Literal templatePlaceHolder = new Literal();
            container.Controls.Add(templatePlaceHolder);

            templatePlaceHolder.DataBinding += new EventHandler(DataBindTemplate);
        }

        public void DataBindTemplate(object sender, EventArgs e)
        {
            Literal templatePlaceHolder = sender as Literal;
            DetailsViewRow row = templatePlaceHolder.Parent.Parent as DetailsViewRow;
            SuperForm form = row.Parent.Parent as SuperForm;

            templatePlaceHolder.Text = DataBinder.Eval(form.DataItem, "ShipCountry").ToString();
        }
    }

    public class ShipCountryEditItemTemplate : ITemplate
    {
        SqlDataSource citiesDataSource;

        public ShipCountryEditItemTemplate(SqlDataSource sds)
        {
            citiesDataSource = sds;
        }
        
        public void InstantiateIn(Control container)
        {
            PlaceHolder templatePlaceHolder = new PlaceHolder();
            container.Controls.Add(templatePlaceHolder);

            Obout.ComboBox.ComboBox comboBox = new Obout.ComboBox.ComboBox();
            templatePlaceHolder.Controls.Add(comboBox);

            comboBox.ID = "ShipCountry";
            comboBox.DataSourceID = "SqlDataSource2";
            comboBox.Width = Unit.Percentage(100);
            comboBox.Height = Unit.Pixel(150);
            comboBox.DataValueField = "ShipCountry";
            comboBox.DataTextField = "ShipCountry";
            comboBox.SelectedIndexChanged += ShipCountry_SelectedIndexChanged;
            comboBox.AutoPostBack = true;

            templatePlaceHolder.DataBinding += new EventHandler(DataBindTemplate);
        }

        public void DataBindTemplate(object sender, EventArgs e)
        {
            PlaceHolder templatePlaceHolder = sender as PlaceHolder;
            DetailsViewRow row = templatePlaceHolder.Parent.Parent as DetailsViewRow;
            SuperForm form = row.Parent.Parent as SuperForm;

            Obout.ComboBox.ComboBox comboBox = templatePlaceHolder.Controls[0] as Obout.ComboBox.ComboBox;

            comboBox.SelectedValue = DataBinder.Eval(form.DataItem, "ShipCountry").ToString();
        }

        protected void ShipCountry_SelectedIndexChanged(object sender, ComboBoxItemEventArgs e)
        {
            citiesDataSource.SelectParameters[0].DefaultValue = e.Item.Value;            
        }
    }

        public class ShipCityItemTemplate : ITemplate
        {
            public void InstantiateIn(Control container)
            {
                Literal templatePlaceHolder = new Literal();
                container.Controls.Add(templatePlaceHolder);

                templatePlaceHolder.DataBinding += new EventHandler(DataBindTemplate);
            }

            public void DataBindTemplate(object sender, EventArgs e)
            {
                Literal templatePlaceHolder = sender as Literal;
                DetailsViewRow row = templatePlaceHolder.Parent.Parent as DetailsViewRow;
                SuperForm form = row.Parent.Parent as SuperForm;

                templatePlaceHolder.Text = DataBinder.Eval(form.DataItem, "ShipCity").ToString();
            }
        }

        public class ShipCityEditItemTemplate : ITemplate
        {
            public void InstantiateIn(Control container)
            {
                PlaceHolder templatePlaceHolder = new PlaceHolder();
                container.Controls.Add(templatePlaceHolder);

                Obout.ComboBox.ComboBox comboBox = new Obout.ComboBox.ComboBox();
                templatePlaceHolder.Controls.Add(comboBox);

                comboBox.ID = "ShipCity";
                comboBox.DataSourceID = "SqlDataSource3";
                comboBox.Width = Unit.Percentage(100);
                comboBox.Height = Unit.Pixel(150);
                comboBox.DataValueField = "ShipCity";
                comboBox.DataTextField = "ShipCity";
                comboBox.AppendDataBoundItems = false;
            }
        }
        protected void SuperForm1_ItemUpdating(object sender, DetailsViewUpdateEventArgs e)
        {
            e.NewValues["ShipCountry"] = ((Obout.ComboBox.ComboBox)((DetailsViewRow)SuperForm1.Rows[2]).FindControl("ShipCountry")).SelectedValue;
            e.NewValues["ShipCity"] = ((Obout.ComboBox.ComboBox)((DetailsViewRow)SuperForm1.Rows[2]).FindControl("ShipCity")).SelectedValue;
        }

        protected void SuperForm1_ItemInserting(object sender, DetailsViewInsertEventArgs e)
        {
            e.Values["ShipCountry"] = ((Obout.ComboBox.ComboBox)((DetailsViewRow)SuperForm1.Rows[2]).FindControl("ShipCountry")).SelectedValue;
            e.Values["ShipCity"] = ((Obout.ComboBox.ComboBox)((DetailsViewRow)SuperForm1.Rows[2]).FindControl("ShipCity")).SelectedValue;
        }


        protected void SuperForm1_DataBound(object sender, EventArgs e)
        {
            if (SuperForm1.CurrentMode == DetailsViewMode.Edit)
            {
                SqlDataSource3.SelectParameters[0].DefaultValue = DataBinder.Eval(SuperForm1.DataItem, "ShipCountry").ToString();
                ((Obout.ComboBox.ComboBox)((DetailsViewRow)SuperForm1.Rows[2]).FindControl("ShipCity")).SelectedValue = DataBinder.Eval(SuperForm1.DataItem, "ShipCity").ToString();
            }
            else
            {
                SqlDataSource3.SelectParameters[0].DefaultValue = "";
            }
        }
    }

