using System;
using System.Collections.Generic;

using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using Obout.SuperForm;
using Obout.Interface;
using Obout.ComboBox;
using System.Data.OleDb;

public partial class SuperForm_cs_templates_combobox_multi : System.Web.UI.Page
{
    private SuperForm SuperForm1;
    protected void Page_Load(object sender, EventArgs e)
    {
        SuperForm1 = new SuperForm();
        SuperForm1.ID = "SuperForm1"; 
        SuperForm1.DataSourceID = "SqlDataSource1";
        SuperForm1.AutoGenerateRows = false;
        SuperForm1.AutoGenerateInsertButton = true;
        SuperForm1.AutoGenerateEditButton = true;
        SuperForm1.AutoGenerateDeleteButton = true;
        SuperForm1.AutoGenerateDateFields = true;
        SuperForm1.DataKeyNames = new string[] { "CustomerID" };
        SuperForm1.AllowPaging = true;
        SuperForm1.DefaultMode = DetailsViewMode.Edit;
       
        SuperForm1.ItemUpdating += SuperForm1_ItemUpdating;
        SuperForm1.ItemInserting += SuperForm1_ItemInserting;

        Obout.SuperForm.BoundField field1 = new Obout.SuperForm.BoundField();
        field1.DataField = "CustomerID";
        field1.HeaderText = "Customer ID";
        field1.ReadOnly = true;
        field1.InsertVisible = false;

        Obout.SuperForm.BoundField field2 = new Obout.SuperForm.BoundField();
        field2.DataField = "CompanyName";
        field2.HeaderText = "Company Name";

        Obout.SuperForm.BoundField field3 = new Obout.SuperForm.BoundField();
        field3.DataField = "ContactName";
        field3.HeaderText = "Contact Name";

        Obout.SuperForm.TemplateField field4 = new Obout.SuperForm.TemplateField();
        field4.HeaderText = "Countries";
        field4.ItemTemplate = new CountriesItemTemplate();
        field4.EditItemTemplate = new CountriesEditItemTemplate();

        SuperForm1.Fields.Add(field1);
        SuperForm1.Fields.Add(field2);
        SuperForm1.Fields.Add(field3);
        SuperForm1.Fields.Add(field4);

        SuperForm1Container.Controls.Add(SuperForm1);
    }
    public class CountriesItemTemplate : ITemplate
    {
        public void InstantiateIn(Control container)
        {
            Literal templatePlaceHolder = new Literal();
            container.Controls.Add(templatePlaceHolder);

            templatePlaceHolder.DataBinding += new EventHandler(DataBindTemplate);
        }

        public void DataBindTemplate(object sender, EventArgs e)
        {
            Literal templatePlaceHolder = sender as Literal;
            DetailsViewRow row = templatePlaceHolder.Parent.Parent as DetailsViewRow;
            SuperForm form = row.Parent.Parent as SuperForm;

            templatePlaceHolder.Text = GetCountries(DataBinder.Eval(form.DataItem, "CountryIds").ToString());
        }

        protected string GetCountries(string countryIds)
        {
            string countries = "";

            if (!string.IsNullOrEmpty(countryIds))
            {
                OleDbConnection myConn = new OleDbConnection("Provider=Microsoft.Jet.OLEDB.4.0;Data Source=|DataDirectory|NorthWind.mdb");

                OleDbCommand myComm = new OleDbCommand("SELECT CountryName FROM Countries WHERE CountryId IN (" + countryIds + ")", myConn);
                myConn.Open();
                OleDbDataReader myReader = myComm.ExecuteReader();

                while (myReader.Read())
                {
                    if (countries != "")
                    {
                        countries += ",";
                    }

                    countries += myReader["CountryName"].ToString();
                }

                myConn.Close();
            }

            return countries;
        }
    }

    public class CountriesEditItemTemplate : ITemplate
    {

        public void InstantiateIn(Control container)
        {
            PlaceHolder templatePlaceHolder = new PlaceHolder();
            container.Controls.Add(templatePlaceHolder);

            Obout.ComboBox.ComboBox comboBox = new Obout.ComboBox.ComboBox();
            templatePlaceHolder.Controls.Add(comboBox);

            comboBox.ID = "CountryIds";
            comboBox.DataSourceID = "SqlDataSource2";
            comboBox.Width = Unit.Percentage(100);
            comboBox.Height = Unit.Pixel(150);
            comboBox.DataValueField = "CountryID";
            comboBox.DataTextField = "CountryName";
            comboBox.SelectionMode = ListSelectionMode.Multiple;
            comboBox.AutoPostBack = true;

            templatePlaceHolder.DataBinding += new EventHandler(DataBindTemplate);
        }

        public void DataBindTemplate(object sender, EventArgs e)
        {
            PlaceHolder templatePlaceHolder = sender as PlaceHolder;
            DetailsViewRow row = templatePlaceHolder.Parent.Parent as DetailsViewRow;
            SuperForm form = row.Parent.Parent as SuperForm;

            Obout.ComboBox.ComboBox comboBox = templatePlaceHolder.Controls[0] as Obout.ComboBox.ComboBox;

            comboBox.SelectedValue = DataBinder.Eval(form.DataItem, "CountryIds").ToString();
        }

    }
    protected void SuperForm1_ItemUpdating(object sender, DetailsViewUpdateEventArgs e)
    {
        e.NewValues["CountryIds"] = GetSelectedCountries();
    }

    protected void SuperForm1_ItemInserting(object sender, DetailsViewInsertEventArgs e)
    {
        e.Values["CountryIds"] = GetSelectedCountries();
    }

    protected string GetSelectedCountries()
    {
        Obout.ComboBox.ComboBox CountryIds = (Obout.ComboBox.ComboBox)((DetailsViewRow)SuperForm1.Rows[3]).FindControl("CountryIds");

        string selectedCountryIds = "";

        foreach (ComboBoxItem item in CountryIds.Items)
        {
            if (item.Selected == true)
            {
                if (selectedCountryIds != "")
                {
                    selectedCountryIds += ",";
                }

                selectedCountryIds += item.Value;
            }
        }

        return selectedCountryIds;
    }

  
}
