using System;
using System.Collections.Generic;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using Obout.SuperForm;
using Obout.Interface;
using Obout.ComboBox;
using System.Data.OleDb;
public partial class SuperForm_cs_templates_fileupload : System.Web.UI.Page
{
    private SuperForm SuperForm1;
    private string fileName = "";

    protected void Page_Load(object sender, EventArgs e)
    {
        SuperForm1 = new SuperForm();
        SuperForm1.ID = "SuperForm1";
        SuperForm1.Width = Unit.Pixel(350);
        SuperForm1.DataSourceID = "SqlDataSource1";
        SuperForm1.AutoGenerateRows = false;
        SuperForm1.AutoGenerateInsertButton = true;
        SuperForm1.AutoGenerateEditButton = true;
        SuperForm1.AutoGenerateDeleteButton = true;
        SuperForm1.AutoGenerateDateFields = true;
        SuperForm1.DataKeyNames = new string[] { "ProductID" };
        SuperForm1.AllowPaging = true;
        SuperForm1.DefaultMode = DetailsViewMode.Edit;
        SuperForm1.HeaderStyle.Width = Unit.Pixel(150);
        
        SuperForm1.ItemUpdating += SuperForm1_ItemUpdating;
        SuperForm1.ItemInserting += SuperForm1_ItemInserting;

        Obout.SuperForm.BoundField field1 = new Obout.SuperForm.BoundField();
        field1.DataField = "ProductID";
        field1.HeaderText = "Product ID";
        field1.ReadOnly = true;
        field1.InsertVisible = false;
        field1.ItemStyle.Width = Unit.Pixel(225);

        Obout.SuperForm.BoundField field2 = new Obout.SuperForm.BoundField();
        field2.DataField = "ProductName";
        field2.HeaderText = "Product Name";
        field2.ItemStyle.Width = Unit.Pixel(225);

        Obout.SuperForm.BoundField field3 = new Obout.SuperForm.BoundField();
        field3.DataField = "UnitPrice";
        field3.HeaderText = "Unit Price";
        field3.ItemStyle.Width = Unit.Pixel(225);

        Obout.SuperForm.TemplateField field4 = new Obout.SuperForm.TemplateField();
        field4.HeaderText = "Image";
        field4.ItemTemplate = new ImageItemTemplate();
        field4.EditItemTemplate = new ImageEditItemTemplate();

        SuperForm1.Fields.Add(field1);
        SuperForm1.Fields.Add(field2);
        SuperForm1.Fields.Add(field3);
        SuperForm1.Fields.Add(field4);

        SuperForm1Container.Controls.Add(SuperForm1);

        fileName = "";
       
        if (Page.IsPostBack)
        {
            HttpFileCollection files = Page.Request.Files;

            if (files.Count > 0)
            {
                fileName = DateTime.Now.Ticks.ToString() + "_" + files[0].FileName;

                files[0].SaveAs(Server.MapPath("~/Grid/resources/images/products/" + fileName));
            }
        }
    }

    public class ImageItemTemplate : ITemplate
    {
        public void InstantiateIn(Control container)
        {
            PlaceHolder templatePlaceHolder = new PlaceHolder();
            container.Controls.Add(templatePlaceHolder);

            Image img = new Image();
            templatePlaceHolder.Controls.Add(img);

            templatePlaceHolder.DataBinding += new EventHandler(DataBindTemplate);
        }

        public void DataBindTemplate(object sender, EventArgs e)
        {
            PlaceHolder templatePlaceHolder = sender as PlaceHolder;
            DetailsViewRow row = templatePlaceHolder.Parent.Parent as DetailsViewRow;
            SuperForm form = row.Parent.Parent as SuperForm;

            Image img = templatePlaceHolder.Controls[0] as Image;

            img.ImageUrl = "~/Grid/resources/images/products/" + DataBinder.Eval(form.DataItem, "Image").ToString();
            img.AlternateText = "";
            img.Width = 100; 
        }
    }
    public class ImageEditItemTemplate : ITemplate
    {

        public void InstantiateIn(Control container)
        {
            PlaceHolder templatePlaceHolder = new PlaceHolder();
            container.Controls.Add(templatePlaceHolder);

            FileUpload fileUpload = new FileUpload();
            fileUpload.Width = Unit.Pixel(200);
            templatePlaceHolder.Controls.Add(fileUpload);

           
        }
    }
    protected void SuperForm1_ItemUpdating(object sender, DetailsViewUpdateEventArgs e)
    {
        e.NewValues["Image"] = fileName;
    }

    protected void SuperForm1_ItemInserting(object sender, DetailsViewInsertEventArgs e)
    {
        e.Values["Image"] = fileName;
    }
        
}
