using System;
using System.Collections.Generic;

using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using Obout.SuperForm;
using Obout.Interface;
using Obout.ComboBox;
using System.Data.OleDb;

public partial class SuperForm_cs_templates_combobox_multilevel : System.Web.UI.Page
{
    private SuperForm SuperForm1;
    protected void Page_Load(object sender, EventArgs e)
    {
        SuperForm1 = new SuperForm();
        SuperForm1.ID = "SuperForm1";
        SuperForm1.DataSourceID = "SqlDataSource1";
        SuperForm1.AutoGenerateRows = false;
        SuperForm1.AutoGenerateInsertButton = true;
        SuperForm1.AutoGenerateEditButton = true;
        SuperForm1.AutoGenerateDeleteButton = true;
        SuperForm1.AutoGenerateDateFields = true;
        SuperForm1.DataKeyNames = new string[] { "OrderID" };
        SuperForm1.AllowPaging = true;
        SuperForm1.DefaultMode = DetailsViewMode.Edit;
        SuperForm1.ItemUpdating += SuperForm1_ItemUpdating;
        SuperForm1.ItemInserting += SuperForm1_ItemInserting;
        SuperForm1.DataBound += SuperForm1_DataBound;

        Obout.SuperForm.BoundField field1 = new Obout.SuperForm.BoundField();
        field1.DataField = "OrderID";
        field1.HeaderText = "Order ID";
        field1.ReadOnly = true;
        field1.InsertVisible = false;

        Obout.SuperForm.BoundField field2 = new Obout.SuperForm.BoundField();
        field2.DataField = "ShipName";
        field2.HeaderText = "Ship Name";

        Obout.SuperForm.TemplateField field3 = new Obout.SuperForm.TemplateField();
        field3.HeaderText = "Ship Country";
        field3.ItemTemplate = new ShipCountryItemTemplate();
        field3.EditItemTemplate = new ShipCountryEditItemTemplate(CountriesDataSource);

        Obout.SuperForm.BoundField field4 = new Obout.SuperForm.BoundField();
        field4.DataField = "ShipCity";
        field4.HeaderText = "Ship City";

        Obout.SuperForm.BoundField field5 = new Obout.SuperForm.BoundField();
        field5.DataField = "ShipRegion";
        field5.HeaderText = "Ship Region";

        SuperForm1.Fields.Add(field1);
        SuperForm1.Fields.Add(field2);
        SuperForm1.Fields.Add(field3);
        SuperForm1.Fields.Add(field4);
        SuperForm1.Fields.Add(field5);

        SuperForm1Container.Controls.Add(SuperForm1);
       
    }
    public class ShipCountryItemTemplate : ITemplate
    {
        public void InstantiateIn(Control container)
        {
            Literal templatePlaceHolder = new Literal();
            container.Controls.Add(templatePlaceHolder);

            templatePlaceHolder.DataBinding += new EventHandler(DataBindTemplate);
        }

        public void DataBindTemplate(object sender, EventArgs e)
        {
            Literal templatePlaceHolder = sender as Literal;
            DetailsViewRow row = templatePlaceHolder.Parent.Parent as DetailsViewRow;
            SuperForm form = row.Parent.Parent as SuperForm;

            templatePlaceHolder.Text = DataBinder.Eval(form.DataItem, "ShipCountry").ToString();
        }
    }
    public class ShipCountryEditItemTemplate : ITemplate
    {    
        SqlDataSource citiesDataSource;

        public ShipCountryEditItemTemplate(SqlDataSource sds)
        {
            citiesDataSource = sds;
        }
        public void InstantiateIn(Control container)
        {
            PlaceHolder templatePlaceHolder = new PlaceHolder();
            container.Controls.Add(templatePlaceHolder);

            Obout.ComboBox.ComboBox comboBox1 = new Obout.ComboBox.ComboBox();
            Obout.ComboBox.ComboBox comboBox2 = new Obout.ComboBox.ComboBox();
            templatePlaceHolder.Controls.Add(comboBox1);

            comboBox1.ID = "ShipCountry";
            comboBox1.DataSourceID = "ContinentsDataSource";
            comboBox1.AutoClose = false;
            comboBox1.Width = Unit.Percentage(100);
            comboBox1.MenuWidth= Unit.Pixel(150);
            comboBox1.Height = Unit.Pixel(150);
            comboBox1.DataValueField = "ContinentID";
            comboBox1.DataTextField = "ContinentName";
            comboBox1.EmptyText = "Select a country ...";
            comboBox1.HeaderTemplate = new HeaderTemplate("CONTINENTS");
            
            comboBox2.ID = "CountriesCombo";
            comboBox2.DataSourceID = "CountriesDataSource";
            comboBox2.LoadingItems += CountriesCombo_LoadingItems;
            comboBox2.Width= Unit.Pixel(150);
            comboBox2.Height = Unit.Pixel(150);
            comboBox2.DataValueField = "CountryName";
            comboBox2.DataTextField = "CountryName";
            comboBox2.EnableLoadOnDemand = true;
            comboBox2.HeaderTemplate = new HeaderTemplate("COUNTRIES");

            comboBox1.Details.Add(comboBox2);
        }
       
        protected void CountriesCombo_LoadingItems(object sender, ComboBoxLoadingItemsEventArgs e)
        {
            if (!string.IsNullOrEmpty(e.Text))
            {
                int tryout = 0;
                if (int.TryParse(e.Text, out tryout))
                {
                    citiesDataSource.SelectParameters[0].DefaultValue = e.Text;
                }
            }
        }
    }
    public class HeaderTemplate : ITemplate
    {
        private string _headerText = "";
        public HeaderTemplate(string headerText)
        {
            _headerText = headerText;
        }

        public void InstantiateIn(Control container)
        {
            Literal header1 = new Literal();
            header1.Text = "<div class=\"header\">" + _headerText + "</div>";
            container.Controls.Add(header1);
        }
    }
    protected void SuperForm1_ItemUpdating(object sender, DetailsViewUpdateEventArgs e)
    {
        e.NewValues["ShipCountry"] = ((Obout.ComboBox.ComboBox)((DetailsViewRow)SuperForm1.Rows[2]).FindControl("ShipCountry")).SelectedText;
        string test = e.NewValues["ShipCountry"].ToString();
    }

    protected void SuperForm1_ItemInserting(object sender, DetailsViewInsertEventArgs e)
    {
        e.Values["ShipCountry"] = ((Obout.ComboBox.ComboBox)((DetailsViewRow)SuperForm1.Rows[4]).FindControl("ShipCountry")).SelectedValue;
    }

    protected void SuperForm1_DataBound(object sender, EventArgs e)
    {
        if (SuperForm1.CurrentMode == DetailsViewMode.Edit)
        {
            string shipCountry = DataBinder.Eval(SuperForm1.DataItem, "ShipCountry").ToString();
            string continentId = "0";

            OleDbConnection myConn = new OleDbConnection("Provider=Microsoft.Jet.OLEDB.4.0;Data Source=" + Server.MapPath("../App_Data/continent.mdb"));
            myConn.Open();

            OleDbCommand myComm = new OleDbCommand("SELECT ContinentID FROM Country WHERE CountryName = @CountryName", myConn);
            myComm.Parameters.Add("@CountryName", OleDbType.VarChar).Value = shipCountry;

            OleDbDataReader myReader = myComm.ExecuteReader();
            if (myReader.Read())
            {
                continentId = myReader[0].ToString();
            }

            myConn.Close();


            Obout.ComboBox.ComboBox shipCountryCombo = ((Obout.ComboBox.ComboBox)((DetailsViewRow)SuperForm1.Rows[2]).FindControl("ShipCountry"));
            shipCountryCombo.Details[0].SelectedValue = shipCountry;
            shipCountryCombo.SelectedValue = continentId;
        }
    }
}
