using System;
using System.Collections.Generic;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using Obout.SuperForm;
using Obout.Interface;
using Obout.ComboBox;

public partial class SuperForm_cs_templates_combobox_ondemand: System.Web.UI.Page
{
    private SuperForm SuperForm1;
    protected void Page_Load(object sender, EventArgs e)
    {
        SuperForm1 = new SuperForm();
        SuperForm1.ID = "SuperForm1";
        SuperForm1.DataSourceID = "SqlDataSource1";
        SuperForm1.AutoGenerateRows = false;
        SuperForm1.AutoGenerateInsertButton = true;
        SuperForm1.AutoGenerateEditButton = true;
        SuperForm1.AutoGenerateDeleteButton = true;
        SuperForm1.AutoGenerateDateFields = true;
        SuperForm1.DataKeyNames = new string[] { "OrderID" };
        SuperForm1.AllowPaging = true;
        SuperForm1.DefaultMode = DetailsViewMode.Edit;

        SuperForm1.DataBound += SuperForm1_DataBound;
        SuperForm1.ItemUpdating += SuperForm1_ItemUpdating;
        SuperForm1.ItemInserting += SuperForm1_ItemInserting;

        Obout.SuperForm.BoundField field1 = new Obout.SuperForm.BoundField();
        field1.DataField = "OrderID";
        field1.HeaderText = "Order ID";
        field1.ReadOnly = true;
        field1.InsertVisible = false;

        Obout.SuperForm.BoundField field2 = new Obout.SuperForm.BoundField();
        field2.DataField = "ShipName";
        field2.HeaderText = "Ship Name";

        Obout.SuperForm.BoundField field3 = new Obout.SuperForm.BoundField();
        field3.DataField = "ShipCity";
        field3.HeaderText = "Ship City";

        Obout.SuperForm.BoundField field4 = new Obout.SuperForm.BoundField();
        field4.DataField = "ShipRegion";
        field4.HeaderText = "Ship Region";

        Obout.SuperForm.TemplateField field5 = new Obout.SuperForm.TemplateField();
        field5.HeaderText = "Ship Country";
        field5.ItemTemplate = new ShipCountryItemTemplate();
        field5.EditItemTemplate = new ShipCountryEditItemTemplate(SqlDataSource2);

        SuperForm1.Fields.Add(field1);
        SuperForm1.Fields.Add(field2);
        SuperForm1.Fields.Add(field3);
        SuperForm1.Fields.Add(field4);
        SuperForm1.Fields.Add(field5);

        SuperForm1Container.Controls.Add(SuperForm1);
       
    }

    protected void SuperForm1_DataBound(object sender, EventArgs e)
    {
        if (SuperForm1.CurrentMode == DetailsViewMode.Edit)
        {
            string selectedCountry = DataBinder.Eval(SuperForm1.DataItem, "ShipCountry").ToString();
            ComboBox ShipCountryComboBox = (ComboBox)((DetailsViewRow)SuperForm1.Rows[4]).FindControl("ShipCountry");            

            // Creating an new item using the selected country and marking it as selected
            ComboBoxItem item = new ComboBoxItem();
            item.Value = selectedCountry;
            item.Text = selectedCountry;
            item.Selected = true;
            ShipCountryComboBox.Items.Add(item);

            ShipCountryComboBox.DataBind();
        }
    }

    protected void SuperForm1_ItemUpdating(object sender, DetailsViewUpdateEventArgs e)
    {
        e.NewValues["ShipCountry"] = ((Obout.ComboBox.ComboBox)((DetailsViewRow)SuperForm1.Rows[4]).FindControl("ShipCountry")).SelectedValue;
    }

    protected void SuperForm1_ItemInserting(object sender, DetailsViewInsertEventArgs e)
    {
        e.Values["ShipCountry"] = ((Obout.ComboBox.ComboBox)((DetailsViewRow)SuperForm1.Rows[4]).FindControl("ShipCountry")).SelectedValue;
    }    

    public class ShipCountryItemTemplate : ITemplate
    {
        public void InstantiateIn(Control container)
        {
            Literal templatePlaceHolder = new Literal();
            container.Controls.Add(templatePlaceHolder);

            templatePlaceHolder.DataBinding += new EventHandler(DataBindTemplate);
        }

        public void DataBindTemplate(object sender, EventArgs e)
        {
            Literal templatePlaceHolder = sender as Literal;
            DetailsViewRow row = templatePlaceHolder.Parent.Parent as DetailsViewRow;
            SuperForm form = row.Parent.Parent as SuperForm;

            templatePlaceHolder.Text = DataBinder.Eval(form.DataItem, "ShipCountry").ToString();
        }
    }

    public class ShipCountryEditItemTemplate : ITemplate
    {
        protected SqlDataSource dataSource;

        public ShipCountryEditItemTemplate(SqlDataSource _dataSource)
        {
            dataSource = _dataSource;
        }
        
        public void InstantiateIn(Control container)
        {
            PlaceHolder templatePlaceHolder = new PlaceHolder();
            container.Controls.Add(templatePlaceHolder);

            Obout.ComboBox.ComboBox comboBox = new Obout.ComboBox.ComboBox();
            templatePlaceHolder.Controls.Add(comboBox);

            comboBox.LoadingItems += ShipCountry_LoadingItems;
            comboBox.ID = "ShipCountry";
            comboBox.Height = Unit.Pixel(150);
            comboBox.Width = Unit.Percentage(100);
            comboBox.DataValueField = "ShipCountry";
            comboBox.DataTextField = "ShipCountry";            
            comboBox.EnableLoadOnDemand = true;

            templatePlaceHolder.DataBinding += new EventHandler(DataBindTemplate);
        }

        protected void ShipCountry_LoadingItems(object sender, ComboBoxLoadingItemsEventArgs e)
        {
            (sender as ComboBox).Items.Clear();
            dataSource.SelectParameters[0].DefaultValue = e.Text + "%";
            (sender as ComboBox).DataSourceID = "SqlDataSource2";
        }

        public void DataBindTemplate(object sender, EventArgs e)
        {
            PlaceHolder templatePlaceHolder = sender as PlaceHolder;
            DetailsViewRow row = templatePlaceHolder.Parent.Parent as DetailsViewRow;
            SuperForm form = row.Parent.Parent as SuperForm;

            Obout.ComboBox.ComboBox comboBox = templatePlaceHolder.Controls[0] as Obout.ComboBox.ComboBox;

            comboBox.SelectedValue = DataBinder.Eval(form.DataItem, "ShipCountry").ToString();
        }
    }
}
