using System;
using System.Collections.Generic;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using Obout.SuperForm;

public partial class SuperForm_cs_validation_custom : System.Web.UI.Page
{
    private SuperForm SuperForm1;
    protected void Page_Load(object sender, EventArgs e)
    {
        SuperForm1 = new SuperForm();
        SuperForm1.ID = "SuperForm1";
        SuperForm1.Title = "Employee Form";
        SuperForm1.DataSourceID = "SqlDataSource1";
        SuperForm1.AutoGenerateRows = false;
        SuperForm1.AutoGenerateInsertButton = true;
        SuperForm1.AutoGenerateEditButton = true;
        SuperForm1.AutoGenerateDeleteButton = true;
        SuperForm1.DataKeyNames = new string[] { "EmployeeID" };
        SuperForm1.AllowPaging = true;
        SuperForm1.DefaultMode = DetailsViewMode.Edit;

        CustomValidator field4Custom = new CustomValidator();
        field4Custom.ID = "CustomValidator1";
        field4Custom.ServerValidate += ValidateTitle;
        field4Custom.ErrorMessage = "Title needs to be 'Mr.', 'Ms.', 'Mrs.' or 'Dr.'";
        field4Custom.Display = ValidatorDisplay.Dynamic;

        RangeValidator field5Custom = new RangeValidator();
        field5Custom.ID = "RangeValidator1";
        field5Custom.MinimumValue = "1900/1/1";
        field5Custom.MaximumValue = "2039/12/31";
        field5Custom.Type = ValidationDataType.Date;
        field5Custom.ErrorMessage = "*";

        RegularExpressionValidator field6Custom = new RegularExpressionValidator();
        field6Custom.ID = "RegularExpressionValidator1";
        field6Custom.Display = ValidatorDisplay.Dynamic;
        field6Custom.ValidationExpression = "^(\\(?\\s*\\d{3}\\s*[\\)\\-\\.]?\\s*)?[1-9]\\d{2}\\s*[\\-\\.]\\s*\\d{4}$";
        field6Custom.ErrorMessage = "Phone numbers must have this format (###) ###-####";

        Obout.SuperForm.BoundField field1 = new Obout.SuperForm.BoundField();
        field1.DataField = "EmployeeID";
        field1.HeaderText = "Employee ID";
        field1.ReadOnly = true;
        field1.InsertVisible = false;

        Obout.SuperForm.BoundField field2 = new Obout.SuperForm.BoundField();
        field2.DataField = "FirstName";
        field2.HeaderText = "First Name";
        field2.Required = true;

        Obout.SuperForm.BoundField field3 = new Obout.SuperForm.BoundField();
        field3.DataField = "LastName";
        field3.HeaderText = "Last Name";
        field3.Required = true;

        Obout.SuperForm.BoundField field4 = new Obout.SuperForm.BoundField();
        field4.DataField = "TitleOfCourtesy";
        field4.HeaderText = "Courtesy Title";
        field4.Required = true;
        field4.Validators.Add(field4Custom);
                
        Obout.SuperForm.DateField field5 = new Obout.SuperForm.DateField();
        field5.DataField = "BirthDate";
        field5.HeaderText = "Birth Date";
        field5.Required = true;
        field5.DataFormatString = "{0:MM/dd/yyyy}";
        field5.ApplyFormatInEditMode = true;
        field5.Validators.Add(field5Custom);

        Obout.SuperForm.BoundField field6 = new Obout.SuperForm.BoundField();
        field6.DataField = "HomePhone";
        field6.HeaderText = "Home Phone";
        field6.Required = true;
        field6.Validators.Add(field6Custom);
  
        SuperForm1.Fields.Add(field1);
        SuperForm1.Fields.Add(field2);
        SuperForm1.Fields.Add(field3);
        SuperForm1.Fields.Add(field4);
        SuperForm1.Fields.Add(field5);
        SuperForm1.Fields.Add(field6);

        SuperForm1Container.Controls.Add(SuperForm1);
       
    }
    protected void ValidateTitle(object sender, ServerValidateEventArgs e)
    {
        if (e.Value != "Mr." && e.Value != "Ms." && e.Value != "Mrs." && e.Value != "Dr.")
        {
            e.IsValid = false;
            return;
        }

        e.IsValid = true;
    }
}
