using System;
using System.Collections.Generic;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using Obout.SuperForm;
using Obout.Interface;

public partial class SuperForm_cs_validation_required : System.Web.UI.Page
{
    private SuperForm SuperForm1;
    protected void Page_Load(object sender, EventArgs e)
    {
        SuperForm1 = new SuperForm();
        SuperForm1.ID = "SuperForm1";
        SuperForm1.Title = "Order Details";
        SuperForm1.DataSourceID = "SqlDataSource1";
        SuperForm1.AutoGenerateRows = false;
        SuperForm1.AutoGenerateInsertButton = true;
        SuperForm1.AutoGenerateEditButton = true;
        SuperForm1.AutoGenerateDeleteButton = true;
        SuperForm1.DataKeyNames = new string[] { "OrderID" };
        SuperForm1.AllowPaging = true;
        SuperForm1.DefaultMode = DetailsViewMode.Insert;
        SuperForm1.AllowDataKeysInsert = false;
        SuperForm1.EnableModelValidation = true;
        SuperForm1.DataBound += SuperForm1_DataBound;

        RequiredFieldValidator RequiredFieldValidator1 = new RequiredFieldValidator();
        RequiredFieldValidator1.ID = "RequiredFieldValidator1";
        RequiredFieldValidator1.ErrorMessage = "*";
        RequiredFieldValidator1.InitialValue = "Select a customer ...";

        RequiredFieldValidator RequiredFieldValidator2 = new RequiredFieldValidator();
        RequiredFieldValidator2.ID = "RequiredFieldValidator2";
        RequiredFieldValidator2.ErrorMessage = "*";
        RequiredFieldValidator2.InitialValue = "Select a country ...";

        Obout.SuperForm.BoundField field1 = new Obout.SuperForm.BoundField();
        field1.DataField = "OrderID";
        field1.HeaderText = "OrderID";
        field1.ReadOnly = true;
        field1.InsertVisible = false;

        Obout.SuperForm.DropDownListField field2 = new Obout.SuperForm.DropDownListField();
        field2.DataField = "CustomerID";
        field2.DisplayField = "CompanyName";
        field2.HeaderText = "Customer";
        field2.DataSourceID = "SqlDataSource3";
        field2.Validators.Add(RequiredFieldValidator1);

        Obout.SuperForm.DropDownListField field3 = new Obout.SuperForm.DropDownListField();
        field3.DataField = "ShipCountry";
        field3.HeaderText = "Country";
        field3.DisplayField = "ShipCountry";
        field3.DataSourceID = "SqlDataSource2";
        field3.Validators.Add(RequiredFieldValidator2);

        SuperForm1.Fields.Add(field1);
        SuperForm1.Fields.Add(field2);
        SuperForm1.Fields.Add(field3);

        SuperForm1Container.Controls.Add(SuperForm1);
    }
    protected void SuperForm1_DataBound(object sender, EventArgs e)
    {
        if (SuperForm1.CurrentMode != DetailsViewMode.ReadOnly)
        {
            OboutDropDownList customerIDDdl = SuperForm1.GetFieldControl(1) as OboutDropDownList;
            customerIDDdl.Items.Insert(0, new ListItem("Select a customer ..."));

            OboutDropDownList shipCountryDdl = SuperForm1.GetFieldControl(2) as OboutDropDownList;
            shipCountryDdl.Items.Insert(0, new ListItem("Select a country ..."));
        }
    }
}
