using System;
using System.Collections.Generic;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using Obout.SuperForm;

public partial class SuperForm_cs_validation_summary : System.Web.UI.Page
{
    private SuperForm SuperForm1;
    protected void Page_Load(object sender, EventArgs e)
    {
        SuperForm1 = new SuperForm();
        SuperForm1.ID = "SuperForm1";
        SuperForm1.Title = "Employee Form";
        SuperForm1.DataSourceID = "SqlDataSource1";
        SuperForm1.AutoGenerateRows = false;
        SuperForm1.AutoGenerateInsertButton = true;
        SuperForm1.AutoGenerateEditButton = true;
        SuperForm1.AutoGenerateDeleteButton = true;
        SuperForm1.DataKeyNames = new string[] { "EmployeeID" };
        SuperForm1.AllowPaging = true;
        SuperForm1.ValidationGroup = "Group1";
        SuperForm1.DefaultMode = DetailsViewMode.Insert;
        SuperForm1.ItemCommand += SuperForm1_ItemCommand;

        RequiredFieldValidator field2Required = new RequiredFieldValidator();
        field2Required.ID = "RequiredFieldValidator1";
        field2Required.Display = ValidatorDisplay.Dynamic;
        field2Required.ErrorMessage = "First Name is mandatory";
        field2Required.Text = "*";
        field2Required.ValidationGroup = "Group1";

        RequiredFieldValidator field3Required = new RequiredFieldValidator();
        field3Required.ID = "RequiredFieldValidator2";
        field3Required.Display = ValidatorDisplay.Dynamic;
        field3Required.ErrorMessage = "Last Name is mandatory";
        field3Required.Text = "*";
        field3Required.ValidationGroup = "Group1";

        RequiredFieldValidator field4Required = new RequiredFieldValidator();
        field4Required.ID = "RequiredFieldValidator3";
        field4Required.Display = ValidatorDisplay.Dynamic;
        field4Required.ErrorMessage = "Courtesy Title is mandatory";
        field4Required.Text = "*";
        field4Required.ValidationGroup = "Group1";

        CustomValidator field4Custom = new CustomValidator();
        field4Custom.ID = "CustomValidator1";
        field4Custom.ServerValidate += ValidateTitle;
        field4Custom.Display = ValidatorDisplay.Dynamic;
        field4Custom.ErrorMessage = "Courtesy Title needs to be 'Mr.', 'Ms.', 'Mrs.' or 'Dr.'";
        field4Custom.Text = "*"; 
        field4Custom.ValidationGroup = "Group1";
    
        RequiredFieldValidator field5Required = new RequiredFieldValidator();
        field5Required.ID = "RequiredFieldValidator4";
        field5Required.Display = ValidatorDisplay.Dynamic;
        field5Required.ErrorMessage = "Birth Date is mandatory";
        field5Required.Text = "*";
        field5Required.ValidationGroup = "Group1";

        RangeValidator field5Custom = new RangeValidator();
        field5Custom.ID = "RangeValidator1";
        field5Custom.Display = ValidatorDisplay.Dynamic;
        field5Custom.MinimumValue = "1900/1/1";
        field5Custom.MaximumValue = "2039/12/31";
        field5Custom.Type = ValidationDataType.Date;
        field5Custom.ErrorMessage = "Birth Date needs to be in this format: mm/dd/yyyy";
        field5Custom.Text = "*";
        field5Custom.ValidationGroup = "Group1";
                
        RequiredFieldValidator field6Required = new RequiredFieldValidator();
        field6Required.ID = "RequiredFieldValidator5";
        field6Required.Display = ValidatorDisplay.Dynamic;
        field6Required.ErrorMessage = "Home Phone is mandatory";
        field6Required.Text = "*";
        field6Required.ValidationGroup = "Group1";

        RegularExpressionValidator field6Custom = new RegularExpressionValidator();
        field6Custom.ID = "RegularExpressionValidator1";
        field6Custom.Display = ValidatorDisplay.Dynamic;
        field6Custom.ValidationExpression = "^(\\(?\\s*\\d{3}\\s*[\\)\\-\\.]?\\s*)?[1-9]\\d{2}\\s*[\\-\\.]\\s*\\d{4}$";
        field6Custom.ErrorMessage = "Home Phone must have this format (###) ###-####";
        field6Custom.Text = "*";
        field6Custom.ValidationGroup = "Group1";

        Obout.SuperForm.BoundField field1 = new Obout.SuperForm.BoundField();
        field1.DataField = "EmployeeID";
        field1.HeaderText = "Employee ID";
        field1.ReadOnly = true;
        field1.InsertVisible = false;

        Obout.SuperForm.BoundField field2 = new Obout.SuperForm.BoundField();
        field2.DataField = "FirstName";
        field2.HeaderText = "First Name";
        field2.Validators.Add(field2Required);

        Obout.SuperForm.BoundField field3 = new Obout.SuperForm.BoundField();
        field3.DataField = "LastName";
        field3.HeaderText = "Last Name";
        field3.Validators.Add(field3Required);

        Obout.SuperForm.BoundField field4 = new Obout.SuperForm.BoundField();
        field4.DataField = "TitleOfCourtesy";
        field4.HeaderText = "Courtesy Title";
        field4.Validators.Add(field4Required);
        field4.Validators.Add(field4Custom);

        Obout.SuperForm.DateField field5 = new Obout.SuperForm.DateField();
        field5.DataField = "BirthDate";
        field5.HeaderText = "Birth Date";
        field5.DataFormatString = "{0:MM/dd/yyyy}";
        field5.ApplyFormatInEditMode = true;
        field5.Validators.Add(field5Required);
        field5.Validators.Add(field5Custom);

        Obout.SuperForm.BoundField field6 = new Obout.SuperForm.BoundField();
        field6.DataField = "HomePhone";
        field6.HeaderText = "Home Phone";
        field6.Validators.Add(field6Required);
        field6.Validators.Add(field6Custom);

        SuperForm1.Fields.Add(field1);
        SuperForm1.Fields.Add(field2);
        SuperForm1.Fields.Add(field3);
        SuperForm1.Fields.Add(field4);
        SuperForm1.Fields.Add(field5);
        SuperForm1.Fields.Add(field6);

        SuperForm1Container.Controls.Add(SuperForm1);
       
    }
    protected void ValidateTitle(object sender, ServerValidateEventArgs e)
    {
        if (e.Value != "Mr." && e.Value != "Ms." && e.Value != "Mrs." && e.Value != "Dr.")
        {
            e.IsValid = false;
            return;
        }

        e.IsValid = true;
    }

    protected void SuperForm1_ItemCommand(object sender, DetailsViewCommandEventArgs e)
    {
        if (e.CommandName == "Cancel")
        {
            SuperForm1.DefaultMode = DetailsViewMode.ReadOnly;
        }
    }
}
