using System;
using System.Collections.Generic;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using Obout.SuperForm;
using Obout.Interface;

public partial class SuperForm_cs_validation_required : System.Web.UI.Page
{
    private SuperForm SuperForm1;
    protected void Page_Load(object sender, EventArgs e)
    {
        SuperForm1 = new SuperForm();
        SuperForm1.ID = "SuperForm1";
        SuperForm1.DataSourceID = "SqlDataSource1";
        SuperForm1.AutoGenerateRows = false;
        SuperForm1.AutoGenerateInsertButton = true;
        SuperForm1.AutoGenerateEditButton = true;
        SuperForm1.AutoGenerateDeleteButton = true;
        SuperForm1.DataKeyNames = new string[] { "ProductID" };
        SuperForm1.AllowPaging = true;
        SuperForm1.DefaultMode = DetailsViewMode.Edit;

        SuperForm1.DataBound += SuperForm1_DataBound;

        Obout.SuperForm.BoundField field1 = new Obout.SuperForm.BoundField();
        field1.DataField = "ProductID";
        field1.HeaderText = "Product ID";
        field1.ReadOnly = true;
        field1.InsertVisible = false;

        Obout.SuperForm.BoundField field2 = new Obout.SuperForm.BoundField();
        field2.DataField = "ProductName";
        field2.HeaderText = "Product Name";
        field2.Required = true;

        Obout.SuperForm.CheckBoxField field3 = new Obout.SuperForm.CheckBoxField();
        field3.DataField = "Discontinued";
        field3.HeaderText = "Discontinued";
        field3.FieldsToDisable="UnitPrice,UnitsInStock,UnitsOnOrder";

        Obout.SuperForm.BoundField field4 = new Obout.SuperForm.BoundField();
        field4.DataField = "UnitPrice";
        field4.HeaderText = "Unit Price";
        field4.Collapsed = true;

        RequiredFieldValidator requiredField1 = new RequiredFieldValidator();
        requiredField1.ID = "RequiredFieldValidator1";
        requiredField1.ErrorMessage = "*";
        field4.Validators.Add(requiredField1);
 
        Obout.SuperForm.BoundField field5 = new Obout.SuperForm.BoundField();
        field5.DataField = "UnitsInStock";
        field5.HeaderText = "Units In Stock";
        field5.Collapsed = true;

        RequiredFieldValidator requiredField2 = new RequiredFieldValidator();
        requiredField2.ID = "RequiredFieldValidator2";
        requiredField2.ErrorMessage = "*";
        field5.Validators.Add(requiredField2);

        Obout.SuperForm.BoundField field6 = new Obout.SuperForm.BoundField();
        field6.DataField = "UnitsOnOrder";
        field6.HeaderText = "Units On Order";
        field6.Collapsed = true;

        RequiredFieldValidator requiredField3 = new RequiredFieldValidator();
        requiredField3.ID = "RequiredFieldValidator3";
        requiredField3.ErrorMessage = "*";
        field6.Validators.Add(requiredField3);
       
        SuperForm1.Fields.Add(field1);
        SuperForm1.Fields.Add(field2);
        SuperForm1.Fields.Add(field3);
        SuperForm1.Fields.Add(field4);
        SuperForm1.Fields.Add(field5);
        SuperForm1.Fields.Add(field6);

        SuperForm1Container.Controls.Add(SuperForm1);
    }
    protected void SuperForm1_DataBound(object sender, EventArgs e)
    {
        if (SuperForm1.CurrentMode != DetailsViewMode.ReadOnly)
        {
            OboutCheckBox discontinuedChk = SuperForm1.GetFieldControl(2) as OboutCheckBox;

            discontinuedChk.ClientSideEvents.OnCheckedChanged = "Discontinued_CheckedChanged";
        }
    }
}
