Imports Obout.SuperForm
Imports System.Data
Imports System.Data.OleDb
Imports System.Collections.Generic
Imports System.Web.UI.WebControls
Partial Class SuperForm_vb_commands_sp
    Inherits System.Web.UI.Page
    Dim SuperForm1 As Obout.SuperForm.SuperForm

    Sub Page_load(ByVal sender As Object, ByVal e As EventArgs)
        SuperForm1 = New SuperForm()
        SuperForm1.ID = "SuperForm1"
        SuperForm1.Title = "Customer Details"
        SuperForm1.DataSourceID = "sds1"
        SuperForm1.AutoGenerateRows = False
        Dim keyNames1() As String = {"CustomerID"}
        SuperForm1.DataKeyNames = keyNames1
        SuperForm1.AllowPaging = True
        SuperForm1.DefaultMode = DetailsViewMode.Edit
        SuperForm1.AutoGenerateInsertButton = True
        SuperForm1.AutoGenerateEditButton = True
        SuperForm1.AutoGenerateDeleteButton = True
        SuperForm1.AllowDataKeysInsert = True

        Dim field11 As Obout.SuperForm.BoundField = New Obout.SuperForm.BoundField()
        field11.DataField = "CustomerID"
        field11.HeaderText = "Customer ID"
        field11.ReadOnly = True

        Dim field12 As Obout.SuperForm.BoundField = New Obout.SuperForm.BoundField()
        field12.DataField = "CompanyName"
        field12.HeaderText = "Company Name"

        Dim field13 As Obout.SuperForm.BoundField = New Obout.SuperForm.BoundField()
        field13.DataField = "ContactName"
        field13.HeaderText = "Contact Name"

        Dim field14 As Obout.SuperForm.BoundField = New Obout.SuperForm.BoundField()
        field14.DataField = "Country"
        field14.HeaderText = "Country"

        SuperForm1.Fields.Add(field11)
        SuperForm1.Fields.Add(field12)
        SuperForm1.Fields.Add(field13)
        SuperForm1.Fields.Add(field14)

        SuperForm1Container.Controls.Add(SuperForm1)

    End Sub
End Class
