Imports Obout.SuperForm
Imports System.Data
Imports System.Data.OleDb
Imports System.Collections.Generic
Imports System.Web.UI.WebControls
Partial Class SuperForm_vb_commands_customize
    Inherits System.Web.UI.Page
    Dim SuperForm1 As Obout.SuperForm.SuperForm
    Sub Page_load(ByVal sender As Object, ByVal e As EventArgs)
        SuperForm1 = New SuperForm()
        SuperForm1.ID = "SuperForm1"
        SuperForm1.DataSourceID = "SqlDataSource1"
        SuperForm1.AutoGenerateRows = True
        SuperForm1.AutoGenerateDateFields = True
        Dim keyNames() As String = {"OrderID"}
        SuperForm1.DataKeyNames = keyNames
        SuperForm1.AllowPaging = True
        SuperForm1.DefaultMode = DetailsViewMode.Edit

        Dim field1 As Obout.SuperForm.CommandField = New Obout.SuperForm.CommandField()

        If (ButtonType1.Checked) Then

            field1.ButtonType = ButtonType.Button

        ElseIf (ButtonType2.Checked) Then

            field1.ButtonType = ButtonType.Image
            field1.EditImageUrl = "resources/icons/Edit.png"
            field1.DeleteImageUrl = "resources/icons/Delete.png"
            field1.NewImageUrl = "resources/icons/Add.png"
            field1.InsertImageUrl = "resources/icons/Save.png"
            field1.UpdateImageUrl = "resources/icons/Save.png"
            field1.CancelImageUrl = "resources/icons/Delete.png"

        Else

            field1.ButtonType = ButtonType.Link
        End If
        field1.ShowCancelButton = ShowCancelButton.Checked
        field1.ShowDeleteButton = ShowDeleteButton.Checked
        field1.ShowEditButton = ShowEditButton.Checked
        field1.ShowInsertButton = ShowInsertButton.Checked
        SuperForm1.Fields.Add(field1)
        SuperForm1Container.Controls.Add(SuperForm1)

    End Sub
End Class