Imports Obout.SuperForm
Imports Obout.Interface
Imports System.Data
Imports System.Data.OleDb
Imports System.Collections.Generic
Imports System.Web.UI.WebControls
Partial Class SuperForm_vb_commands_default
    Inherits System.Web.UI.Page
    Dim SuperForm1 As Obout.SuperForm.SuperForm
    Sub Page_Load(ByVal sender As Object, ByVal e As EventArgs)
        SuperForm1 = New SuperForm()
        SuperForm1.ID = "SuperForm1"
        SuperForm1.Title = "Order Details"
        SuperForm1.DataSourceID = "SqlDataSource1"
        SuperForm1.AutoGenerateInsertButton = True
        SuperForm1.AutoGenerateEditButton = True
        SuperForm1.AutoGenerateDeleteButton = True
        SuperForm1.AllowDataKeysInsert = False
        Dim keyNames1() As String = {"Order ID"}
        SuperForm1.DataKeyNames = keyNames1
        SuperForm1.AllowPaging = True
        SuperForm1.DefaultMode = DetailsViewMode.Edit

        SuperForm1Container.Controls.Add(SuperForm1)
    End Sub

    Sub SuperForm1_DataBound(ByVal sender As Object, ByVal e As EventArgs)

        If SuperForm1.CurrentMode = DetailsViewMode.Insert Then

            Dim shipName As OboutTextBox = CType(SuperForm1.Rows(1).Cells(1).Controls(0).Controls(0), OboutTextBox)
            shipName.Text = "Default Name"

            Dim shipCity As OboutTextBox = CType(SuperForm1.Rows(2).Cells(1).Controls(0).Controls(0), OboutTextBox)
            shipCity.Text = "Default City"

            Dim shipCountry As OboutTextBox = CType(SuperForm1.Rows(3).Cells(1).Controls(0).Controls(0), OboutTextBox)
            shipCountry.Text = "Default Country"

            Dim orderDate As OboutTextBox = CType(SuperForm1.Rows(4).Cells(1).Controls(0).Controls(0), OboutTextBox)
            orderDate.Text = DateTime.Now.ToString("MM/dd/yyyy")

            Dim sent As OboutCheckBox = CType(SuperForm1.Rows(5).Cells(1).Controls(0), OboutCheckBox)
            sent.Checked = True
        End If

    End Sub

End Class
