Imports Obout.SuperForm
Imports System.Data
Imports System.Data.OleDb
Imports System.Collections.Generic
Imports System.Web.UI.WebControls
Partial Class SuperForm_vb_commands_autogenerate
    Inherits System.Web.UI.Page
    Dim SuperForm1 As Obout.SuperForm.SuperForm

    Sub Page_load(ByVal sender As Object, ByVal e As EventArgs)
        SuperForm1 = New SuperForm()
        SuperForm1.ID = "SuperForm1"
        SuperForm1.DataSourceID = "SqlDataSource1"
        SuperForm1.AutoGenerateRows = True
        SuperForm1.AutoGenerateDateFields = True
        Dim keyNames() As String = {"OrderID"}
        SuperForm1.DataKeyNames = keyNames
        SuperForm1.AllowPaging = True

        If Not IsPostBack Then

            SuperForm1.AutoGenerateInsertButton = True
            SuperForm1.AutoGenerateEditButton = True
            SuperForm1.AutoGenerateDeleteButton = True
        End If

        SuperForm1Container.Controls.Add(SuperForm1)
    End Sub

    Sub CheckBox_CheckedChanged(ByVal sender As Object, ByVal e As EventArgs)

        SuperForm1.AutoGenerateEditButton = GenerateEditButton.Checked
        SuperForm1.AutoGenerateDeleteButton = GenerateDeleteButton.Checked
        SuperForm1.AutoGenerateInsertButton = GenerateInsertButton.Checked

        SuperForm1Container.DataBind()
    End Sub
End Class