Imports Obout.SuperForm
Imports System.Data
Imports System.Data.OleDb
Imports System.Collections.Generic
Imports System.Web.UI.WebControls
Imports Obout.Interface
Partial Class SuperForm_vb_fields_passwordfield
    Inherits System.Web.UI.Page
    Dim SuperForm1 As Obout.SuperForm.SuperForm
    Sub Page_load(ByVal sender As Object, ByVal e As EventArgs)
        SuperForm1 = New SuperForm()
        SuperForm1.ID = "SuperForm1"
        SuperForm1.Title = "Registration Form"
        SuperForm1.AutoGenerateRows = False
        SuperForm1.AutoGenerateInsertButton = False
        SuperForm1.AutoGenerateEditButton = False
        SuperForm1.AutoGenerateDeleteButton = False
        Dim keyNames1() As String = {"OrderID"}
        SuperForm1.DataKeyNames = keyNames1
        SuperForm1.AllowPaging = False
        SuperForm1.DefaultMode = DetailsViewMode.Insert

        AddHandler SuperForm1.DataBound, AddressOf SuperForm1_DataBound
        AddHandler SuperForm1.ItemInserting, AddressOf SuperForm1_Inserting

        Dim field1 As Obout.SuperForm.BoundField = New Obout.SuperForm.BoundField()
        field1.DataField = "UserName"
        field1.HeaderText = "Username"
        field1.Required = True

        Dim field2 As Obout.SuperForm.BoundField = New Obout.SuperForm.BoundField()
        field2.DataField = "Password"
        field2.HeaderText = "Password"
        field2.Required = True

        Dim field3 As Obout.SuperForm.BoundField = New Obout.SuperForm.BoundField()
        field3.DataField = "FirstName"
        field3.HeaderText = "First Name"
        field3.Required = True

        Dim field4 As Obout.SuperForm.BoundField = New Obout.SuperForm.BoundField()
        field4.DataField = "LastName"
        field4.HeaderText = "Last Name"
        field4.Required = True

        Dim field5 As Obout.SuperForm.CommandField = New Obout.SuperForm.CommandField()
        field5.ShowInsertButton = True
        field5.ShowCancelButton = False
        field5.InsertText = "Register"
        field5.ButtonType = ButtonType.Button
        field5.ItemStyle.HorizontalAlign = HorizontalAlign.Center

        SuperForm1.Fields.Add(field1)
        SuperForm1.Fields.Add(field2)
        SuperForm1.Fields.Add(field3)
        SuperForm1.Fields.Add(field4)
        SuperForm1.Fields.Add(field5)

        SuperForm1Container.Controls.Add(SuperForm1)

    End Sub

    Sub SuperForm1_Inserting(ByVal sender As Object, ByVal e As DetailsViewInsertEventArgs)

        SuperForm1.Visible = False
        MessagePanel.Visible = True

    End Sub

    Sub SuperForm1_DataBound(ByVal sender As Object, ByVal e As EventArgs)

        If SuperForm1.CurrentMode <> DetailsViewMode.ReadOnly Then

            Dim password As OboutTextBox = CType(SuperForm1.GetFieldControl(1), OboutTextBox)
            password.TextMode = TextBoxMode.Password

        End If

    End Sub

    End Class
