Imports Obout.SuperForm
Imports System.Data
Imports System.Data.OleDb
Imports System.Collections.Generic
Imports System.Web.UI.WebControls
Partial Class SuperForm_vb_fields_datefield_time
    Inherits System.Web.UI.Page
    Dim SuperForm1 As Obout.SuperForm.SuperForm
    Sub Page_load(ByVal sender As Object, ByVal e As EventArgs)
        SuperForm1 = New SuperForm()
        SuperForm1.ID = "SuperForm1"
        SuperForm1.Title = "Order Details"
        SuperForm1.DataSourceID = "SqlDataSource1"
        SuperForm1.AutoGenerateRows = False
        SuperForm1.AutoGenerateInsertButton = True
        SuperForm1.AutoGenerateEditButton = True
        SuperForm1.AutoGenerateDeleteButton = True
        Dim keyNames1() As String = {"OrderID"}
        SuperForm1.DataKeyNames = keyNames1
        SuperForm1.AllowPaging = True
        SuperForm1.DefaultMode = DetailsViewMode.Edit
        SuperForm1.AllowDataKeysInsert = False
        SuperForm1.EnableModelValidation = True

        AddHandler SuperForm1.DataBound, AddressOf SuperForm1_DataBound

        Dim field1 As Obout.SuperForm.BoundField = New Obout.SuperForm.BoundField()
        field1.DataField = "OrderID"
        field1.HeaderText = "Order ID"
        field1.ReadOnly = True
        field1.InsertVisible = False

        Dim field2 As Obout.SuperForm.BoundField = New Obout.SuperForm.BoundField()
        field2.DataField = "ShipName"
        field2.HeaderText = "Ship Name"

        Dim field3 As Obout.SuperForm.DateField = New Obout.SuperForm.DateField()
        field3.DataField = "OrderDate"
        field3.HeaderText = "Order Date"
        field3.DataFormatString = "{0:MM/dd/yyyy hh:mm}"
        field3.ApplyFormatInEditMode = True

        Dim field4 As Obout.SuperForm.DateField = New Obout.SuperForm.DateField()
        field4.DataField = "ShippedDate"
        field4.HeaderText = "Shipped Date"
        field4.DataFormatString = "{0:MM/dd/yyyy hh:mm}"
        field4.ApplyFormatInEditMode = True

        Dim field5 As Obout.SuperForm.DateField = New Obout.SuperForm.DateField()
        field5.DataField = "RequiredDate"
        field5.HeaderText = "Required Date"
        field5.DataFormatString = "{0:MM/dd/yyyy hh:mm}"
        field5.ApplyFormatInEditMode = True

        SuperForm1.Fields.Add(field1)
        SuperForm1.Fields.Add(field2)
        SuperForm1.Fields.Add(field3)
        SuperForm1.Fields.Add(field4)
        SuperForm1.Fields.Add(field5)


        SuperForm1Container.Controls.Add(SuperForm1)

    End Sub
    Sub SuperForm1_DataBound(ByVal sender As Object, ByVal e As EventArgs)

        If SuperForm1.CurrentMode <> DetailsViewMode.ReadOnly Then

            Dim orderDateCal As OboutInc.Calendar2.Calendar = CType(SuperForm1.Rows(2).Cells(1).Controls(0).Controls(1).Controls(0), OboutInc.Calendar2.Calendar)
            orderDateCal.ShowTimeSelector = True
            orderDateCal.DateFormat = "MM/dd/yyyy hh:mm"

            Dim shippedDateCal As OboutInc.Calendar2.Calendar = CType(SuperForm1.Rows(3).Cells(1).Controls(0).Controls(1).Controls(0), OboutInc.Calendar2.Calendar)
            shippedDateCal.ShowTimeSelector = True
            shippedDateCal.DateFormat = "MM/dd/yyyy hh:mm"

            Dim requiredDateCal As OboutInc.Calendar2.Calendar = CType(SuperForm1.Rows(4).Cells(1).Controls(0).Controls(1).Controls(0), OboutInc.Calendar2.Calendar)
            requiredDateCal.ShowTimeSelector = True
            requiredDateCal.DateFormat = "MM/dd/yyyy hh:mm"
        End If
    End Sub
End Class
