Imports Obout.SuperForm
Imports System.Data
Imports System.Data.OleDb
Imports System.Collections.Generic
Imports System.Web.UI.WebControls
Imports Obout.Interface
Imports OboutInc.EasyMenu_Pro
Partial Class SuperForm_vb_layout_tabs
    Inherits System.Web.UI.Page
    Dim SuperForm1 As Obout.SuperForm.SuperForm
    Sub Page_Load(ByVal sender As Object, ByVal e As EventArgs)
        SuperForm1 = New SuperForm()
        SuperForm1.ID = "SuperForm1"
        SuperForm1.Title = "Employee Form"
        SuperForm1.DataSourceID = "SqlDataSource1"
        SuperForm1.AutoGenerateRows = False
        SuperForm1.AutoGenerateInsertButton = True
        SuperForm1.AutoGenerateEditButton = True
        SuperForm1.AutoGenerateDeleteButton = True
        SuperForm1.Width = Unit.Pixel(480)
        Dim keyNames1() As String = {"EmployeeID"}
        SuperForm1.DataKeyNames = keyNames1
        SuperForm1.AllowPaging = True
        SuperForm1.DefaultMode = DetailsViewMode.Edit

        AddHandler SuperForm1.ItemUpdating, AddressOf SuperForm1_ItemUpdating
        AddHandler SuperForm1.ItemInserting, AddressOf SuperForm1_ItemInserting

        Dim field1 As Obout.SuperForm.BoundField = New Obout.SuperForm.BoundField()
        field1.DataField = "EmployeeID"
        field1.HeaderText = "Employee ID:"
        field1.ReadOnly = True
        field1.InsertVisible = False
        field1.Visible = False
        field1.FieldSetID = "FieldSet1"

        Dim field2 As Obout.SuperForm.BoundField = New Obout.SuperForm.BoundField()
        field2.DataField = "FirstName"
        field2.HeaderText = "First Name:"
        field2.FieldSetID = "FieldSet1"

        Dim field3 As Obout.SuperForm.BoundField = New Obout.SuperForm.BoundField()
        field3.DataField = "LastName"
        field3.HeaderText = "Last Name:"
        field3.FieldSetID = "FieldSet1"

        Dim field4 As Obout.SuperForm.TemplateField = New Obout.SuperForm.TemplateField()
        field4.FieldSetID = "FieldSet2"
        field4.ItemTemplate = New TabStripItemTemplate()
        field4.EditItemTemplate = New TabStripEditItemTemplate()

        Dim field5 As Obout.SuperForm.BoundField = New Obout.SuperForm.BoundField()
        field5.DataField = "City"
        field5.HeaderText = "City:"
        field5.FieldSetID = "FieldSet3"

        Dim field6 As Obout.SuperForm.DateField = New Obout.SuperForm.DateField()
        field6.DataField = "BirthDate"
        field6.HeaderText = "Birth Date:"
        field6.FieldSetID = "FieldSet3"
        field6.DataFormatString = "{0:MM/dd/yyyy}"
        field6.ApplyFormatInEditMode = True

        Dim field7 As Obout.SuperForm.BoundField = New Obout.SuperForm.BoundField()
        field7.DataField = "Address"
        field7.HeaderText = "Address:"
        field7.FieldSetID = "FieldSet3"

        Dim field8 As Obout.SuperForm.DateField = New Obout.SuperForm.DateField()
        field8.DataField = "HireDate"
        field8.HeaderText = "Hire Date:"
        field8.FieldSetID = "FieldSet3"
        field8.DataFormatString = "{0:MM/dd/yyyy}"
        field8.ApplyFormatInEditMode = True

        Dim field9 As Obout.SuperForm.BoundField = New Obout.SuperForm.BoundField()
        field9.DataField = "Country"
        field9.HeaderText = "Country:"
        field9.FieldSetID = "FieldSet3"

        Dim field10 As Obout.SuperForm.BoundField = New Obout.SuperForm.BoundField()
        field10.DataField = "Salary"
        field10.HeaderText = "Salary:"
        field10.FieldSetID = "FieldSet3"

        Dim field11 As Obout.SuperForm.BoundField = New Obout.SuperForm.BoundField()
        field11.DataField = "HomePhone"
        field11.HeaderText = "HomePhone:"
        field11.FieldSetID = "FieldSet4"

        Dim field12 As Obout.SuperForm.BoundField = New Obout.SuperForm.BoundField()
        field12.DataField = "Extension"
        field12.HeaderText = "Extension:"
        field12.FieldSetID = "FieldSet4"

        Dim field13 As Obout.SuperForm.BoundField = New Obout.SuperForm.BoundField()
        field13.DataField = "PostalCode"
        field13.HeaderText = "PostalCode:"
        field13.FieldSetID = "FieldSet4"

        Dim field14 As Obout.SuperForm.BoundField = New Obout.SuperForm.BoundField()
        field14.DataField = "Region"
        field14.HeaderText = "Region:"
        field14.FieldSetID = "FieldSet4"

        Dim field15 As Obout.SuperForm.TemplateField = New Obout.SuperForm.TemplateField()
        field15.FieldSetID = "FieldSet5"
        field15.HeaderText = "Notes:"
        field15.ItemTemplate = New EditorItemTemplate()
        field15.EditItemTemplate = New EditorEditItemTemplate()

        Dim fieldSetRow1 As Obout.SuperForm.FieldSetRow = New Obout.SuperForm.FieldSetRow()
        Dim fieldSet1 As Obout.SuperForm.FieldSet = New Obout.SuperForm.FieldSet()
        fieldSet1.ID = "FieldSet1"
        fieldSet1.Direction = Direction.Horizontal
        fieldSet1.CssClass = "field-set"
        fieldSetRow1.Items.Add(fieldSet1)

        Dim fieldSetRow2 As Obout.SuperForm.FieldSetRow = New Obout.SuperForm.FieldSetRow()
        Dim fieldSet2 As Obout.SuperForm.FieldSet = New Obout.SuperForm.FieldSet()
        fieldSet2.ID = "FieldSet2"
        fieldSet2.Direction = Direction.Horizontal
        fieldSet2.CssClass = "field-set"
        fieldSetRow2.Items.Add(fieldSet2)

        Dim fieldSetRow3 As Obout.SuperForm.FieldSetRow = New Obout.SuperForm.FieldSetRow()
        Dim fieldSet3 As Obout.SuperForm.FieldSet = New Obout.SuperForm.FieldSet()
        fieldSet3.ID = "FieldSet3"
        fieldSet3.Direction = Direction.Horizontal
        fieldSet3.CssClass = "field-set field-set-visible"
        fieldSetRow3.Items.Add(fieldSet3)

        Dim fieldSetRow4 As Obout.SuperForm.FieldSetRow = New Obout.SuperForm.FieldSetRow()
        Dim fieldSet4 As Obout.SuperForm.FieldSet = New Obout.SuperForm.FieldSet()
        fieldSet4.ID = "FieldSet4"
        fieldSet4.Direction = Direction.Horizontal
        fieldSet4.CssClass = "field-set field-set-hidden"
        fieldSetRow4.Items.Add(fieldSet4)

        Dim fieldSetRow5 As Obout.SuperForm.FieldSetRow = New Obout.SuperForm.FieldSetRow()
        Dim fieldSet5 As Obout.SuperForm.FieldSet = New Obout.SuperForm.FieldSet()
        fieldSet5.ID = "FieldSet5"
        fieldSet5.Direction = Direction.Horizontal
        fieldSet5.CssClass = "field-set field-set-hidden-editor"
        fieldSetRow5.Items.Add(fieldSet5)

        SuperForm1.FieldSets.Add(fieldSetRow1)
        SuperForm1.FieldSets.Add(fieldSetRow2)
        SuperForm1.FieldSets.Add(fieldSetRow3)
        SuperForm1.FieldSets.Add(fieldSetRow4)
        SuperForm1.FieldSets.Add(fieldSetRow5)

        SuperForm1.Fields.Add(field1)
        SuperForm1.Fields.Add(field2)
        SuperForm1.Fields.Add(field3)
        SuperForm1.Fields.Add(field4)
        SuperForm1.Fields.Add(field5)
        SuperForm1.Fields.Add(field6)
        SuperForm1.Fields.Add(field7)
        SuperForm1.Fields.Add(field8)
        SuperForm1.Fields.Add(field9)
        SuperForm1.Fields.Add(field10)
        SuperForm1.Fields.Add(field11)
        SuperForm1.Fields.Add(field12)
        SuperForm1.Fields.Add(field13)
        SuperForm1.Fields.Add(field14)
        SuperForm1.Fields.Add(field15)
        SuperForm1.FieldHeaderStyle.Width = Unit.Pixel(200)
        SuperForm1Container.Controls.Add(SuperForm1)
    End Sub

    Sub SuperForm1_ItemUpdating(ByVal sender As Object, ByVal e As DetailsViewUpdateEventArgs)

        e.NewValues("Notes") = CType(CType(SuperForm1.Rows(14), DetailsViewRow).FindControl("Editor1"), Obout.Ajax.UI.HTMLEditor.Editor).Content
    End Sub

    Sub SuperForm1_ItemInserting(ByVal sender As Object, ByVal e As DetailsViewInsertEventArgs)

        e.Values("Notes") = CType(CType(SuperForm1.Rows(14), DetailsViewRow).FindControl("Editor1"), Obout.Ajax.UI.HTMLEditor.Editor).Content
    End Sub

    Public Class TabStripItemTemplate
        Implements ITemplate
        Sub InstantiateIn(ByVal container As Control) Implements ITemplate.InstantiateIn

            Dim templatePlaceHolder As PlaceHolder = New PlaceHolder()
            container.Controls.Add(templatePlaceHolder)

            Dim div1 As Literal = New Literal()
            div1.Text = "<div style=""position: relative;"">"

            Dim tabStrip As EasyMenu = New EasyMenu()
            tabStrip.SelectedItemId = "Item_3_1"
            tabStrip.ID = "EasymenuTabStrip1"
            tabStrip.ShowEvent = MenuShowEvent.Always
            tabStrip.StyleFolder = "../EasyMenu/styles/TabStrip2"
            tabStrip.Position = MenuPosition.Horizontal
            tabStrip.Width = "430"

            Dim item1 As OboutInc.EasyMenu_Pro.MenuItem = New OboutInc.EasyMenu_Pro.MenuItem()
            item1.InnerHtml = "<span style='cursor:default'>Personal Information</span>"
            item1.OnClientClick = "SelectTab(3, 1)"
            item1.ID = "Item_3_1"

            Dim item2 As OboutInc.EasyMenu_Pro.MenuItem = New OboutInc.EasyMenu_Pro.MenuItem()
            item2.InnerHtml = "<span style='cursor:default'>Contact Information</span>"
            item2.OnClientClick = "SelectTab(4, 1)"
            item2.ID = "Item_4_1"

            Dim item3 As OboutInc.EasyMenu_Pro.MenuItem = New OboutInc.EasyMenu_Pro.MenuItem()
            item3.InnerHtml = "<span style='cursor:default'>Notes</span>"
            item3.OnClientClick = "SelectTab(5, 1)"
            item3.ID = "Item_5_1"

            tabStrip.Components.Add(item1)
            tabStrip.Components.Add(item2)
            tabStrip.Components.Add(item3)

            Dim div2 As Literal = New Literal()
            div2.Text = "<div class=""tabs-border"">&#160;</div>"

            Dim enddiv1 As Literal = New Literal()
            enddiv1.Text = "</div>"

            templatePlaceHolder.Controls.Add(div1)
            templatePlaceHolder.Controls.Add(tabStrip)
            templatePlaceHolder.Controls.Add(div2)
            templatePlaceHolder.Controls.Add(enddiv1)
        End Sub
    End Class

    Public Class TabStripEditItemTemplate
        Implements ITemplate
        Sub InstantiateIn(ByVal container As Control) Implements ITemplate.InstantiateIn

            Dim templatePlaceHolder As PlaceHolder = New PlaceHolder()
            container.Controls.Add(templatePlaceHolder)

            Dim div1 As Literal = New Literal()
            div1.Text = "<div style=""position: relative;"">"

            Dim tabStrip As EasyMenu = New EasyMenu()
            tabStrip.SelectedItemId = "Item_3_2"
            tabStrip.ID = "EasymenuTabStrip2"
            tabStrip.ShowEvent = MenuShowEvent.Always
            tabStrip.StyleFolder = "../EasyMenu/styles/TabStrip2"
            tabStrip.Position = MenuPosition.Horizontal
            tabStrip.Width = "430"

            Dim item1 As OboutInc.EasyMenu_Pro.MenuItem = New OboutInc.EasyMenu_Pro.MenuItem()
            item1.InnerHtml = "<span style='cursor:default'>Personal Information</span>"
            item1.OnClientClick = "SelectTab(3, 2)"
            item1.ID = "Item_3_2"

            Dim item2 As OboutInc.EasyMenu_Pro.MenuItem = New OboutInc.EasyMenu_Pro.MenuItem()
            item2.InnerHtml = "<span style='cursor:default'>Contact Information</span>"
            item2.OnClientClick = "SelectTab(4, 2)"
            item2.ID = "Item_4_2"

            Dim item3 As OboutInc.EasyMenu_Pro.MenuItem = New OboutInc.EasyMenu_Pro.MenuItem()
            item3.InnerHtml = "<span style='cursor:default'>Notes</span>"
            item3.OnClientClick = "SelectTab(5, 3)"
            item3.ID = "Item_5_3"

            tabStrip.Components.Add(item1)
            tabStrip.Components.Add(item2)
            tabStrip.Components.Add(item3)

            Dim div2 As Literal = New Literal()
            div2.Text = "<div class=""tabs-border"">&#160;</div>"

            Dim enddiv1 As Literal = New Literal()
            enddiv1.Text = "</div>"

            templatePlaceHolder.Controls.Add(div1)
            templatePlaceHolder.Controls.Add(tabStrip)
            templatePlaceHolder.Controls.Add(div2)
            templatePlaceHolder.Controls.Add(enddiv1)
        End Sub
    End Class

    Public Class EditorItemTemplate
        Implements ITemplate
        Sub InstantiateIn(ByVal container As Control) Implements ITemplate.InstantiateIn

            Dim templatePlaceHolder As Literal = New Literal()
            container.Controls.Add(templatePlaceHolder)

            AddHandler templatePlaceHolder.DataBinding, AddressOf DataBindTemplate
        End Sub

        Sub DataBindTemplate(ByVal sender As Object, ByVal e As EventArgs)

            Dim templatePlaceHolder As Literal = CType(sender, Literal)
            Dim row As DetailsViewRow = CType(templatePlaceHolder.Parent.Parent, DetailsViewRow)
            Dim form As SuperForm = CType(row.Parent.Parent, SuperForm)

            templatePlaceHolder.Text = DataBinder.Eval(form.DataItem, "Notes").ToString()
        End Sub
    End Class

    Public Class EditorEditItemTemplate
        Implements ITemplate
        Sub InstantiateIn(ByVal container As Control) Implements ITemplate.InstantiateIn

            Dim templatePlaceHolder As PlaceHolder = New PlaceHolder()
            container.Controls.Add(templatePlaceHolder)

            Dim div As Literal = New Literal()
            div.Text = "<div id=""EditorContainer"">"

            Dim editor1 As Obout.Ajax.UI.HTMLEditor.Editor = New Obout.Ajax.UI.HTMLEditor.Editor()

            templatePlaceHolder.Controls.Add(div)
            templatePlaceHolder.Controls.Add(editor1)

            editor1.ID = "Editor1"
            editor1.TopToolbar.Appearance = Obout.Ajax.UI.HTMLEditor.EditorTopToolbar.AppearanceType.Lite
            editor1.Width = 450
            editor1.Height = 270
            
            Dim enddiv As Literal = New Literal()
            enddiv.Text = "</div>"

            templatePlaceHolder.Controls.Add(enddiv)
        End Sub
    End Class
End Class
