Imports Obout.SuperForm
Imports System.Data
Imports System.Data.OleDb
Imports System.Collections.Generic
Imports System.Web.UI.WebControls
Imports Obout.Interface
Imports OboutInc.EasyMenu_Pro
Partial Class SuperForm_vb_layout_survey
    Inherits System.Web.UI.Page
    Dim SuperForm1 As Obout.SuperForm.SuperForm
    Sub Page_Load(ByVal sender As Object, ByVal e As EventArgs)

        SuperForm1 = New SuperForm()
        SuperForm1.AutoGenerateRows = False
        SuperForm1.FolderStyle = "styles/black_glass"
        SuperForm1.Title = "Company Survey"
        SuperForm1.AutoGenerateInsertButton = False
        SuperForm1.AutoGenerateEditButton = False
        SuperForm1.AutoGenerateDeleteButton = False
        SuperForm1.Width = Unit.Pixel(480)
        SuperForm1.AllowPaging = False
        SuperForm1.DefaultMode = DetailsViewMode.Insert
        SuperForm1.ID = "SuperForm1"

        AddHandler SuperForm1.ItemInserting, AddressOf SuperForm1_ItemInserting

        Dim field1 As Obout.SuperForm.TemplateField = New Obout.SuperForm.TemplateField()
        field1.FieldSetID = "FieldSet1"
        field1.HeaderText = "1) Please describe your position with the company:"
        field1.ItemTemplate = New Field1ItemTemplate()
        field1.EditItemTemplate = New Field1EditItemTemplate()

        Dim field2 As Obout.SuperForm.TemplateField = New Obout.SuperForm.TemplateField()
        field2.FieldSetID = "FieldSet1"
        field2.HeaderText = "2) How long have you worked for the company?"
        field2.ItemTemplate = New Field2ItemTemplate()
        field2.EditItemTemplate = New Field2EditItemTemplate()

        Dim field3 As Obout.SuperForm.TemplateField = New Obout.SuperForm.TemplateField()
        field3.FieldSetID = "FieldSet2"
        field3.HeaderText = "3) Employees have a voice in major decisions regarding changes in the work environment."
        field3.ItemTemplate = New Field3ItemTemplate()
        field3.EditItemTemplate = New Field3EditItemTemplate()

        Dim field4 As Obout.SuperForm.TemplateField = New Obout.SuperForm.TemplateField()
        field4.FieldSetID = "FieldSet2"
        field4.HeaderText = "4) I have received the in-house training I need to get my job done."
        field4.ItemTemplate = New Field4ItemTemplate()
        field4.EditItemTemplate = New Field4EditItemTemplate()

        Dim field5 As Obout.SuperForm.TemplateField = New Obout.SuperForm.TemplateField()
        field5.FieldSetID = "FieldSet2"
        field5.HeaderText = "5) The environment of the workplace is comfortable and safe."
        field5.ItemTemplate = New Field5ItemTemplate()
        field5.EditItemTemplate = New Field5EditItemTemplate()

        Dim field6 As Obout.SuperForm.TemplateField = New Obout.SuperForm.TemplateField()
        field6.FieldSetID = "FieldSet3"
        field6.HeaderText = "6) Employees are treated fairly and equally."
        field6.ItemTemplate = New Field6ItemTemplate()
        field6.EditItemTemplate = New Field6EditItemTemplate()

        Dim field7 As Obout.SuperForm.TemplateField = New Obout.SuperForm.TemplateField()
        field7.FieldSetID = "FieldSet3"
        field7.HeaderText = "7) Management listens to employees."
        field7.ItemTemplate = New Field7ItemTemplate()
        field7.EditItemTemplate = New Field7EditItemTemplate()

        Dim field8 As Obout.SuperForm.TemplateField = New Obout.SuperForm.TemplateField()
        field8.FieldSetID = "FieldSet3"
        field8.HeaderText = "8) I feel under a great deal of stress on my job."
        field8.ItemTemplate = New Field8ItemTemplate()
        field8.EditItemTemplate = New Field8EditItemTemplate()

        Dim field9 As Obout.SuperForm.TemplateField = New Obout.SuperForm.TemplateField()
        field9.FieldSetID = "FieldSet4"
        field9.HeaderText = "9) Please rate the following areas by level of importance with 1 being most important and 6 being least important."
        field9.ItemTemplate = New Field9ItemTemplate()
        field9.EditItemTemplate = New Field9EditItemTemplate()

        Dim field15 As Obout.SuperForm.TemplateField = New Obout.SuperForm.TemplateField()
        field15.FieldSetID = "FieldSet5"
        field15.ItemTemplate = New ButtonItemTemplate()

        Dim fieldSetRow1 As Obout.SuperForm.FieldSetRow = New Obout.SuperForm.FieldSetRow()
        Dim fieldSet1 As Obout.SuperForm.FieldSet = New Obout.SuperForm.FieldSet()
        fieldSet1.ID = "FieldSet1"
        fieldSet1.Direction = Direction.Horizontal
        fieldSet1.CssClass = "field-set field-set-visible"
        fieldSetRow1.Items.Add(fieldSet1)

        Dim fieldSetRow2 As Obout.SuperForm.FieldSetRow = New Obout.SuperForm.FieldSetRow()
        Dim fieldSet2 As Obout.SuperForm.FieldSet = New Obout.SuperForm.FieldSet()
        fieldSet2.ID = "FieldSet2"
        fieldSet2.Direction = Direction.Horizontal
        fieldSet2.CssClass = "field-set field-set-visible field-set-hidden"
        fieldSetRow2.Items.Add(fieldSet2)

        Dim fieldSetRow3 As Obout.SuperForm.FieldSetRow = New Obout.SuperForm.FieldSetRow()
        Dim fieldSet3 As Obout.SuperForm.FieldSet = New Obout.SuperForm.FieldSet()
        fieldSet3.ID = "FieldSet3"
        fieldSet3.Direction = Direction.Horizontal
        fieldSet3.CssClass = "field-set field-set-visible field-set-hidden"
        fieldSetRow3.Items.Add(fieldSet3)

        Dim fieldSetRow4 As Obout.SuperForm.FieldSetRow = New Obout.SuperForm.FieldSetRow()
        Dim fieldSet4 As Obout.SuperForm.FieldSet = New Obout.SuperForm.FieldSet()
        fieldSet4.ID = "FieldSet4"
        fieldSet4.Direction = Direction.Horizontal
        fieldSet4.CssClass = "field-set field-set-visible field-set-hidden"
        fieldSetRow4.Items.Add(fieldSet4)

        Dim fieldSetRow5 As Obout.SuperForm.FieldSetRow = New Obout.SuperForm.FieldSetRow()
        Dim fieldSet5 As Obout.SuperForm.FieldSet = New Obout.SuperForm.FieldSet()
        fieldSet5.ID = "FieldSet5"
        fieldSet5.Direction = Direction.Horizontal
        fieldSet5.CssClass = "field-set field-set-buttons"
        fieldSet5.ColumnSpan = 2
        fieldSet5.HorizontalAlign = HorizontalAlign.Center
        fieldSetRow5.Items.Add(fieldSet5)

        SuperForm1.FieldSets.Add(fieldSetRow1)
        SuperForm1.FieldSets.Add(fieldSetRow2)
        SuperForm1.FieldSets.Add(fieldSetRow3)
        SuperForm1.FieldSets.Add(fieldSetRow4)
        SuperForm1.FieldSets.Add(fieldSetRow5)

        SuperForm1.Fields.Add(field1)
        SuperForm1.Fields.Add(field2)
        SuperForm1.Fields.Add(field3)
        SuperForm1.Fields.Add(field4)
        SuperForm1.Fields.Add(field5)
        SuperForm1.Fields.Add(field6)
        SuperForm1.Fields.Add(field7)
        SuperForm1.Fields.Add(field8)
        SuperForm1.Fields.Add(field9)
        SuperForm1.Fields.Add(field15)


        SuperForm1.FieldHeaderStyle.Width = Unit.Pixel(200)
        SuperForm1Container.Controls.Add(SuperForm1)

    End Sub

    Public Class Field1ItemTemplate
        Implements ITemplate
        Sub InstantiateIn(ByVal container As Control) Implements ITemplate.InstantiateIn

            Dim templatePlaceHolder As Literal = New Literal()
            container.Controls.Add(templatePlaceHolder)

            templatePlaceHolder.Text = "1) Please describe your position with the company:"

        End Sub
    End Class

    Public Class Field1EditItemTemplate
        Implements ITemplate
        Sub InstantiateIn(ByVal container As Control) Implements ITemplate.InstantiateIn

            Dim templatePlaceHolder As PlaceHolder = New PlaceHolder()
            container.Controls.Add(templatePlaceHolder)

            Dim div As Literal = New Literal()
            div.Text = "<div class=""Q1"">"

            Dim textArea As Obout.Interface.OboutTextBox = New Obout.Interface.OboutTextBox()
            textArea.ID = "txt1"
            textArea.TextMode = TextBoxMode.MultiLine
            textArea.Height = 70
            textArea.Width = 400

            Dim requiredFieldValidator1 As System.Web.UI.WebControls.RequiredFieldValidator = New System.Web.UI.WebControls.RequiredFieldValidator()
            requiredFieldValidator1.ID = "RequiredFieldValidator1"
            requiredFieldValidator1.ControlToValidate = "txt1"
            requiredFieldValidator1.ErrorMessage = "*"

            templatePlaceHolder.Controls.Add(div)
            templatePlaceHolder.Controls.Add(textArea)
            templatePlaceHolder.Controls.Add(requiredFieldValidator1)


            Dim enddiv As Literal = New Literal()
            enddiv.Text = "</div>"

            templatePlaceHolder.Controls.Add(enddiv)
        End Sub
    End Class
    Public Class Field2ItemTemplate
        Implements ITemplate
        Sub InstantiateIn(ByVal container As Control) Implements ITemplate.InstantiateIn

            Dim templatePlaceHolder As Literal = New Literal()
            container.Controls.Add(templatePlaceHolder)

            templatePlaceHolder.Text = "2) How long have you worked for the company?"

        End Sub
    End Class

    Public Class Field2EditItemTemplate
        Implements ITemplate
        Sub InstantiateIn(ByVal container As Control) Implements ITemplate.InstantiateIn

            Dim templatePlaceHolder As PlaceHolder = New PlaceHolder()
            container.Controls.Add(templatePlaceHolder)

            Dim div As Literal = New Literal()
            div.Text = "<div class=""Q2"">"

            Dim ddl1 As Obout.Interface.OboutDropDownList = New Obout.Interface.OboutDropDownList()
            templatePlaceHolder.Controls.Add(div)
            templatePlaceHolder.Controls.Add(ddl1)

            ddl1.ID = "OboutDropDownList1"
            ddl1.Width = 400

            Dim item1 As System.Web.UI.WebControls.ListItem = New System.Web.UI.WebControls.ListItem()
            item1.Value = "1"
            item1.Text = "Less than 1 Year"

            Dim item2 As System.Web.UI.WebControls.ListItem = New System.Web.UI.WebControls.ListItem()
            item2.Value = "2"
            item2.Text = "1-2 Years"

            Dim item3 As System.Web.UI.WebControls.ListItem = New System.Web.UI.WebControls.ListItem()
            item3.Value = "3"
            item3.Text = "3-4 Years"

            Dim item4 As System.Web.UI.WebControls.ListItem = New System.Web.UI.WebControls.ListItem()
            item4.Value = "4"
            item4.Text = "5-6 Years"

            Dim item5 As System.Web.UI.WebControls.ListItem = New System.Web.UI.WebControls.ListItem()
            item5.Value = "5"
            item5.Text = "7-8 Years"

            Dim item6 As System.Web.UI.WebControls.ListItem = New System.Web.UI.WebControls.ListItem()
            item6.Value = "6"
            item6.Text = "9-10 Years"

            Dim item7 As System.Web.UI.WebControls.ListItem = New System.Web.UI.WebControls.ListItem()
            item7.Value = "7"
            item7.Text = "More than 10 Years"

            ddl1.Items.Add(item1)
            ddl1.Items.Add(item2)
            ddl1.Items.Add(item3)
            ddl1.Items.Add(item4)
            ddl1.Items.Add(item5)
            ddl1.Items.Add(item6)
            ddl1.Items.Add(item7)

            Dim enddiv As Literal = New Literal()
            enddiv.Text = "</div>"


            templatePlaceHolder.Controls.Add(enddiv)
        End Sub
    End Class
    Public Class Field3ItemTemplate
        Implements ITemplate
        Sub InstantiateIn(ByVal container As Control) Implements ITemplate.InstantiateIn

            Dim templatePlaceHolder As Literal = New Literal()
            container.Controls.Add(templatePlaceHolder)

            templatePlaceHolder.Text = "3) Employees have a voice in major decisions regarding changes in the work environment."

        End Sub
    End Class

    Public Class Field3EditItemTemplate
        Implements ITemplate
        Sub InstantiateIn(ByVal container As Control) Implements ITemplate.InstantiateIn

            Dim templatePlaceHolder As PlaceHolder = New PlaceHolder()
            container.Controls.Add(templatePlaceHolder)

            Dim div As Literal = New Literal()
            div.Text = "<div class=""Q3"">"

            Dim radio31 As Obout.Interface.OboutRadioButton = New Obout.Interface.OboutRadioButton()
            radio31.ID = "OboutRadioButton31"
            radio31.GroupName = "g1"
            radio31.Text = "Strongly Disagree"
            radio31.Width = 125

            Dim radio32 As Obout.Interface.OboutRadioButton = New Obout.Interface.OboutRadioButton()
            radio32.ID = "OboutRadioButton32"
            radio32.GroupName = "g1"
            radio32.Text = "Disagree"
            radio32.Width = 75

            Dim radio33 As Obout.Interface.OboutRadioButton = New Obout.Interface.OboutRadioButton()
            radio33.ID = "OboutRadioButton33"
            radio33.GroupName = "g1"
            radio33.Text = "Agree"
            radio33.Width = 65

            Dim radio34 As Obout.Interface.OboutRadioButton = New Obout.Interface.OboutRadioButton()
            radio34.ID = "OboutRadioButton34"
            radio34.GroupName = "g1"
            radio34.Text = "Strongly Agree"
            radio34.Width = 100

            Dim customValidator3 As CustomValidator = New CustomValidator()
            customValidator3.ID = "CustomValidator3"
            customValidator3.ClientValidationFunction = "validateQuestion3"
            customValidator3.ErrorMessage = "*"

            templatePlaceHolder.Controls.Add(div)
            templatePlaceHolder.Controls.Add(radio31)
            templatePlaceHolder.Controls.Add(radio32)
            templatePlaceHolder.Controls.Add(radio33)
            templatePlaceHolder.Controls.Add(radio34)
            templatePlaceHolder.Controls.Add(customValidator3)

            Dim enddiv As Literal = New Literal()
            enddiv.Text = "</div>"

            templatePlaceHolder.Controls.Add(enddiv)
        End Sub
    End Class
    Public Class Field4ItemTemplate
        Implements ITemplate
        Sub InstantiateIn(ByVal container As Control) Implements ITemplate.InstantiateIn

            Dim templatePlaceHolder As Literal = New Literal()
            container.Controls.Add(templatePlaceHolder)

            templatePlaceHolder.Text = "4) I have received the in-house training I need to get my job done."

        End Sub
    End Class

    Public Class Field4EditItemTemplate
        Implements ITemplate
        Sub InstantiateIn(ByVal container As Control) Implements ITemplate.InstantiateIn

            Dim templatePlaceHolder As PlaceHolder = New PlaceHolder()
            container.Controls.Add(templatePlaceHolder)

            Dim div As Literal = New Literal()
            div.Text = "<div class=""Q3"">"

            Dim radio41 As Obout.Interface.OboutRadioButton = New Obout.Interface.OboutRadioButton()
            radio41.ID = "OboutRadioButton41"
            radio41.GroupName = "g2"
            radio41.Text = "Strongly Disagree"
            radio41.Width = 125

            Dim radio42 As Obout.Interface.OboutRadioButton = New Obout.Interface.OboutRadioButton()
            radio42.ID = "OboutRadioButton42"
            radio42.GroupName = "g2"
            radio42.Text = "Disagree"
            radio42.Width = 75

            Dim radio43 As Obout.Interface.OboutRadioButton = New Obout.Interface.OboutRadioButton()
            radio43.ID = "OboutRadioButton43"
            radio43.GroupName = "g2"
            radio43.Text = "Agree"
            radio43.Width = 65

            Dim radio44 As Obout.Interface.OboutRadioButton = New Obout.Interface.OboutRadioButton()
            radio44.ID = "OboutRadioButton44"
            radio44.GroupName = "g2"
            radio44.Text = "Strongly Agree"
            radio44.Width = 100

            Dim customValidator4 As CustomValidator = New CustomValidator()
            customValidator4.ID = "CustomValidator4"
            customValidator4.ClientValidationFunction = "validateQuestion4"
            customValidator4.ErrorMessage = "*"

            templatePlaceHolder.Controls.Add(div)
            templatePlaceHolder.Controls.Add(radio41)
            templatePlaceHolder.Controls.Add(radio42)
            templatePlaceHolder.Controls.Add(radio43)
            templatePlaceHolder.Controls.Add(radio44)
            templatePlaceHolder.Controls.Add(customValidator4)

            Dim enddiv As Literal = New Literal()
            enddiv.Text = "</div>"

            templatePlaceHolder.Controls.Add(enddiv)
        End Sub
    End Class
    Public Class Field5ItemTemplate
        Implements ITemplate
        Sub InstantiateIn(ByVal container As Control) Implements ITemplate.InstantiateIn

            Dim templatePlaceHolder As Literal = New Literal()
            container.Controls.Add(templatePlaceHolder)

            templatePlaceHolder.Text = "5) The environment of the workplace is comfortable and safe."

        End Sub
    End Class

    Public Class Field5EditItemTemplate
        Implements ITemplate
        Sub InstantiateIn(ByVal container As Control) Implements ITemplate.InstantiateIn

            Dim templatePlaceHolder As PlaceHolder = New PlaceHolder()
            container.Controls.Add(templatePlaceHolder)

            Dim div As Literal = New Literal()
            div.Text = "<div class=""Q3"">"

            Dim radio51 As Obout.Interface.OboutRadioButton = New Obout.Interface.OboutRadioButton()
            radio51.ID = "OboutRadioButton51"
            radio51.GroupName = "g3"
            radio51.Text = "Strongly Disagree"
            radio51.Width = 125

            Dim radio52 As Obout.Interface.OboutRadioButton = New Obout.Interface.OboutRadioButton()
            radio52.ID = "OboutRadioButton52"
            radio52.GroupName = "g3"
            radio52.Text = "Disagree"
            radio52.Width = 75

            Dim radio53 As Obout.Interface.OboutRadioButton = New Obout.Interface.OboutRadioButton()
            radio53.ID = "OboutRadioButton53"
            radio53.GroupName = "g3"
            radio53.Text = "Agree"
            radio53.Width = 65

            Dim radio54 As Obout.Interface.OboutRadioButton = New Obout.Interface.OboutRadioButton()
            radio54.ID = "OboutRadioButton54"
            radio54.GroupName = "g3"
            radio54.Text = "Strongly Agree"
            radio54.Width = 100

            Dim customValidator5 As CustomValidator = New CustomValidator()
            customValidator5.ID = "CustomValidator5"
            customValidator5.ClientValidationFunction = "validateQuestion5"
            customValidator5.ErrorMessage = "*"

            templatePlaceHolder.Controls.Add(div)
            templatePlaceHolder.Controls.Add(radio51)
            templatePlaceHolder.Controls.Add(radio52)
            templatePlaceHolder.Controls.Add(radio53)
            templatePlaceHolder.Controls.Add(radio54)
            templatePlaceHolder.Controls.Add(customValidator5)

            Dim enddiv As Literal = New Literal()
            enddiv.Text = "</div>"

            templatePlaceHolder.Controls.Add(enddiv)
        End Sub
    End Class
    Public Class Field6ItemTemplate
        Implements ITemplate
        Sub InstantiateIn(ByVal container As Control) Implements ITemplate.InstantiateIn

            Dim templatePlaceHolder As Literal = New Literal()
            container.Controls.Add(templatePlaceHolder)

            templatePlaceHolder.Text = "6) Employees are treated fairly and equally."

        End Sub
    End Class

    Public Class Field6EditItemTemplate
        Implements ITemplate
        Sub InstantiateIn(ByVal container As Control) Implements ITemplate.InstantiateIn

            Dim templatePlaceHolder As PlaceHolder = New PlaceHolder()
            container.Controls.Add(templatePlaceHolder)

            Dim div As Literal = New Literal()
            div.Text = "<div class=""Q4"">"

            Dim radio61 As Obout.Interface.OboutRadioButton = New Obout.Interface.OboutRadioButton()
            radio61.ID = "OboutRadioButton61"
            radio61.GroupName = "g4"
            radio61.Text = "Strongly Disagree"
            radio61.Width = 125

            Dim radio62 As Obout.Interface.OboutRadioButton = New Obout.Interface.OboutRadioButton()
            radio62.ID = "OboutRadioButton62"
            radio62.GroupName = "g4"
            radio62.Text = "Disagree"
            radio62.Width = 75

            Dim radio63 As Obout.Interface.OboutRadioButton = New Obout.Interface.OboutRadioButton()
            radio63.ID = "OboutRadioButton63"
            radio63.GroupName = "g4"
            radio63.Text = "Agree"
            radio63.Width = 65

            Dim radio64 As Obout.Interface.OboutRadioButton = New Obout.Interface.OboutRadioButton()
            radio64.ID = "OboutRadioButton64"
            radio64.GroupName = "g4"
            radio64.Text = "Strongly Agree"
            radio64.Width = 100

            Dim customValidator6 As CustomValidator = New CustomValidator()
            customValidator6.ID = "CustomValidator6"
            customValidator6.ClientValidationFunction = "validateQuestion6"
            customValidator6.ErrorMessage = "*"

            templatePlaceHolder.Controls.Add(div)
            templatePlaceHolder.Controls.Add(radio61)
            templatePlaceHolder.Controls.Add(radio62)
            templatePlaceHolder.Controls.Add(radio63)
            templatePlaceHolder.Controls.Add(radio64)
            templatePlaceHolder.Controls.Add(customValidator6)

            Dim enddiv As Literal = New Literal()
            enddiv.Text = "</div>"

            templatePlaceHolder.Controls.Add(enddiv)
        End Sub
    End Class
    Public Class Field7ItemTemplate
        Implements ITemplate
        Sub InstantiateIn(ByVal container As Control) Implements ITemplate.InstantiateIn

            Dim templatePlaceHolder As Literal = New Literal()
            container.Controls.Add(templatePlaceHolder)

            templatePlaceHolder.Text = "7) Management listens to employees."

        End Sub
    End Class

    Public Class Field7EditItemTemplate
        Implements ITemplate
        Sub InstantiateIn(ByVal container As Control) Implements ITemplate.InstantiateIn

            Dim templatePlaceHolder As PlaceHolder = New PlaceHolder()
            container.Controls.Add(templatePlaceHolder)

            Dim div As Literal = New Literal()
            div.Text = "<div class=""Q4"">"

            Dim radio71 As Obout.Interface.OboutRadioButton = New Obout.Interface.OboutRadioButton()
            radio71.ID = "OboutRadioButton71"
            radio71.GroupName = "g5"
            radio71.Text = "Strongly Disagree"
            radio71.Width = 125

            Dim radio72 As Obout.Interface.OboutRadioButton = New Obout.Interface.OboutRadioButton()
            radio72.ID = "OboutRadioButton72"
            radio72.GroupName = "g5"
            radio72.Text = "Disagree"
            radio72.Width = 75

            Dim radio73 As Obout.Interface.OboutRadioButton = New Obout.Interface.OboutRadioButton()
            radio73.ID = "OboutRadioButton73"
            radio73.GroupName = "g5"
            radio73.Text = "Agree"
            radio73.Width = 65

            Dim radio74 As Obout.Interface.OboutRadioButton = New Obout.Interface.OboutRadioButton()
            radio74.ID = "OboutRadioButton74"
            radio74.GroupName = "g5"
            radio74.Text = "Strongly Agree"
            radio74.Width = 100

            Dim customValidator7 As CustomValidator = New CustomValidator()
            customValidator7.ID = "CustomValidator7"
            customValidator7.ClientValidationFunction = "validateQuestion7"
            customValidator7.ErrorMessage = "*"

            templatePlaceHolder.Controls.Add(div)
            templatePlaceHolder.Controls.Add(radio71)
            templatePlaceHolder.Controls.Add(radio72)
            templatePlaceHolder.Controls.Add(radio73)
            templatePlaceHolder.Controls.Add(radio74)
            templatePlaceHolder.Controls.Add(customValidator7)

            Dim enddiv As Literal = New Literal()
            enddiv.Text = "</div>"

            templatePlaceHolder.Controls.Add(enddiv)
        End Sub
    End Class
    Public Class Field8ItemTemplate
        Implements ITemplate
        Sub InstantiateIn(ByVal container As Control) Implements ITemplate.InstantiateIn

            Dim templatePlaceHolder As Literal = New Literal()
            container.Controls.Add(templatePlaceHolder)

            templatePlaceHolder.Text = "8) I feel under a great deal of stress on my job."

        End Sub
    End Class

    Public Class Field8EditItemTemplate
        Implements ITemplate
        Sub InstantiateIn(ByVal container As Control) Implements ITemplate.InstantiateIn

            Dim templatePlaceHolder As PlaceHolder = New PlaceHolder()
            container.Controls.Add(templatePlaceHolder)

            Dim div As Literal = New Literal()
            div.Text = "<div class=""Q4"">"

            Dim radio81 As Obout.Interface.OboutRadioButton = New Obout.Interface.OboutRadioButton()
            radio81.ID = "OboutRadioButton81"
            radio81.GroupName = "g6"
            radio81.Text = "Strongly Disagree"
            radio81.Width = 125

            Dim radio82 As Obout.Interface.OboutRadioButton = New Obout.Interface.OboutRadioButton()
            radio82.ID = "OboutRadioButton82"
            radio82.GroupName = "g6"
            radio82.Text = "Disagree"
            radio82.Width = 75

            Dim radio83 As Obout.Interface.OboutRadioButton = New Obout.Interface.OboutRadioButton()
            radio83.ID = "OboutRadioButton83"
            radio83.GroupName = "g6"
            radio83.Text = "Agree"
            radio83.Width = 65

            Dim radio84 As Obout.Interface.OboutRadioButton = New Obout.Interface.OboutRadioButton()
            radio84.ID = "OboutRadioButton84"
            radio84.GroupName = "g6"
            radio84.Text = "Strongly Agree"
            radio84.Width = 100

            Dim customValidator8 As CustomValidator = New CustomValidator()
            customValidator8.ID = "CustomValidator8"
            customValidator8.ClientValidationFunction = "validateQuestion8"
            customValidator8.ErrorMessage = "*"

            templatePlaceHolder.Controls.Add(div)
            templatePlaceHolder.Controls.Add(radio81)
            templatePlaceHolder.Controls.Add(radio82)
            templatePlaceHolder.Controls.Add(radio83)
            templatePlaceHolder.Controls.Add(radio84)
            templatePlaceHolder.Controls.Add(customValidator8)

            Dim enddiv As Literal = New Literal()
            enddiv.Text = "</div>"

            templatePlaceHolder.Controls.Add(enddiv)
        End Sub
    End Class
    Public Class Field9ItemTemplate
        Implements ITemplate
        Sub InstantiateIn(ByVal container As Control) Implements ITemplate.InstantiateIn

            Dim templatePlaceHolder As Literal = New Literal()
            container.Controls.Add(templatePlaceHolder)

            templatePlaceHolder.Text = "9) Please rate the following areas by level of importance with 1 being most important and 6 being least important."

        End Sub
    End Class

    Public Class Field9EditItemTemplate
        Implements ITemplate
        Sub InstantiateIn(ByVal container As Control) Implements ITemplate.InstantiateIn

            Dim templatePlaceHolder As PlaceHolder = New PlaceHolder()
            container.Controls.Add(templatePlaceHolder)

            Dim divQ5 As Literal = New Literal()
            divQ5.Text = "<div class=""Q5"">"

            Dim div As Literal = New Literal()
            div.Text = "<div id=""scaleNumber"">1&#160;&#160;&#160;&#160;2&#160;&#160;&#160;&#160;3&#160;&#160;&#160;&#160;4&#160;&#160;&#160;&#160;5&#160;&#160;&#160;&#160;6</div>"

            Dim unorderlist As Literal = New Literal()
            unorderlist.Text = "<ul class=""no-bullet"" id=""textArea"">"

            Dim list1 As Literal = New Literal()
            list1.Text = "<li>Employee recognition program</li>"

            Dim list2 As Literal = New Literal()
            list2.Text = "<li>Ability to make decisions</li>"

            Dim list3 As Literal = New Literal()
            list3.Text = "<li>Comfortable work environment</li>"

            Dim list4 As Literal = New Literal()
            list4.Text = "<li>Employee training program</li>"

            Dim list5 As Literal = New Literal()
            list5.Text = "<li>Company picnic</li>"

            Dim list6 As Literal = New Literal()
            list6.Text = "<li>Christmas party</li>"

            Dim divRadiosAreas As Literal = New Literal()
            divRadiosAreas.Text = "<div id=""radiosAreas"">"

            Dim div2 As Literal = New Literal()
            div2.Text = "<div>"

            Dim radio91 As Obout.Interface.OboutRadioButton = New Obout.Interface.OboutRadioButton()
            radio91.ID = "OboutRadioButton91"
            radio91.GroupName = "g7"
            Dim radio92 As Obout.Interface.OboutRadioButton = New Obout.Interface.OboutRadioButton()
            radio92.ID = "OboutRadioButton92"
            radio92.GroupName = "g7"
            Dim radio93 As Obout.Interface.OboutRadioButton = New Obout.Interface.OboutRadioButton()
            radio93.ID = "OboutRadioButton93"
            radio93.GroupName = "g7"
            Dim radio94 As Obout.Interface.OboutRadioButton = New Obout.Interface.OboutRadioButton()
            radio94.ID = "OboutRadioButton94"
            radio94.GroupName = "g7"
            Dim radio95 As Obout.Interface.OboutRadioButton = New Obout.Interface.OboutRadioButton()
            radio95.ID = "OboutRadioButton95"
            radio95.GroupName = "g7"
            Dim radio96 As Obout.Interface.OboutRadioButton = New Obout.Interface.OboutRadioButton()
            radio96.ID = "OboutRadioButton96"
            radio96.GroupName = "g7"

            Dim customValidator91 As CustomValidator = New CustomValidator()
            customValidator91.ID = "CustomValidator91"
            customValidator91.ClientValidationFunction = "validateQuestion91"
            customValidator91.ErrorMessage = "*"

            Dim endDiv2 As Literal = New Literal()
            endDiv2.Text = "</div>"

            Dim div3 As Literal = New Literal()
            div3.Text = "<div>"

            Dim radio97 As Obout.Interface.OboutRadioButton = New Obout.Interface.OboutRadioButton()
            radio97.ID = "OboutRadioButton97"
            radio97.GroupName = "g8"
            Dim radio98 As Obout.Interface.OboutRadioButton = New Obout.Interface.OboutRadioButton()
            radio98.ID = "OboutRadioButton98"
            radio98.GroupName = "g8"
            Dim radio99 As Obout.Interface.OboutRadioButton = New Obout.Interface.OboutRadioButton()
            radio99.ID = "OboutRadioButton99"
            radio99.GroupName = "g8"
            Dim radio910 As Obout.Interface.OboutRadioButton = New Obout.Interface.OboutRadioButton()
            radio910.ID = "OboutRadioButton910"
            radio910.GroupName = "g8"
            Dim radio911 As Obout.Interface.OboutRadioButton = New Obout.Interface.OboutRadioButton()
            radio911.ID = "OboutRadioButton911"
            radio911.GroupName = "g8"
            Dim radio912 As Obout.Interface.OboutRadioButton = New Obout.Interface.OboutRadioButton()
            radio912.ID = "OboutRadioButton912"
            radio912.GroupName = "g8"

            Dim customValidator92 As CustomValidator = New CustomValidator()
            customValidator92.ID = "CustomValidator92"
            customValidator92.ClientValidationFunction = "validateQuestion92"
            customValidator92.ErrorMessage = "*"

            Dim endDiv3 As Literal = New Literal()
            endDiv3.Text = "</div>"

            Dim div4 As Literal = New Literal()
            div4.Text = "<div>"

            Dim radio913 As Obout.Interface.OboutRadioButton = New Obout.Interface.OboutRadioButton()
            radio913.ID = "OboutRadioButton913"
            radio913.GroupName = "g9"
            Dim radio914 As Obout.Interface.OboutRadioButton = New Obout.Interface.OboutRadioButton()
            radio914.ID = "OboutRadioButton914"
            radio914.GroupName = "g9"
            Dim radio915 As Obout.Interface.OboutRadioButton = New Obout.Interface.OboutRadioButton()
            radio915.ID = "OboutRadioButton915"
            radio915.GroupName = "g9"
            Dim radio916 As Obout.Interface.OboutRadioButton = New Obout.Interface.OboutRadioButton()
            radio916.ID = "OboutRadioButton916"
            radio916.GroupName = "g9"
            Dim radio917 As Obout.Interface.OboutRadioButton = New Obout.Interface.OboutRadioButton()
            radio917.ID = "OboutRadioButton917"
            radio917.GroupName = "g9"
            Dim radio918 As Obout.Interface.OboutRadioButton = New Obout.Interface.OboutRadioButton()
            radio918.ID = "OboutRadioButton918"
            radio918.GroupName = "g9"

            Dim customValidator93 As CustomValidator = New CustomValidator()
            customValidator93.ID = "CustomValidator93"
            customValidator93.ClientValidationFunction = "validateQuestion93"
            customValidator93.ErrorMessage = "*"

            Dim endDiv4 As Literal = New Literal()
            endDiv4.Text = "</div>"

            Dim div5 As Literal = New Literal()
            div5.Text = "<div>"

            Dim radio919 As Obout.Interface.OboutRadioButton = New Obout.Interface.OboutRadioButton()
            radio919.ID = "OboutRadioButton919"
            radio919.GroupName = "g10"
            Dim radio920 As Obout.Interface.OboutRadioButton = New Obout.Interface.OboutRadioButton()
            radio920.ID = "OboutRadioButton920"
            radio920.GroupName = "g10"
            Dim radio921 As Obout.Interface.OboutRadioButton = New Obout.Interface.OboutRadioButton()
            radio921.ID = "OboutRadioButton921"
            radio921.GroupName = "g10"
            Dim radio922 As Obout.Interface.OboutRadioButton = New Obout.Interface.OboutRadioButton()
            radio922.ID = "OboutRadioButton922"
            radio922.GroupName = "g10"
            Dim radio923 As Obout.Interface.OboutRadioButton = New Obout.Interface.OboutRadioButton()
            radio923.ID = "OboutRadioButton923"
            radio923.GroupName = "g10"
            Dim radio924 As Obout.Interface.OboutRadioButton = New Obout.Interface.OboutRadioButton()
            radio924.ID = "OboutRadioButton924"
            radio924.GroupName = "g10"

            Dim customValidator94 As CustomValidator = New CustomValidator()
            customValidator94.ID = "CustomValidator94"
            customValidator94.ClientValidationFunction = "validateQuestion94"
            customValidator94.ErrorMessage = "*"

            Dim endDiv5 As Literal = New Literal()
            endDiv5.Text = "</div>"

            Dim div6 As Literal = New Literal()
            div6.Text = "<div>"

            Dim radio925 As Obout.Interface.OboutRadioButton = New Obout.Interface.OboutRadioButton()
            radio925.ID = "OboutRadioButton925"
            radio925.GroupName = "g11"
            Dim radio926 As Obout.Interface.OboutRadioButton = New Obout.Interface.OboutRadioButton()
            radio926.ID = "OboutRadioButton926"
            radio926.GroupName = "g11"
            Dim radio927 As Obout.Interface.OboutRadioButton = New Obout.Interface.OboutRadioButton()
            radio927.ID = "OboutRadioButton927"
            radio927.GroupName = "g11"
            Dim radio928 As Obout.Interface.OboutRadioButton = New Obout.Interface.OboutRadioButton()
            radio928.ID = "OboutRadioButton928"
            radio928.GroupName = "g11"
            Dim radio929 As Obout.Interface.OboutRadioButton = New Obout.Interface.OboutRadioButton()
            radio929.ID = "OboutRadioButton929"
            radio929.GroupName = "g11"
            Dim radio930 As Obout.Interface.OboutRadioButton = New Obout.Interface.OboutRadioButton()
            radio930.ID = "OboutRadioButton930"
            radio930.GroupName = "g11"

            Dim customValidator95 As CustomValidator = New CustomValidator()
            customValidator95.ID = "CustomValidator95"
            customValidator95.ClientValidationFunction = "validateQuestion95"
            customValidator95.ErrorMessage = "*"

            Dim endDiv6 As Literal = New Literal()
            endDiv6.Text = "</div>"

            Dim div7 As Literal = New Literal()
            div7.Text = "<div>"

            Dim radio931 As Obout.Interface.OboutRadioButton = New Obout.Interface.OboutRadioButton()
            radio931.ID = "OboutRadioButton931"
            radio931.GroupName = "g12"
            Dim radio932 As Obout.Interface.OboutRadioButton = New Obout.Interface.OboutRadioButton()
            radio932.ID = "OboutRadioButton932"
            radio932.GroupName = "g12"
            Dim radio933 As Obout.Interface.OboutRadioButton = New Obout.Interface.OboutRadioButton()
            radio933.ID = "OboutRadioButton933"
            radio933.GroupName = "g12"
            Dim radio934 As Obout.Interface.OboutRadioButton = New Obout.Interface.OboutRadioButton()
            radio934.ID = "OboutRadioButton934"
            radio934.GroupName = "g12"
            Dim radio935 As Obout.Interface.OboutRadioButton = New Obout.Interface.OboutRadioButton()
            radio935.ID = "OboutRadioButton935"
            radio935.GroupName = "g12"
            Dim radio936 As Obout.Interface.OboutRadioButton = New Obout.Interface.OboutRadioButton()
            radio936.ID = "OboutRadioButton936"
            radio936.GroupName = "g12"

            Dim customValidator96 As CustomValidator = New CustomValidator()
            customValidator96.ID = "CustomValidator96"
            customValidator96.ClientValidationFunction = "validateQuestion96"
            customValidator96.ErrorMessage = "*"

            Dim endDiv7 As Literal = New Literal()
            endDiv7.Text = "</div>"

            Dim endDdivQ5 As Literal = New Literal()
            endDdivQ5.Text = "</div>"

            Dim endDivRadios As Literal = New Literal()
            endDiv7.Text = "</div>"

            templatePlaceHolder.Controls.Add(divQ5)
            templatePlaceHolder.Controls.Add(div)
            templatePlaceHolder.Controls.Add(unorderlist)
            templatePlaceHolder.Controls.Add(list1)
            templatePlaceHolder.Controls.Add(list2)
            templatePlaceHolder.Controls.Add(list3)
            templatePlaceHolder.Controls.Add(list4)
            templatePlaceHolder.Controls.Add(list5)
            templatePlaceHolder.Controls.Add(list6)
            templatePlaceHolder.Controls.Add(divRadiosAreas)
            templatePlaceHolder.Controls.Add(div2)
            templatePlaceHolder.Controls.Add(CreateSpacer())
            templatePlaceHolder.Controls.Add(radio91)
            templatePlaceHolder.Controls.Add(CreateSpacer())
            templatePlaceHolder.Controls.Add(radio92)
            templatePlaceHolder.Controls.Add(CreateSpacer())
            templatePlaceHolder.Controls.Add(radio93)
            templatePlaceHolder.Controls.Add(CreateSpacer())
            templatePlaceHolder.Controls.Add(radio94)
            templatePlaceHolder.Controls.Add(CreateSpacer())
            templatePlaceHolder.Controls.Add(radio95)
            templatePlaceHolder.Controls.Add(CreateSpacer())
            templatePlaceHolder.Controls.Add(radio96)
            templatePlaceHolder.Controls.Add(customValidator91)
            templatePlaceHolder.Controls.Add(endDiv2)
            templatePlaceHolder.Controls.Add(div3)
            templatePlaceHolder.Controls.Add(CreateSpacer())
            templatePlaceHolder.Controls.Add(radio97)
            templatePlaceHolder.Controls.Add(CreateSpacer())
            templatePlaceHolder.Controls.Add(radio98)
            templatePlaceHolder.Controls.Add(CreateSpacer())
            templatePlaceHolder.Controls.Add(radio99)
            templatePlaceHolder.Controls.Add(CreateSpacer())
            templatePlaceHolder.Controls.Add(radio910)
            templatePlaceHolder.Controls.Add(CreateSpacer())
            templatePlaceHolder.Controls.Add(radio911)
            templatePlaceHolder.Controls.Add(CreateSpacer())
            templatePlaceHolder.Controls.Add(radio912)
            templatePlaceHolder.Controls.Add(customValidator92)
            templatePlaceHolder.Controls.Add(endDiv3)
            templatePlaceHolder.Controls.Add(div4)
            templatePlaceHolder.Controls.Add(CreateSpacer())
            templatePlaceHolder.Controls.Add(radio913)
            templatePlaceHolder.Controls.Add(CreateSpacer())
            templatePlaceHolder.Controls.Add(radio914)
            templatePlaceHolder.Controls.Add(CreateSpacer())
            templatePlaceHolder.Controls.Add(radio915)
            templatePlaceHolder.Controls.Add(CreateSpacer())
            templatePlaceHolder.Controls.Add(radio916)
            templatePlaceHolder.Controls.Add(CreateSpacer())
            templatePlaceHolder.Controls.Add(radio917)
            templatePlaceHolder.Controls.Add(CreateSpacer())
            templatePlaceHolder.Controls.Add(radio918)
            templatePlaceHolder.Controls.Add(customValidator93)
            templatePlaceHolder.Controls.Add(endDiv4)
            templatePlaceHolder.Controls.Add(div5)
            templatePlaceHolder.Controls.Add(CreateSpacer())
            templatePlaceHolder.Controls.Add(radio919)
            templatePlaceHolder.Controls.Add(CreateSpacer())
            templatePlaceHolder.Controls.Add(radio920)
            templatePlaceHolder.Controls.Add(CreateSpacer())
            templatePlaceHolder.Controls.Add(radio921)
            templatePlaceHolder.Controls.Add(CreateSpacer())
            templatePlaceHolder.Controls.Add(radio922)
            templatePlaceHolder.Controls.Add(CreateSpacer())
            templatePlaceHolder.Controls.Add(radio923)
            templatePlaceHolder.Controls.Add(CreateSpacer())
            templatePlaceHolder.Controls.Add(radio924)
            templatePlaceHolder.Controls.Add(customValidator94)
            templatePlaceHolder.Controls.Add(endDiv5)
            templatePlaceHolder.Controls.Add(div6)
            templatePlaceHolder.Controls.Add(CreateSpacer())
            templatePlaceHolder.Controls.Add(radio925)
            templatePlaceHolder.Controls.Add(CreateSpacer())
            templatePlaceHolder.Controls.Add(radio926)
            templatePlaceHolder.Controls.Add(CreateSpacer())
            templatePlaceHolder.Controls.Add(radio927)
            templatePlaceHolder.Controls.Add(CreateSpacer())
            templatePlaceHolder.Controls.Add(radio928)
            templatePlaceHolder.Controls.Add(CreateSpacer())
            templatePlaceHolder.Controls.Add(radio929)
            templatePlaceHolder.Controls.Add(CreateSpacer())
            templatePlaceHolder.Controls.Add(radio930)
            templatePlaceHolder.Controls.Add(customValidator95)
            templatePlaceHolder.Controls.Add(endDiv6)
            templatePlaceHolder.Controls.Add(div7)
            templatePlaceHolder.Controls.Add(CreateSpacer())
            templatePlaceHolder.Controls.Add(radio931)
            templatePlaceHolder.Controls.Add(CreateSpacer())
            templatePlaceHolder.Controls.Add(radio932)
            templatePlaceHolder.Controls.Add(CreateSpacer())
            templatePlaceHolder.Controls.Add(radio933)
            templatePlaceHolder.Controls.Add(CreateSpacer())
            templatePlaceHolder.Controls.Add(radio934)
            templatePlaceHolder.Controls.Add(CreateSpacer())
            templatePlaceHolder.Controls.Add(radio935)
            templatePlaceHolder.Controls.Add(CreateSpacer())
            templatePlaceHolder.Controls.Add(radio936)
            templatePlaceHolder.Controls.Add(customValidator96)
            templatePlaceHolder.Controls.Add(endDiv7)

            templatePlaceHolder.Controls.Add(endDivRadios)
            templatePlaceHolder.Controls.Add(endDdivQ5)

        End Sub

        Protected Function CreateSpacer() As Literal
            Dim spacer As Literal = New Literal()
            spacer.Text = "&#160;"
            Return spacer
        End Function

    End Class

    Public Class ButtonItemTemplate
        Implements ITemplate

        Sub InstantiateIn(ByVal container As Control) Implements ITemplate.InstantiateIn

            Dim templatePlaceHolder As PlaceHolder = New PlaceHolder()
            container.Controls.Add(templatePlaceHolder)

            Dim spanButton1 As Literal = New Literal()
            spanButton1.Text = "<span id=""PreviousButtonContainer"" style=""display: none;"">"

            Dim previousButton As Obout.Interface.OboutButton = New Obout.Interface.OboutButton()
            previousButton.ID = "OboutButton1"
            previousButton.Text = "Back"
            previousButton.OnClientClick = "moveToPreviousStep(); return false"

            Dim endspanButton1 As Literal = New Literal()
            endspanButton1.Text = "</span>"

            Dim spanButton2 As Literal = New Literal()
            spanButton2.Text = "<span id=""NextButtonContainer"">"

            Dim nextButton As Obout.Interface.OboutButton = New Obout.Interface.OboutButton()
            nextButton.ID = "OboutButton2"
            nextButton.Text = "Next"
            nextButton.OnClientClick = "moveToNextStep(); return false"

            Dim endspanButton2 As Literal = New Literal()
            endspanButton2.Text = "</span>"

            Dim spanButton3 As Literal = New Literal()
            spanButton3.Text = "<span id=""SaveButtonContainer"" style=""display: none;"">"

            Dim saveButton As Obout.Interface.OboutButton = New Obout.Interface.OboutButton()
            saveButton.ID = "OboutButton3"
            saveButton.Text = "Save"
            saveButton.CommandName = "Insert"

            Dim endspanButton3 As Literal = New Literal()
            endspanButton3.Text = "</span>"

            templatePlaceHolder.Controls.Add(spanButton1)
            templatePlaceHolder.Controls.Add(previousButton)
            templatePlaceHolder.Controls.Add(endspanButton1)
            templatePlaceHolder.Controls.Add(CreateSpacer())
            templatePlaceHolder.Controls.Add(spanButton2)
            templatePlaceHolder.Controls.Add(nextButton)
            templatePlaceHolder.Controls.Add(endspanButton2)
            templatePlaceHolder.Controls.Add(CreateSpacer())
            templatePlaceHolder.Controls.Add(spanButton3)
            templatePlaceHolder.Controls.Add(saveButton)
            templatePlaceHolder.Controls.Add(endspanButton3)
        End Sub

        Protected Function CreateSpacer() As Literal
            Dim spacer As Literal = New Literal()
            spacer.Text = "&#160;"
            Return spacer
        End Function

    End Class

    Sub SuperForm1_ItemInserting(ByVal sender As Object, ByVal e As DetailsViewInsertEventArgs)

        SuperForm1.Visible = False
        Panel1.Visible = True

        e.Cancel = True

        Question1Answer.Text = CType(CType(SuperForm1.Rows(0), DetailsViewRow).FindControl("txt1"), OboutTextBox).Text
        Question2Answer.Text = CType(CType(SuperForm1.Rows(1), DetailsViewRow).FindControl("OboutDropDownList1"), OboutDropDownList).SelectedItem.Text


        Dim question3Radios As New List(Of OboutRadioButton)()
        question3Radios.Add(CType(CType(SuperForm1.Rows(2), DetailsViewRow).FindControl("OboutRadioButton31"), OboutRadioButton))
        question3Radios.Add(CType(CType(SuperForm1.Rows(2), DetailsViewRow).FindControl("OboutRadioButton32"), OboutRadioButton))
        question3Radios.Add(CType(CType(SuperForm1.Rows(2), DetailsViewRow).FindControl("OboutRadioButton33"), OboutRadioButton))
        question3Radios.Add(CType(CType(SuperForm1.Rows(2), DetailsViewRow).FindControl("OboutRadioButton34"), OboutRadioButton))

        For Each radio As OboutRadioButton In question3Radios
            If radio.Checked Then
                Question3Answer.Text = radio.Text
            End If
        Next

        Dim question4Radios As New List(Of OboutRadioButton)()
        question4Radios.Add(CType(CType(SuperForm1.Rows(2), DetailsViewRow).FindControl("OboutRadioButton41"), OboutRadioButton))
        question4Radios.Add(CType(CType(SuperForm1.Rows(2), DetailsViewRow).FindControl("OboutRadioButton42"), OboutRadioButton))
        question4Radios.Add(CType(CType(SuperForm1.Rows(2), DetailsViewRow).FindControl("OboutRadioButton43"), OboutRadioButton))
        question4Radios.Add(CType(CType(SuperForm1.Rows(2), DetailsViewRow).FindControl("OboutRadioButton44"), OboutRadioButton))

        For Each radio As OboutRadioButton In question4Radios
            If radio.Checked Then
                Question4Answer.Text = radio.Text
            End If
        Next

        Dim question5Radios As New List(Of OboutRadioButton)()
        question5Radios.Add(CType(CType(SuperForm1.Rows(2), DetailsViewRow).FindControl("OboutRadioButton51"), OboutRadioButton))
        question5Radios.Add(CType(CType(SuperForm1.Rows(2), DetailsViewRow).FindControl("OboutRadioButton52"), OboutRadioButton))
        question5Radios.Add(CType(CType(SuperForm1.Rows(2), DetailsViewRow).FindControl("OboutRadioButton53"), OboutRadioButton))
        question5Radios.Add(CType(CType(SuperForm1.Rows(2), DetailsViewRow).FindControl("OboutRadioButton54"), OboutRadioButton))

        For Each radio As OboutRadioButton In question5Radios
            If radio.Checked Then
                Question5Answer.Text = radio.Text
            End If
        Next

        Dim question6Radios As New List(Of OboutRadioButton)()
        question6Radios.Add(CType(CType(SuperForm1.Rows(2), DetailsViewRow).FindControl("OboutRadioButton61"), OboutRadioButton))
        question6Radios.Add(CType(CType(SuperForm1.Rows(2), DetailsViewRow).FindControl("OboutRadioButton62"), OboutRadioButton))
        question6Radios.Add(CType(CType(SuperForm1.Rows(2), DetailsViewRow).FindControl("OboutRadioButton63"), OboutRadioButton))
        question6Radios.Add(CType(CType(SuperForm1.Rows(2), DetailsViewRow).FindControl("OboutRadioButton64"), OboutRadioButton))

        For Each radio As OboutRadioButton In question6Radios
            If radio.Checked Then
                Question6Answer.Text = radio.Text
            End If
        Next

        Dim question7Radios As New List(Of OboutRadioButton)()
        question7Radios.Add(CType(CType(SuperForm1.Rows(2), DetailsViewRow).FindControl("OboutRadioButton71"), OboutRadioButton))
        question7Radios.Add(CType(CType(SuperForm1.Rows(2), DetailsViewRow).FindControl("OboutRadioButton72"), OboutRadioButton))
        question7Radios.Add(CType(CType(SuperForm1.Rows(2), DetailsViewRow).FindControl("OboutRadioButton73"), OboutRadioButton))
        question7Radios.Add(CType(CType(SuperForm1.Rows(2), DetailsViewRow).FindControl("OboutRadioButton74"), OboutRadioButton))

        For Each radio As OboutRadioButton In question7Radios
            If radio.Checked Then
                Question7Answer.Text = radio.Text
            End If
        Next

        Dim question8Radios As New List(Of OboutRadioButton)()
        question8Radios.Add(CType(CType(SuperForm1.Rows(2), DetailsViewRow).FindControl("OboutRadioButton81"), OboutRadioButton))
        question8Radios.Add(CType(CType(SuperForm1.Rows(2), DetailsViewRow).FindControl("OboutRadioButton82"), OboutRadioButton))
        question8Radios.Add(CType(CType(SuperForm1.Rows(2), DetailsViewRow).FindControl("OboutRadioButton83"), OboutRadioButton))
        question8Radios.Add(CType(CType(SuperForm1.Rows(2), DetailsViewRow).FindControl("OboutRadioButton84"), OboutRadioButton))

        For Each radio As OboutRadioButton In question8Radios
            If radio.Checked Then
                Question8Answer.Text = radio.Text
            End If
        Next



        Dim question91Radios As New List(Of OboutRadioButton)()
        question91Radios.Add(CType(CType(SuperForm1.Rows(2), DetailsViewRow).FindControl("OboutRadioButton91"), OboutRadioButton))
        question91Radios.Add(CType(CType(SuperForm1.Rows(2), DetailsViewRow).FindControl("OboutRadioButton92"), OboutRadioButton))
        question91Radios.Add(CType(CType(SuperForm1.Rows(2), DetailsViewRow).FindControl("OboutRadioButton93"), OboutRadioButton))
        question91Radios.Add(CType(CType(SuperForm1.Rows(2), DetailsViewRow).FindControl("OboutRadioButton94"), OboutRadioButton))
        question91Radios.Add(CType(CType(SuperForm1.Rows(2), DetailsViewRow).FindControl("OboutRadioButton95"), OboutRadioButton))
        question91Radios.Add(CType(CType(SuperForm1.Rows(2), DetailsViewRow).FindControl("OboutRadioButton96"), OboutRadioButton))

        For i As Integer = 0 To question91Radios.Count - 1
            If question91Radios(i).Checked Then
                Question91Answer.Text = (i + 1).ToString()
            End If
        Next


        Dim question92Radios As New List(Of OboutRadioButton)()
        question92Radios.Add(CType(CType(SuperForm1.Rows(2), DetailsViewRow).FindControl("OboutRadioButton97"), OboutRadioButton))
        question92Radios.Add(CType(CType(SuperForm1.Rows(2), DetailsViewRow).FindControl("OboutRadioButton98"), OboutRadioButton))
        question92Radios.Add(CType(CType(SuperForm1.Rows(2), DetailsViewRow).FindControl("OboutRadioButton99"), OboutRadioButton))
        question92Radios.Add(CType(CType(SuperForm1.Rows(2), DetailsViewRow).FindControl("OboutRadioButton910"), OboutRadioButton))
        question92Radios.Add(CType(CType(SuperForm1.Rows(2), DetailsViewRow).FindControl("OboutRadioButton911"), OboutRadioButton))
        question92Radios.Add(CType(CType(SuperForm1.Rows(2), DetailsViewRow).FindControl("OboutRadioButton912"), OboutRadioButton))

        For i As Integer = 0 To question92Radios.Count - 1
            If question92Radios(i).Checked Then
                Question92Answer.Text = (i + 1).ToString()
            End If
        Next

        Dim question93Radios As New List(Of OboutRadioButton)()
        question93Radios.Add(CType(CType(SuperForm1.Rows(2), DetailsViewRow).FindControl("OboutRadioButton913"), OboutRadioButton))
        question93Radios.Add(CType(CType(SuperForm1.Rows(2), DetailsViewRow).FindControl("OboutRadioButton914"), OboutRadioButton))
        question93Radios.Add(CType(CType(SuperForm1.Rows(2), DetailsViewRow).FindControl("OboutRadioButton915"), OboutRadioButton))
        question93Radios.Add(CType(CType(SuperForm1.Rows(2), DetailsViewRow).FindControl("OboutRadioButton916"), OboutRadioButton))
        question93Radios.Add(CType(CType(SuperForm1.Rows(2), DetailsViewRow).FindControl("OboutRadioButton917"), OboutRadioButton))
        question93Radios.Add(CType(CType(SuperForm1.Rows(2), DetailsViewRow).FindControl("OboutRadioButton918"), OboutRadioButton))

        For i As Integer = 0 To question93Radios.Count - 1
            If question93Radios(i).Checked Then
                Question93Answer.Text = (i + 1).ToString()
            End If
        Next

        Dim question94Radios As New List(Of OboutRadioButton)()
        question94Radios.Add(CType(CType(SuperForm1.Rows(2), DetailsViewRow).FindControl("OboutRadioButton919"), OboutRadioButton))
        question94Radios.Add(CType(CType(SuperForm1.Rows(2), DetailsViewRow).FindControl("OboutRadioButton920"), OboutRadioButton))
        question94Radios.Add(CType(CType(SuperForm1.Rows(2), DetailsViewRow).FindControl("OboutRadioButton921"), OboutRadioButton))
        question94Radios.Add(CType(CType(SuperForm1.Rows(2), DetailsViewRow).FindControl("OboutRadioButton922"), OboutRadioButton))
        question94Radios.Add(CType(CType(SuperForm1.Rows(2), DetailsViewRow).FindControl("OboutRadioButton923"), OboutRadioButton))
        question94Radios.Add(CType(CType(SuperForm1.Rows(2), DetailsViewRow).FindControl("OboutRadioButton924"), OboutRadioButton))

        For i As Integer = 0 To question94Radios.Count - 1
            If question94Radios(i).Checked Then
                Question94Answer.Text = (i + 1).ToString()
            End If
        Next

        Dim question95Radios As New List(Of OboutRadioButton)()
        question95Radios.Add(CType(CType(SuperForm1.Rows(2), DetailsViewRow).FindControl("OboutRadioButton925"), OboutRadioButton))
        question95Radios.Add(CType(CType(SuperForm1.Rows(2), DetailsViewRow).FindControl("OboutRadioButton926"), OboutRadioButton))
        question95Radios.Add(CType(CType(SuperForm1.Rows(2), DetailsViewRow).FindControl("OboutRadioButton927"), OboutRadioButton))
        question95Radios.Add(CType(CType(SuperForm1.Rows(2), DetailsViewRow).FindControl("OboutRadioButton928"), OboutRadioButton))
        question95Radios.Add(CType(CType(SuperForm1.Rows(2), DetailsViewRow).FindControl("OboutRadioButton929"), OboutRadioButton))
        question95Radios.Add(CType(CType(SuperForm1.Rows(2), DetailsViewRow).FindControl("OboutRadioButton930"), OboutRadioButton))

        For i As Integer = 0 To question95Radios.Count - 1
            If question95Radios(i).Checked Then
                Question95Answer.Text = (i + 1).ToString()
            End If
        Next

        Dim question96Radios As New List(Of OboutRadioButton)()
        question96Radios.Add(CType(CType(SuperForm1.Rows(2), DetailsViewRow).FindControl("OboutRadioButton931"), OboutRadioButton))
        question96Radios.Add(CType(CType(SuperForm1.Rows(2), DetailsViewRow).FindControl("OboutRadioButton932"), OboutRadioButton))
        question96Radios.Add(CType(CType(SuperForm1.Rows(2), DetailsViewRow).FindControl("OboutRadioButton933"), OboutRadioButton))
        question96Radios.Add(CType(CType(SuperForm1.Rows(2), DetailsViewRow).FindControl("OboutRadioButton934"), OboutRadioButton))
        question96Radios.Add(CType(CType(SuperForm1.Rows(2), DetailsViewRow).FindControl("OboutRadioButton935"), OboutRadioButton))
        question96Radios.Add(CType(CType(SuperForm1.Rows(2), DetailsViewRow).FindControl("OboutRadioButton936"), OboutRadioButton))

        For i As Integer = 0 To question96Radios.Count - 1
            If question96Radios(i).Checked Then
                Question96Answer.Text = (i + 1).ToString()
            End If
        Next

    End Sub
End Class
