Imports Obout.SuperForm
Imports System.Data
Imports System.Data.OleDb
Imports System.Collections.Generic
Imports System.Web.UI.WebControls
Imports Obout.Interface
Imports Obout.ComboBox
Partial Class SuperForm_vb_master_detail_combobox
    Inherits System.Web.UI.Page
    Dim SuperForm1 As Obout.SuperForm.SuperForm
    Sub Page_Load(ByVal sender As Object, ByVal e As EventArgs)
        SuperForm1 = New SuperForm()
        SuperForm1.ID = "SuperForm1"
        SuperForm1.Title = "Order Details"
        SuperForm1.DataSourceID = "SqlDataSource2"
        SuperForm1.AutoGenerateRows = False
        SuperForm1.AutoGenerateInsertButton = True
        SuperForm1.AutoGenerateEditButton = True
        SuperForm1.AutoGenerateDeleteButton = True
        SuperForm1.AutoGenerateDateFields = True
        Dim keyNames1() As String = {"OrderID"}
        SuperForm1.DataKeyNames = keyNames1
        SuperForm1.AllowPaging = True
        SuperForm1.DefaultMode = DetailsViewMode.Edit
        AddHandler SuperForm1.ItemUpdated, AddressOf SuperForm1_ItemUpdated
        AddHandler SuperForm1.ItemCommand, AddressOf SuperForm1_ItemCommand

        Dim field1 As Obout.SuperForm.BoundField = New Obout.SuperForm.BoundField()
        field1.DataField = "OrderID"
        field1.HeaderText = "Order ID"
        field1.ReadOnly = True

        Dim field2 As Obout.SuperForm.BoundField = New Obout.SuperForm.BoundField()
        field2.DataField = "ShipName"
        field2.HeaderText = "Ship Name"

        Dim field3 As Obout.SuperForm.BoundField = New Obout.SuperForm.BoundField()
        field3.DataField = "ShipCity"
        field3.HeaderText = "Ship City"

        Dim field4 As Obout.SuperForm.BoundField = New Obout.SuperForm.BoundField()
        field4.DataField = "ShipRegion"
        field4.HeaderText = "Ship Region"

        Dim field5 As Obout.SuperForm.DropDownListField = New Obout.SuperForm.DropDownListField()
        field5.DataField = "ShipCountry"
        field5.HeaderText = "Ship Country"
        field5.DataSourceID = "SqlDataSource3"

        Dim field6 As Obout.SuperForm.DateField = New Obout.SuperForm.DateField()
        field6.DataField = "OrderDate"
        field6.HeaderText = "Order Date"
        field6.DataFormatString = "{0:MM/dd/yyyy}"
        field6.ApplyFormatInEditMode = True

        Dim field7 As Obout.SuperForm.DateField = New Obout.SuperForm.DateField()
        field7.DataField = "ShippedDate"
        field7.HeaderText = "Shipped Date"
        field7.DataFormatString = "{0:MM/dd/yyyy}"
        field7.ApplyFormatInEditMode = True

        Dim field8 As Obout.SuperForm.DateField = New Obout.SuperForm.DateField()
        field8.DataField = "RequiredDate"
        field8.HeaderText = "Required Date"
        field8.DataFormatString = "{0:MM/dd/yyyy}"
        field8.ApplyFormatInEditMode = True

        SuperForm1.Fields.Add(field1)
        SuperForm1.Fields.Add(field2)
        SuperForm1.Fields.Add(field3)
        SuperForm1.Fields.Add(field4)
        SuperForm1.Fields.Add(field5)
        SuperForm1.Fields.Add(field6)
        SuperForm1.Fields.Add(field7)
        SuperForm1.Fields.Add(field8)

        SuperForm1Container.Controls.Add(SuperForm1)
    End Sub
    Sub ComboBox1_SelectedIndexChanged(ByVal sender As Object, ByVal e As ComboBoxItemEventArgs)

        SqlDataSource2.SelectParameters(0).DefaultValue = e.Item.Value
        SuperForm1.DefaultMode = DetailsViewMode.Edit
        SuperForm1.DataBind()

    End Sub
    Sub SuperForm1_ItemCommand(ByVal sender As Object, ByVal e As DetailsViewCommandEventArgs)

        If e.CommandName = "Cancel" Then

            SqlDataSource2.SelectParameters(0).DefaultValue = "0"
            SuperForm1.DataBind()
        End If
    End Sub

    Sub SuperForm1_ItemUpdated(ByVal sender As Object, ByVal e As DetailsViewUpdatedEventArgs)

        SqlDataSource2.SelectParameters(0).DefaultValue = "0"
        SuperForm1.DataBind()
    End Sub
End Class
