Imports Obout.SuperForm
Imports System.Data
Imports System.Data.OleDb
Imports System.Collections.Generic
Imports System.Web.UI.WebControls
Imports Obout.Interface
Imports Obout.ComboBox
Partial Class SuperForm_vb_serverapi_focus
    Inherits System.Web.UI.Page
    Dim SuperForm1 As Obout.SuperForm.SuperForm
    Sub Page_Load(ByVal sender As Object, ByVal e As EventArgs)
        SuperForm1 = New SuperForm()
        SuperForm1.ID = "SuperForm1"
        SuperForm1.DataSourceID = "SqlDataSource1"
        SuperForm1.Title = "Order Details"
        SuperForm1.AutoGenerateInsertButton = True
        SuperForm1.AutoGenerateEditButton = True
        SuperForm1.AutoGenerateDeleteButton = True
        Dim keyNames1() As String = {"Order ID"}
        SuperForm1.DataKeyNames = keyNames1
        SuperForm1.AllowPaging = True
        SuperForm1.DefaultMode = DetailsViewMode.Edit
        SuperForm1.AllowDataKeysInsert = False
        AddHandler SuperForm1.DataBound, AddressOf SuperForm1_DataBound

        SuperForm1Container.Controls.Add(SuperForm1)
    End Sub

    Sub SuperForm1_DataBound(ByVal sender As Object, ByVal e As EventArgs)

        If SuperForm1.CurrentMode = DetailsViewMode.Edit Or SuperForm1.CurrentMode = DetailsViewMode.Insert Then
            CType(SuperForm1.Rows(1).Cells(1).Controls(0).Controls(0), OboutTextBox).Focus()
        End If
    End Sub
End Class
