Imports Obout.SuperForm
Imports System.Data
Imports System.Data.OleDb
Imports System.Collections.Generic
Imports System.Web.UI.WebControls
Imports Obout.Interface
Imports Obout.ComboBox
Partial Class SuperForm_vb_templates_combobox_cascading
    Inherits System.Web.UI.Page
    Dim SuperForm1 As Obout.SuperForm.SuperForm
    Sub Page_Load(ByVal sender As Object, ByVal e As EventArgs)
        SuperForm1 = New SuperForm()
        SuperForm1.ID = "SuperForm1"
        SuperForm1.DataSourceID = "SqlDataSource1"
        SuperForm1.AutoGenerateRows = False
        SuperForm1.AutoGenerateInsertButton = True
        SuperForm1.AutoGenerateEditButton = True
        SuperForm1.AutoGenerateDeleteButton = True
        SuperForm1.AutoGenerateDateFields = True
        Dim keyNames1() As String = {"OrderID"}
        SuperForm1.DataKeyNames = keyNames1
        SuperForm1.AllowPaging = True
        SuperForm1.DefaultMode = DetailsViewMode.Edit
        AddHandler SuperForm1.ItemUpdating, AddressOf SuperForm1_ItemUpdating
        AddHandler SuperForm1.ItemInserting, AddressOf SuperForm1_ItemInserting
        AddHandler SuperForm1.DataBound, AddressOf SuperForm1_DataBound

        Dim field1 As Obout.SuperForm.BoundField = New Obout.SuperForm.BoundField()
        field1.DataField = "OrderID"
        field1.HeaderText = "Order ID"
        field1.ReadOnly = True
        field1.InsertVisible = False

        Dim field2 As Obout.SuperForm.BoundField = New Obout.SuperForm.BoundField()
        field2.DataField = "ShipName"
        field2.HeaderText = "Ship Name"

        Dim field3 As Obout.SuperForm.TemplateField = New Obout.SuperForm.TemplateField()
        field3.HeaderText = "Ship Country"
        field3.ItemTemplate = New ShipCountryItemTemplate()
        field3.EditItemTemplate = New ShipCountryEditItemTemplate(SqlDataSource3)

        Dim field4 As Obout.SuperForm.TemplateField = New Obout.SuperForm.TemplateField()
        field4.HeaderText = "Ship City"
        field4.ItemTemplate = New ShipCityItemTemplate()
        field4.EditItemTemplate = New ShipCityEditItemTemplate()

        SuperForm1.Fields.Add(field1)
        SuperForm1.Fields.Add(field2)
        SuperForm1.Fields.Add(field3)
        SuperForm1.Fields.Add(field4)

        SuperForm1Container.Controls.Add(SuperForm1)

    End Sub

    Public Class ShipCountryItemTemplate
        Implements ITemplate
        Sub InstantiateIn(ByVal container As Control) Implements ITemplate.InstantiateIn
            Dim templatePlaceHolder As Literal = New Literal()
            container.Controls.Add(templatePlaceHolder)

            AddHandler templatePlaceHolder.DataBinding, AddressOf DataBindTemplate
        End Sub

        Sub DataBindTemplate(ByVal sender As Object, ByVal e As EventArgs)

            Dim templatePlaceHolder As Literal = CType(sender, Literal)
            Dim row As DetailsViewRow = CType(templatePlaceHolder.Parent.Parent, DetailsViewRow)
            Dim Form As SuperForm = CType(row.Parent.Parent, SuperForm)

            templatePlaceHolder.Text = DataBinder.Eval(Form.DataItem, "ShipCountry").ToString()
        End Sub
    End Class


    Public Class ShipCountryEditItemTemplate
        Implements ITemplate
        Dim citiesDataSource As SqlDataSource

        Public Sub New(ByVal sds As SqlDataSource)

            citiesDataSource = sds

        End Sub
        Sub InstantiateIn(ByVal container As Control) Implements ITemplate.InstantiateIn

            Dim templatePlaceHolder As PlaceHolder = New PlaceHolder()
            container.Controls.Add(templatePlaceHolder)

            Dim comboBox As Obout.ComboBox.ComboBox = New Obout.ComboBox.ComboBox()
            templatePlaceHolder.Controls.Add(comboBox)

            comboBox.ID = "ShipCountry"
            comboBox.DataSourceID = "SqlDataSource2"
            comboBox.Width = Unit.Percentage(100)
            comboBox.Height = Unit.Pixel(150)
            comboBox.DataValueField = "ShipCountry"
            comboBox.DataTextField = "ShipCountry"
            AddHandler comboBox.SelectedIndexChanged, AddressOf ShipCountry_SelectedIndexChanged
            comboBox.AutoPostBack = True

            AddHandler templatePlaceHolder.DataBinding, AddressOf DataBindTemplate
        End Sub

        Sub DataBindTemplate(ByVal sender As Object, ByVal e As EventArgs)

            Dim templatePlaceHolder As PlaceHolder = CType(sender, PlaceHolder)
            Dim row As DetailsViewRow = CType(templatePlaceHolder.Parent.Parent, DetailsViewRow)
            Dim Form As SuperForm = CType(row.Parent.Parent, SuperForm)

            Dim ComboBox As Obout.ComboBox.ComboBox = CType(templatePlaceHolder.Controls(0), Obout.ComboBox.ComboBox)

            ComboBox.SelectedValue = DataBinder.Eval(Form.DataItem, "ShipCountry").ToString()
        End Sub

        Sub ShipCountry_SelectedIndexChanged(ByVal sender As Object, ByVal e As ComboBoxItemEventArgs)

            citiesDataSource.SelectParameters(0).DefaultValue = e.Item.Value
        End Sub
    End Class

    Public Class ShipCityItemTemplate
        Implements ITemplate
        Sub InstantiateIn(ByVal container As Control) Implements ITemplate.InstantiateIn
            Dim templatePlaceHolder As Literal = New Literal()
            container.Controls.Add(templatePlaceHolder)

            AddHandler templatePlaceHolder.DataBinding, AddressOf DataBindTemplate
        End Sub

        Sub DataBindTemplate(ByVal sender As Object, ByVal e As EventArgs)

            Dim templatePlaceHolder As Literal = CType(sender, Literal)
            Dim row As DetailsViewRow = CType(templatePlaceHolder.Parent.Parent, DetailsViewRow)
            Dim Form As SuperForm = CType(row.Parent.Parent, SuperForm)

            templatePlaceHolder.Text = DataBinder.Eval(Form.DataItem, "ShipCity").ToString()
        End Sub
    End Class

    Public Class ShipCityEditItemTemplate
        Implements ITemplate
        Sub InstantiateIn(ByVal container As Control) Implements ITemplate.InstantiateIn

            Dim templatePlaceHolder As PlaceHolder = New PlaceHolder()
            container.Controls.Add(templatePlaceHolder)

            Dim ComboBox As Obout.ComboBox.ComboBox = New Obout.ComboBox.ComboBox()
            templatePlaceHolder.Controls.Add(ComboBox)

            ComboBox.ID = "ShipCity"
            ComboBox.DataSourceID = "SqlDataSource3"
            ComboBox.Width = Unit.Percentage(100)
            ComboBox.Height = Unit.Pixel(150)
            ComboBox.DataValueField = "ShipCity"
            ComboBox.DataTextField = "ShipCity"
            ComboBox.AppendDataBoundItems = False

        End Sub
    End Class

    Sub SuperForm1_ItemUpdating(ByVal sender As Object, ByVal e As DetailsViewUpdateEventArgs)

        e.NewValues("ShipCountry") = CType(CType(SuperForm1.Rows(2), DetailsViewRow).FindControl("ShipCountry"), Obout.ComboBox.ComboBox).SelectedValue
        e.NewValues("ShipCity") = CType(CType(SuperForm1.Rows(2), DetailsViewRow).FindControl("ShipCity"), Obout.ComboBox.ComboBox).SelectedValue
    End Sub

    Sub SuperForm1_ItemInserting(ByVal sender As Object, ByVal e As DetailsViewInsertEventArgs)

        e.Values("ShipCountry") = CType(CType(SuperForm1.Rows(2), DetailsViewRow).FindControl("ShipCountry"), Obout.ComboBox.ComboBox).SelectedValue
        e.Values("ShipCity") = CType(CType(SuperForm1.Rows(2), DetailsViewRow).FindControl("ShipCity"), Obout.ComboBox.ComboBox).SelectedValue
    End Sub


    Sub SuperForm1_DataBound(ByVal sender As Object, ByVal e As EventArgs)

        If (SuperForm1.CurrentMode = DetailsViewMode.Edit) Then

            SqlDataSource3.SelectParameters(0).DefaultValue = DataBinder.Eval(SuperForm1.DataItem, "ShipCountry").ToString()
            CType(CType(SuperForm1.Rows(2), DetailsViewRow).FindControl("ShipCity"), Obout.ComboBox.ComboBox).SelectedValue = DataBinder.Eval(SuperForm1.DataItem, "ShipCity").ToString()

        Else

            SqlDataSource3.SelectParameters(0).DefaultValue = ""
        End If

    End Sub

End Class
