Imports Obout.SuperForm
Imports System.Data
Imports System.Data.OleDb
Imports System.Collections.Generic
Imports System.Web.UI.WebControls
Imports Obout.Interface
Imports Obout.ComboBox
Partial Class SuperForm_vb_templates_radiobuttonlist
    Inherits System.Web.UI.Page
    Dim SuperForm1 As Obout.SuperForm.SuperForm
    Sub Page_Load(ByVal sender As Object, ByVal e As EventArgs)
        SuperForm1 = New SuperForm()
        SuperForm1.ID = "SuperForm1"
        SuperForm1.DataSourceID = "SqlDataSource1"
        SuperForm1.AutoGenerateRows = False
        SuperForm1.AutoGenerateInsertButton = True
        SuperForm1.AutoGenerateEditButton = True
        SuperForm1.AutoGenerateDeleteButton = True
        SuperForm1.AutoGenerateDateFields = True
        Dim keyNames1() As String = {"CustomerID"}
        SuperForm1.DataKeyNames = keyNames1
        SuperForm1.AllowPaging = True
        SuperForm1.DefaultMode = DetailsViewMode.Edit
        AddHandler SuperForm1.ItemUpdating, AddressOf SuperForm1_ItemUpdating
        AddHandler SuperForm1.ItemInserting, AddressOf SuperForm1_ItemInserting
        AddHandler SuperForm1.DataBound, AddressOf SuperForm1_DataBound

        Dim field1 As Obout.SuperForm.BoundField = New Obout.SuperForm.BoundField()
        field1.DataField = "CustomerID"
        field1.HeaderText = "Customer ID"
        field1.ReadOnly = True
        field1.InsertVisible = False

        Dim field2 As Obout.SuperForm.BoundField = New Obout.SuperForm.BoundField()
        field2.DataField = "CompanyName"
        field2.HeaderText = "Company Name"

        Dim field3 As Obout.SuperForm.BoundField = New Obout.SuperForm.BoundField()
        field3.DataField = "ContactName"
        field3.HeaderText = "Contact Name"

        Dim field4 As Obout.SuperForm.TemplateField = New Obout.SuperForm.TemplateField()
        field4.HeaderText = "Countries"
        field4.ItemTemplate = New CountryItemTemplate()
        field4.EditItemTemplate = New CountryEditItemTemplate()

        SuperForm1.Fields.Add(field1)
        SuperForm1.Fields.Add(field2)
        SuperForm1.Fields.Add(field3)
        SuperForm1.Fields.Add(field4)

        SuperForm1Container.Controls.Add(SuperForm1)

    End Sub
    Public Class CountryItemTemplate
        Implements ITemplate
        Sub InstantiateIn(ByVal container As Control) Implements ITemplate.InstantiateIn
            Dim templatePlaceHolder As Literal = New Literal()
            container.Controls.Add(templatePlaceHolder)

            AddHandler templatePlaceHolder.DataBinding, AddressOf DataBindTemplate
        End Sub

        Sub DataBindTemplate(ByVal sender As Object, ByVal e As EventArgs)

            Dim templatePlaceHolder As Literal = CType(sender, Literal)
            Dim row As DetailsViewRow = CType(templatePlaceHolder.Parent.Parent, DetailsViewRow)
            Dim Form As SuperForm = CType(row.Parent.Parent, SuperForm)

            templatePlaceHolder.Text = DataBinder.Eval(Form.DataItem, "Country").ToString()
        End Sub

    End Class
    Public Class CountryEditItemTemplate
        Implements ITemplate

        Sub InstantiateIn(ByVal container As Control) Implements ITemplate.InstantiateIn

            Dim templatePlaceHolder As PlaceHolder = New PlaceHolder()
            container.Controls.Add(templatePlaceHolder)

            Dim divContainer1 As Literal = New Literal()
            divContainer1.Text = "<div style=""height: 150px; overflow: auto; position: relative;"">"

            Dim RadioButtonList1 As RadioButtonList = New RadioButtonList()
            RadioButtonList1.ID = "Country"
            RadioButtonList1.DataSourceID = "SqlDataSource2"
            RadioButtonList1.Height = Unit.Pixel(150)
            RadioButtonList1.DataValueField = "CountryID"
            RadioButtonList1.DataTextField = "CountryName"

            Dim divContainer2 As Literal = New Literal()
            divContainer2.Text = "</div>"

            templatePlaceHolder.Controls.Add(divContainer1)
            templatePlaceHolder.Controls.Add(RadioButtonList1)
            templatePlaceHolder.Controls.Add(divContainer2)

        End Sub
    End Class
    Sub SuperForm1_DataBound(ByVal sender As Object, ByVal e As EventArgs)

        If SuperForm1.CurrentMode = DetailsViewMode.Edit Then

            Dim _country As String = DataBinder.Eval(SuperForm1.DataItem, "Country").ToString()

            Dim Country As RadioButtonList = CType(CType(SuperForm1.Rows(3), DetailsViewRow).FindControl("Country"), RadioButtonList)

            For Each item As ListItem In Country.Items

                If item.Text = _country Then

                    item.Selected = True
                    Exit For

                End If

            Next
        End If
    End Sub
    Sub SuperForm1_ItemUpdating(ByVal sender As Object, ByVal e As DetailsViewUpdateEventArgs)

        e.NewValues("Country") = GetSelectedCountries()
    End Sub

    Sub SuperForm1_ItemInserting(ByVal sender As Object, ByVal e As DetailsViewInsertEventArgs)

        e.Values("Country") = GetSelectedCountries()
    End Sub
    Function GetSelectedCountries() As String

        Dim Country As RadioButtonList = CType(CType(SuperForm1.Rows(3), DetailsViewRow).FindControl("Country"), RadioButtonList)

        Dim selectedCountryIds As String = ""

        For Each item As ListItem In Country.Items

            If item.Selected = True Then

                If (selectedCountryIds <> "") Then

                    selectedCountryIds += ","
                End If


                selectedCountryIds += item.Value
            End If
        Next

        Return selectedCountryIds
    End Function

End Class

