Imports Obout.SuperForm
Imports System.Data
Imports System.Data.OleDb
Imports System.Collections.Generic
Imports System.Web.UI.WebControls
Imports Obout.Interface
Partial Class SuperForm_vb_validation_required
    Inherits System.Web.UI.Page
    Dim SuperForm1 As Obout.SuperForm.SuperForm
    Sub Page_load(ByVal sender As Object, ByVal e As EventArgs)
        SuperForm1 = New SuperForm()
        SuperForm1.ID = "SuperForm1"
        SuperForm1.Title = "Order Details"
        SuperForm1.DataSourceID = "SqlDataSource1"
        SuperForm1.AutoGenerateRows = False
        SuperForm1.AutoGenerateInsertButton = True
        SuperForm1.AutoGenerateEditButton = True
        SuperForm1.AutoGenerateDeleteButton = True
        Dim keyNames1() As String = {"OrderID"}
        SuperForm1.DataKeyNames = keyNames1
        SuperForm1.AllowPaging = True
        SuperForm1.DefaultMode = DetailsViewMode.Insert
        SuperForm1.AllowDataKeysInsert = False
        SuperForm1.EnableModelValidation = True
        AddHandler SuperForm1.DataBound, AddressOf SuperForm1_DataBound

        Dim RequiredFieldValidator1 As RequiredFieldValidator = New RequiredFieldValidator()
        RequiredFieldValidator1.ID = "RequiredFieldValidator1"
        RequiredFieldValidator1.ErrorMessage = "*"
        RequiredFieldValidator1.InitialValue = "Select a customer ..."

        Dim RequiredFieldValidator2 As RequiredFieldValidator = New RequiredFieldValidator()
        RequiredFieldValidator2.ID = "RequiredFieldValidator2"
        RequiredFieldValidator2.ErrorMessage = "*"
        RequiredFieldValidator2.InitialValue = "Select a country ..."

        Dim field1 As Obout.SuperForm.BoundField = New Obout.SuperForm.BoundField()
        field1.DataField = "OrderID"
        field1.HeaderText = "OrderID"
        field1.ReadOnly = True
        field1.InsertVisible = False

        Dim field2 As Obout.SuperForm.DropDownListField = New Obout.SuperForm.DropDownListField()
        field2.DataField = "CustomerID"
        field2.DisplayField = "CompanyName"
        field2.HeaderText = "Customer"
        field2.DataSourceID = "SqlDataSource3"
        field2.Validators.Add(RequiredFieldValidator1)

        Dim field3 As Obout.SuperForm.DropDownListField = New Obout.SuperForm.DropDownListField()
        field3.DataField = "ShipCountry"
        field3.HeaderText = "Country"
        field3.DisplayField = "ShipCountry"
        field3.DataSourceID = "SqlDataSource2"
        field3.Validators.Add(RequiredFieldValidator2)

        SuperForm1.Fields.Add(field1)
        SuperForm1.Fields.Add(field2)
        SuperForm1.Fields.Add(field3)
        
        SuperForm1Container.Controls.Add(SuperForm1)
    End Sub
    Sub SuperForm1_DataBound(ByVal sender As Object, ByVal e As EventArgs)

        If SuperForm1.CurrentMode <> DetailsViewMode.ReadOnly Then

            Dim customerIDDdl As OboutDropDownList = CType(SuperForm1.GetFieldControl(1), OboutDropDownList)
            customerIDDdl.Items.Insert(0, New ListItem("Select a customer ..."))

            Dim shipCountryDdl As OboutDropDownList = CType(SuperForm1.GetFieldControl(2), OboutDropDownList)
            shipCountryDdl.Items.Insert(0, New ListItem("Select a country ..."))
        End If

    End Sub
End Class
