Imports Obout.SuperForm
Imports System.Data
Imports System.Data.OleDb
Imports System.Collections.Generic
Imports System.Web.UI.WebControls
Imports Obout.Interface
Partial Class SuperForm_vb_validation_type
    Inherits System.Web.UI.Page
    Dim SuperForm1 As Obout.SuperForm.SuperForm
    Sub Page_load(ByVal sender As Object, ByVal e As EventArgs)
        SuperForm1 = New SuperForm()
        SuperForm1.ID = "SuperForm1"
        SuperForm1.Title = "Order Details"
        SuperForm1.DataSourceID = "SqlDataSource1"
        SuperForm1.AutoGenerateRows = False
        SuperForm1.AutoGenerateInsertButton = True
        SuperForm1.AutoGenerateEditButton = True
        SuperForm1.AutoGenerateDeleteButton = True
        Dim keyNames1() As String = {"OrderID"}
        SuperForm1.DataKeyNames = keyNames1
        SuperForm1.AllowPaging = True
        SuperForm1.DefaultMode = DetailsViewMode.Edit

        Dim field4Range As RangeValidator = New RangeValidator()
        field4Range.ID = "RangeValidator1"
        field4Range.MinimumValue = "1900/1/1"
        field4Range.MaximumValue = "2039/12/31"
        field4Range.Type = ValidationDataType.Date
        field4Range.ErrorMessage = "*"

        Dim field5Range As RangeValidator = New RangeValidator()
        field5Range.ID = "RangeValidator2"
        field5Range.MinimumValue = "1900/1/1"
        field5Range.MaximumValue = "2039/12/31"
        field5Range.Type = ValidationDataType.Date
        field5Range.ErrorMessage = "*"

        Dim field6Range As RangeValidator = New RangeValidator()
        field6Range.ID = "RangeValidator3"
        field6Range.MinimumValue = "1900/1/1"
        field6Range.MaximumValue = "2039/12/31"
        field6Range.Type = ValidationDataType.Date
        field6Range.ErrorMessage = "*"

        Dim field7Range As RangeValidator = New RangeValidator()
        field7Range.ID = "RangeValidator4"
        field7Range.MinimumValue = "0.00"
        field7Range.MaximumValue = "999.99"
        field7Range.Type = ValidationDataType.Currency
        field7Range.ErrorMessage = "*"

        Dim field1 As Obout.SuperForm.BoundField = New Obout.SuperForm.BoundField()
        field1.DataField = "OrderID"
        field1.HeaderText = "Order ID"
        field1.ReadOnly = True
        field1.InsertVisible = False

        Dim field2 As Obout.SuperForm.BoundField = New Obout.SuperForm.BoundField()
        field2.DataField = "ShipName"
        field2.HeaderText = "Ship Name"
        field2.Required = True

        Dim field3 As Obout.SuperForm.BoundField = New Obout.SuperForm.BoundField()
        field3.DataField = "ShipCountry"
        field3.HeaderText = "Ship Country"
        field3.Required = True

        Dim field4 As Obout.SuperForm.BoundField = New Obout.SuperForm.BoundField()
        field4.DataField = "OrderDate"
        field4.HeaderText = "Order Date"
        field4.Required = True
        field4.DataFormatString = "{0:MM/dd/yyyy}"
        field4.ApplyFormatInEditMode = True
        field4.Validators.Add(field4Range)

        Dim field5 As Obout.SuperForm.DateField = New Obout.SuperForm.DateField()
        field5.DataField = "ShippedDate"
        field5.HeaderText = "Shipped Date"
        field5.Required = True
        field5.DataFormatString = "{0:MM/dd/yyyy}"
        field5.ApplyFormatInEditMode = True
        field5.Validators.Add(field5Range)

        Dim field6 As Obout.SuperForm.DateField = New Obout.SuperForm.DateField()
        field6.DataField = "RequiredDate"
        field6.HeaderText = "Required Date"
        field6.Required = True
        field6.DataFormatString = "{0:MM/dd/yyyy}"
        field6.ApplyFormatInEditMode = True
        field6.Validators.Add(field6Range)

        Dim field7 As Obout.SuperForm.BoundField = New Obout.SuperForm.BoundField()
        field7.DataField = "Freight"
        field7.HeaderText = "Freight"
        field7.Required = True
        field7.DataFormatString = "{0:C2}"
        field7.ApplyFormatInEditMode = False
        field7.Validators.Add(field7Range)

        SuperForm1.Fields.Add(field1)
        SuperForm1.Fields.Add(field2)
        SuperForm1.Fields.Add(field3)
        SuperForm1.Fields.Add(field4)
        SuperForm1.Fields.Add(field5)
        SuperForm1.Fields.Add(field6)
        SuperForm1.Fields.Add(field7)

        SuperForm1Container.Controls.Add(SuperForm1)
    End Sub

End Class
